### ISSUE TITLE
Add extensive Linux Docker setup instructions

### ISSUE THREAD

**Issue by bojanz** [drud/ddev#1002]
Tried ddev for the first time, on a brand new Ubuntu 18.04 install. I've previously only played with Docker on a mac, so this was new ground for me, making me your ideal test subject. My experience was bumpy, I spent an under-caffeinated hour getting everything to work.

Once I installed ddev, I got a message saying that Docker and Docker Composer are not installed.
My expectation was that the ddev install script would do this for me, since I'm on a OS where both are a few commands away. Nevermind, I'll just paste the commands from the docs. However, ddev didn't give me a link to its docs that shows what I need to paste, it sends me to Docker's confusing marketing website, which takes me to a [page](https://store.docker.com/editions/community/docker-ce-server-ubuntu) listing supported Ubuntu versions, none of them 18.04. I get confused and give up. Decide to install Docker myself. Google for "Install docker" and click the first link, which tells me to do an "apt install docker-io". This is the Docker from the official Ubuntu repo, and it's too old for ddev. I learn that after I've installed it. I go back and uninstall docker-io. Then I follow the next link, which tells me to add the external Docker repo and do an apt install.

The tutorial that did the trick was https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04, though I also initially skipped the "optional" step of configuring Docker for non-root, which required me to sudo all ddev commands. This step was mentioned in the ddev docs, but I was already away from them due to needing to figure out what to do with Docker.

My bumpy experience would have been much less bumpy if there was an official ddev docs page that at least sent me to the digitalocean tutorial, with notes saying "don't use ubuntu's docker" and "now setup docker to run without root".

**Comment by rfay** [comment]
Great to have you taking ddev for a spin! 

Linux is kind of hard because docker has different instructions for every variety. The right way to do ubuntu and debian is to install the docker debian repo, I imagine that's what you did.

Don't forget the post-install instructions, which we do have several links to. https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

Thanks for the prod, we can maybe have a separate section with links on ubuntu techniques, I agree it's hard to get to the right place on docker.com, and they keep fooling with it. We currently link to https://www.docker.com/community-edition, which *finally* links to the right place, https://docs.docker.com/install/linux/docker-ce/ubuntu/ but it's definitely a crazy set of links.

**Comment by rfay** [comment]
It might be possible for ddev or the install script to just check to see if the group setup has been done, would save Linux users new to docker a lot of pain.

**Comment by rfay** [comment]
@bojanz would love it if you could review the docs changes in https://github.com/drud/ddev/pull/1041

**Comment by rfay** [comment]
Fixed in #1041
