### ISSUE TITLE
Officially Support Magento v1 and v2

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#1011]
**Is your feature request related to a problem? Please describe.**
There has been several requests for Magento supportAfter the CMS refactor work, we were able to bring in other CMS's (e.g. Backdrop). However, we need to have some additional guidance from Magento end-users.

**Describe the solution you'd like**
Magento as a 1st class CMS citizen. In order to address the following in order to have official support: (non-exhaustive list):

* Documentation
* App type detection
* DB settings file generation.
* import-db support
* import-files support
* test coverage for Magento install
* Custom nginx file

**Describe alternatives you've considered**
Technically, end-users can use the "php" app, but we've heard that users have needed a bit of custom configuration to make it work. To do this right, we want to make this work out of the box. This will also be important when we have the UI and the ability to start from a stock install.

**Additional context**

At this time, this is not on our timeline until we have enough demand as well as Magento devs that can help us confirm this.

**Comment by vanpoppel** [comment]
This would be a nice feature for me (as a Magento dev). I already got it running nicely through the "php" app.

A 'must' for me to use it would be to have n98-magerun available (great Magento tool set).

Would like to contribute, i just haven't had any time yet to get into it.

**Comment by rickmanelius** [comment]
@vanpoppel Did you have to do anything special (add libraries, generate files, etc) to get through the installer? And was this for Magento 1 or 2?

I realize you may not have much time to dedicate to this, but any pointers would be helpful!

**Comment by Ahmed-Ayman** [comment]
can't wait!

**Comment by marvinhuebner** [comment]
DDEV support for Magento (2) would be really great. Especially for me, for example, who only does things at the frontend from time to time and doesn't know the server requirements so well, extremely helpful. 
___

> @vanpoppel Did you have to do anything special (add libraries, generate files, etc) to get through the installer? And was this for Magento 1 or 2? 

@vanpoppel may be able to answer that even better, but if I may speak for him, n98-magerun should only be interesting for Magento 1, because starting with Magento 2, the core brings its own CLI commands with it.

**Comment by rfay** [comment]
Since ddev "just works" for every PHP setup we know of, we'd love to have you give this a try @marvinhuebner - just use the 'php' project type, and set up your own settings files. If you could report back with a recipe, that's the starting point! Thanks!

**Comment by onigunn** [comment]
I've stumbled across a magento 1.9 project and added this into my config.yaml

```
hooks:
   post-start:
        - exec: "bash -c 'cd /usr/local/bin && sudo wget https://files.magerun.net/n98-magerun.phar && sudo chmod +x n98-magerun.phar'"
```

Works. A simple `ddev exec n98-magerun.phar` and we're fine.

**Comment by benmarks** [comment]
Taking a look at this.

**Comment by rfay** [comment]
As you probably saw, the PR from @paulvandermeijs is at https://github.com/drud/ddev/pull/1802

**Comment by jwohlfeil** [comment]
Magento 2 is working perfectly with ddev, but Magento 1 doesn't support MariaDB as far as i know (https://devdocs.magento.com/guides/m1x/system-requirements.html). During importing a DB from a 1.9 installation there are some errors. Is there an easy way to get MySQL for such projects?

**Comment by rfay** [comment]
The next release of ddev will support mysql 5.5/6/7 and 8.0, that should be before the end of the year. A prerelease can be expected even before that. 

For now, ddev-contrib has a recipe for using mysql as an add-on service: https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/mysql

**Comment by jwohlfeil** [comment]
With the support of other mysql versions things getting a bit easier. But i still have problems with session handling, f.e. adding products to cart and login is not working. Tested it with several installations. Anyone else?

**Comment by rfay** [comment]
We hope to have explicit support for magento in the next release via https://github.com/drud/ddev/pull/1802 - I don't think that works right now, but would love to have you test it when it's working again, which shouldn't be long.

Are you using nginx or apache?

**Comment by jwohlfeil** [comment]
Great to hear! Mainly Apache, but one customer of mine is using nginx
extensively.


Von: Randy Fay <notifications@github.com> <notifications@github.com>
Antworten: drud/ddev
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 8. Januar 2020 at 15:00:15
An: drud/ddev <ddev@noreply.github.com> <ddev@noreply.github.com>
CC: Jan Wohlfeil <jan.wohlfeil@digitalhoch3.de>
<jan.wohlfeil@digitalhoch3.de>, Comment <comment@noreply.github.com>
<comment@noreply.github.com>
Betreff:  Re: [drud/ddev] Officially Support Magento v1 and v2 (#1011)

We hope to have explicit support for magento in the next release via #1802
<https://github.com/drud/ddev/pull/1802> - I don't think that works right
now, but would love to have you test it when it's working again, which
shouldn't be long.

Are you using nginx or apache?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/drud/ddev/issues/1011?email_source=notifications&email_token=AADMK4PRRWCYOUVM2VU7RP3Q4XL67A5CNFSM4FLUSGE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIMQ4LQ#issuecomment-572067374>,
or unsubscribe
