### ISSUE TITLE
How to debug container healthcheck failures

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#1024]
**Is your feature request related to a problem? Please describe.**
When your custom nginx configuration is broken (e.g. you forgot to add /fpmstatus location to the nginx-site.conf, then ddev will fail to start without any meaningful information.
Also ddev logs is not helpful in this case. 

**Describe the solution you'd like**
I would like to get a clear message like "Can not connect to nginx on http://..../fpmstatus", please check if your `nginx-site.conf` contains a `/fpmstatus` endpotint.

**Comment by rfay** [comment]
Definitely a good point. Related [Reorganize nginx configs to share most elements #849](https://github.com/drud/ddev/issues/849), a custom nginx config really shouldn't have to do any of this.

And another annoyance: Because of apache change in (hopefully) next release, the /fpmstatus endpoint will probably change to /phpstatus. It's possible we can do something meaningful in there to fix that. AFAIK docker-compose doesn't inform us very well of what's going on. But maybe we can find something. I'd sure love to see this fixed.

BTW, could you mention what you're still having to do for custom nginx config? It would help to give a gist to the actual config that broke you as well.

**Comment by tmotyl** [comment]
Hi @rfay,
I did some tests, and after adding error message to stderr in the healthcheck.sh, I can see it when calling `docker inspect` in the `log` section. This not ideal (as not everybody would check inspect), but at last gives you some hints.

**Comment by rfay** [comment]
Excellent, thanks!

**Comment by rfay** [comment]
I use and recommend 

Web container: `docker inspect --format "{{json .State.Health }}" ddev-<project>-web | jq` (for web container failure)
ddev-router: `docker inspect --format "{{json .State.Health }}" ddev-router`
