### ISSUE TITLE
Provide a wp-cli command hint to adjust WP production URL

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#108]
## What happened (or feature request):
Feature Request

In short, Wordpress relies heavily on the full URL of the site. Unlike Drupal, Wordpress does not store paths to uploaded files as relative paths. They are instead referenced by the full URL path to the asset. This means that in order to deploy a copy of a wordpress site that will run from a different URL than the original, the URL must be configured in `wp-config.php`, and the URLs referenced throughout the database are usually updated with a search/replace. I believe we implemented an alternative w/ rewrite rules, but either way we will need to provide a way for the end user to define the original URL of the site they are importing.

## What you expected to happen:
A configuration option should be provided in our `config.yaml` to allow the user to define the original URL of the site they are importing. `ddev import` should then take this value into account when executing the import, and the end result should be a site that is fully navigable with working assets that load from local files.

## How to reproduce it (as minimally and precisely as possible):
n/a

## Anything else do we need to know:
The `WP_SITEURL` value *can* be defined in the database. I believe this is actually the default behavior, but the wp docs recommend setting in the config file for slight performance benefit. We may be able to read this value and perform the update without user definition, but this would not be reliable for all sites. None of the newmedia sites for example would have this value set.

## Related source links or issues (like source JIRA issue):
#32 wordpress support
#33 asset imports for local platform

## TODO

* [x] Provision new ticket for post hook functionality #183

**Comment by rickmanelius** [comment]
I'm revisiting this because I feel it's imperative that we test/confirm that we can get a working WP site with image assets. Without this in place, imports will always appear broken to user that doesn't understand how to perform the seach/replace with WP-CLI.

**Comment by rickmanelius** [comment]
Moving this one milestone out. While it definitely needs to be addressed by the time we're at provider plugins, we still need some sort of short term functionality for end-users.

**Comment by rickmanelius** [comment]
As we discussed in our conversation outside the issue queue, we will solve this temporarily by outputting the instructions for WP-CLI for WordPress type projects. We will then provision another ticket to address the post-hook functionality/

**Comment by beeradb** [comment]
It looks like this can be closed as well? we have #183 in place which I believe covers the followup steps.

**Comment by rfay** [comment]
Completed in https://github.com/drud/ddev/issues/184

**Comment by rickmanelius** [comment]
I need to re-open this issue to address a few issues discovered while testing:

1. Technically, we've installed `wp-cli` in the webserver container and did not rename to the shortened `wp`. The preference is to fix this by renaming `wp-cli` to `wp` so the instruction is accurate.
2. Copying and pasting the command doesn't work out the box because you get the following warning: 

```
➜  drudio git:(master) ✗ ddev exec 'wp-cli search-replace https://www.drud.com http://drudio.ddev.local'
Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress install exists under.

If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.

If you'd like to continue as root, please run this again, adding this flag:  --allow-root

If you'd like to run it as the user that this site is under, you can run the following to become the respective user:

    sudo -u USER -i -- wp <command>
```
I would suggest we either a) not run `ddev exec` as root OR specify the flag in the prompt so an end-user is more likely to be successful.

3. Spelling error in the prompt s/acroos/across/.
4. It's a nitpick, but it was unclear if there was some weird syntax reason for including the [] on the WP-CLI search replace.
5. Let's finish with "For more information, see http://wp-cli.org/commands/search-replace/."

**Comment by rfay** [comment]
This is yet another reason to just not run containers as root. Kudos to wp-cli for complaining. 

Good catches!

**Comment by tannerjfco** [comment]
1. `wp` is a valid command to run in the web container, we have a wrapper script for wp-cli. If it didn't work for you, you might have outdated configuration, as this script was recently re-introduced from inadvertent removal.
2. The command you entered looks to be totally valid. Looks to be related to 1)
3. Impossible. I never make spelling errors. :P
4. I wanted to indicate that it's a value to be replaced. Perhaps it would be clearer to use `<>` vs `[]`?
5. Works for me :+1:

**Comment by rickmanelius** [comment]
Hey @tannerjfco. Thanks for the quick turn around. Please let me know how to get the wrapper script working so that I can resolve items 1 and 2. Looks like 3 and 5 are quick wins. Regarding 4, I totally get what you were going for. How about this. Given this is a short term fix and ultimately we want to have this as a post import hook, let's leave 4 as is with the hope that this hinting is deprecated in the near future.

**Comment by tannerjfco** [comment]
@rickmanelius what is the web container version for your project? You can either check by reviewing your config.yaml, or running `docker ps` when running should show the image being run for the web container. You should have the latest version `drud/nginx-php-fpm7-local:v0.3.5`

**Comment by rickmanelius** [comment]
@tannerjfco You're correct that the test I was running against was using an old version of .ddev/config.yml. I keep forgetting that the best way to test this is to kill the repo completely so as to not have an older version of the configuration lingering. I ran `ddev config`, but it was still referring to v0.3.4. Retesting...

**Comment by rfay** [comment]
Actually, you don't have to kill the whole repo - consider `ddev rm; rm -rf .ddev; ddev config; ddev start`

**Comment by beeradb** [comment]
@rickmanelius for the future, just removing the site and then deleting `~/.ddev/config.yaml` before running config will get you to the latest container versions. At this point we don't update container versions when re-running config, since we have no promise of not breaking compatibility. This is probably a long-term strategy we need to decide on, though.

**Comment by rickmanelius** [comment]
@beeradb @rfay Thanks for the alternatives. Regardless, I just need to update my testing strategy to consistently include one of these options, and I will note said option when I post my review. Thanks!

**Comment by rfay** [comment]
It's actually not entirely your fault. We have a flaw here in how we use the config.yaml and its persistence in sites. It's going to bite us over and over in the way you just got bitten, and at some point we have to think about how it matters to the user. We've been working on that by making the container specs optional, and the name and other details optional, but we don't have a clear strategy.  So really, it's not you, it's you experiencing a problem we're going to have until we deal with it.

**Comment by rickmanelius** [comment]
Closing this issue now that the PR is merged and the two primary issues I was dealing with were more a result of the wrong container being used.

**Comment by tannerjfco** [comment]
Follow up items resolved, closing.
