### ISSUE TITLE
Corporate Proxy Support

### ISSUE THREAD

**Issue by NickStees** [drud/ddev#1125]
Currently getting this type of error, when trying to use drush, which is likely due to my corporate proxy on Windows 10. 
```
Failed to get available update data from                             [error]
https://updates.drupal.org/release-history/registry_rebuild/7.x
Could not download requested project(s).                             [error]
```

**Is your feature request related to a problem? Please describe.**
The containers cannot access the internet due to being behind a corporate proxy. There should be a way to pass in Proxy configuration to the containers so they can download assets such as using drush. 

**Describe the solution you'd like**
In other Linux docker containers, I normally have to do something like the following where $PROXY is an environment variable. 

- ARG PROXY
- ENV PROXY $PROXY
- COPY config/.wgetrc /etc/wgetrc/
- ENV http_proxy $PROXY
- ENV https_proxy $PROXY

**Describe alternatives you've considered**
Verified my Windows 10 OS has the correct HTTP_PROXY set in Enviroment Variables (some software automatically picks these up and uses them, DDEV did not)

**Additional context**
I looked over the docs.readthedocs and searched previous issues but couldn't locate anything regarding proxy settings for the DDEV containers.

**Comment by rfay** [comment]
I don't think this is something related to ddev; you need to configure Drupal properly. See https://www.drupal.org/project/drupal/issues/2687623

**Comment by rfay** [comment]
Closing, feel free to continue the conversation. But you should be able to do the right thing in settings.local.php on D8

**Comment by rfay** [comment]
Thanks - This really is a web client problem, and in this case Drupal is the client, so that's where the solution will be. It does look like https://www.drupal.org/project/update_status_proxy has links to all the relevant issues. The D7 issue appears to have been solved.

I also see https://www.drupal.org/project/http_proxy, which appears to be maintained for d7. 

It sounds like you've stumbled on a very longstanding Drupal issue, but a pretty standard one. I'm surprised you haven't had this problem in every other environment.

**Comment by rfay** [comment]
Oh, here's the thing. It's actually in D7's default.settings.php

```
/**
 * External access proxy settings:
 *
 * If your site must access the Internet via a web proxy then you can enter
 * the proxy settings here. Currently only basic authentication is supported
 * by using the username and password variables. The proxy_user_agent variable
 * can be set to NULL for proxies that require no User-Agent header or to a
 * non-empty string for proxies that limit requests to a specific agent. The
 * proxy_exceptions variable is an array of host names to be accessed directly,
 * not via proxy.
 */
# $conf['proxy_server'] = '';
# $conf['proxy_port'] = 8080;
# $conf['proxy_username'] = '';
# $conf['proxy_password'] = '';
# $conf['proxy_user_agent'] = '';
# $conf['proxy_exceptions'] = array('127.0.0.1', 'localhost');
```

**Comment by NickStees** [comment]
Ok, yeah looks like our other sites also have https://www.drupal.org/project/chr which is probably the fix I need to have on this site as well. Ok since this is not a DDEV issue ill keep trying things. When I try to run `ddev exec drush en chr` 
I get a 
`WD php: Error: Call to undefined function dmemcache_object_cluster() [error] in memcache_admin_menu() (line 63 of  /var/www/html/docroot/sites/all/modules/contrib/memcache/memcache_admin/memcache_admin.module).` so time for more googling :). 

Thanks for the help!

**Comment by wtfred** [comment]
Waiting for a global way to do this, here is how i do for each ddev project:
Create a file `./ddev/docker-compose.environment.yaml` with:
```
version: '3.6'

services:
  web:
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
```
(convention is uppercase, but some tools like `wget` need lowercase to work)
Then `ddev restart`

**Comment by rfay** [comment]
That's pretty weird about wget, but I see https://stackoverflow.com/questions/11211705/how-to-set-proxy-for-wget :)

**Comment by rfay** [comment]
Note that @wtfred 's main stated reason for this is composer, and it only makes sense that composer would need some help here.

**Comment by wtfred** [comment]
@rfay I'm continuing my tests, and proxy integration also need a file on web container `/etc/apt/apt.conf.d/20proxyconf` (name doesn't really matter) with the content `Acquire::http::Proxy "http://IP:PORT";` for apt to work...

**Comment by wtfred** [comment]
Well, after reading a bit of docker documentation, there is an existing way to define a proxy properly... See https://docs.docker.com/network/proxy/
By creating on the host a file `~/.docker/config.json`, docker automatically set the needed ENV vars, lowercase and uppercase.
With this, `composer` works, `wget` works. `apt` still doesn't works form inside the container, because it still need the file i mention above, but it works from a `Dockerfile`, i think that's enough :)

**Comment by rfay** [comment]
That's awesome work!  I hope you'll write up the whole solution here or on Stack Overflow when you get it sorted.

Note that if you do the work in the .ddev/web-build/Dockerfile, it's possible you won't need the /etc/apt/apt.conf.d/20proxyconf because the build is happening in docker's context, rather than in the docker container context.

**Comment by wtfred** [comment]
Yes for `apt`, that's what i was trying to say by "it doesn't works inside the container, but it works in a Dockerfile", i'm using `RUN apt-get update` inside a `.ddev/web-build/Dockerfile` and it's working :)

**Comment by rfay** [comment]
@wtfred could you please review https://github.com/drud/ddev-contrib/pull/3 ?

Thanks!

**Comment by rfay** [comment]
Fixed and documented in https://github.com/drud/ddev-contrib/pull/3
