### ISSUE TITLE
"ddev config" doesn't look for an existing .ddev/config.yaml

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1158]
**Describe the bug**

`ddev config` does not do the check to see if it's already in a project. Instead it will always try to create a .ddev/config.yaml in the current directory.  (The other commands all call utils.CheckForConf() at some point). 

`ddev config` should call CheckForConf() and if *not* found, create the config in the current directory.

**To Reproduce**

* Create a project
* cd into a subdirectory of the project
* `ddev config`
* Note that the new .ddev is created in the subdirectory.

**Expected behavior**

`ddev config` should find the master directory to config if it's already configured. 

**Additional context**

I think this dates from the time that `ddev config` was assumed never to be run more than once.

**Comment by mglaman** [comment]
So to fix this: `ddev config` needs to loo upwards for the existing project just like start/stop/exec, et do?

**Comment by rfay** [comment]
Yes, exactly.

**Comment by andrewfrench** [comment]
The bulk of this is fixed by replacing `os.Getwd()` with `ddevapp.CheckForConf()` to search through parent directories for an existing config:

https://github.com/drud/ddev/blob/b139f191f5171f75c7066fd2bf0fa4814c5dda65/cmd/ddev/cmd/config.go#L198

But that one-line fix seems to break the assumptions of the interactive config (specifically docroot and apptype detection). I think that's easily fixable by working relative to the detected app root. It'll also take some wording changes in the docroot prompt, as "current directory" will end up being misleading.

**Comment by rfay** [comment]
👍
