### ISSUE TITLE
Security: ddev can be used to sudo an arbitrary command

### ISSUE THREAD

**Issue by rfay** [drud/ddev#117]
## What happened (or feature request):

ddev does a [sudo on itself](https://github.com/drud/ddev/blob/master/pkg/plugins/platform/local.go#L404) in order to update /etc/hosts, which requires root privs. 

However, the command there does not specify the path to the "ddev" command, so it would be trivial for an attacker to gain root privileges and execute arbitrary commands with root privs just by placing a script named "ddev" anywhere in the path before the real one. 

## What you expected to happen:

No access to root privs just from running ddev.

## How to reproduce it (as minimally and precisely as possible):

It's easy to reproduce but not recommended.

## Anything else do we need to know:

There are a few ways to fix this:

1. Explicitly call sudo on a known rooted full-path version of ddev (like the one that's running)
2. Use another technique to manage hostnames.
3. ???

## Related source links or issues (like source JIRA issue):

**Comment by rfay** [comment]
In order to keep the scope of this reasonable, here's what I propose at this time:

1. When sudo is needed, prompt the user what is about to happen, giving them the command that will be executed.
2. When they grant permission, execute the command
3. Use the full path of the running ddev in the sudo command.

In the future it would be fantastic to do some kind of name resolution instead. And it might be totally reasonable to do what other packages do, using DNS with a wildcard (and tell people that for offline work they have to add it to /etc/hosts, and give them an easy way to do it.)

**Comment by rickmanelius** [comment]
So it looks like there are two things at play here:

1. Avoiding sudo. Can we use we adopt a wildcard DNS entry so that this is a one and done thing.
2. Safe sudo. Can we make it very clear what is about to happen in case of a man in the middle.

I like (1) and we should get a ticket filed for that. It's a common request among the devs that I've worked. In terms of (2), I see this as an excellent educational opportunity (after all, we're trying to "make the right choice the easiest"). So I think that would be a valid approach.

Given that we need to get this closed out, I would vote to adopt Randy's last proposal for the purposes of this ticket and get the separate one filed.

**Comment by rfay** [comment]
Opened https://github.com/drud/ddev/issues/175 for @rickmanelius request 1
