### ISSUE TITLE
Add option to import-db --no-wipe just to import some tables / rows

### ISSUE THREAD

**Issue by velletti** [drud/ddev#1265]
actually import-db truncates all tables before the import runs. 
But:
As a developer for TYPO3 extensions i often import the db from the LIVE Website to be able to program near to the original data of the plattform. 

Afterwards some of the data must be changed manualy: 
f.e: the Default domain  shloud be set to the ".dev.local" Domain,
i need  aspecific set of users to be able to run automatic usability tests
or
i have a running local env and just need the latest Entries from the "Dates&events" or "news" entries to fix a problem with this entries. 

actually then i do:
ddev import-db --src FULL.sql 

winpty ddev ssh  
mysql -udb -pdb db < /vara/www/html/someSql.sql 
exit

nice would be instead:
ddev import-db --src FULL.sql  
ddev import-db --src someSql.sql **--no-wipe**

**Comment by rfay** [comment]
Just so you know, it's easy to use  the mysql client either on the host or in either the web or db containers. For example `ddev exec mysql db <someSQL.sql` (where someSQL.sql is in this case in the project root). Or `ddev ssh` and `mysql db <someSQL.sql`. And the mysql port is exposed on the host, (see `ddev describe`), but it's annoying because the port changes on each start.

**Comment by rfay** [comment]
There are so many good established ways to accomplish this that I'm going to say "won't fix". Thanks for bringing this forward, and hope that the existing techniques are meeting your needs.
