### ISSUE TITLE
Make name, dba, dbimage and webimage optional in config.yaml

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#139]
## What happened (or feature request):
We have the `dbimage` and `webimage` keys committed to all of our test/demo repositories. This means to run tests using a new container you need to update those repositories and then create a release with the new images in them. It's a very ham-handed way of running tests with custom container versions.

## What you expected to happen:
- Remove the `dbimage` and `webimage` keys from config.yaml in those test/demo repositories
- Modify the `Read()` method of the `config` struct in the `ddevapp` package to properly set the defaults from the `versions` package after the config is loaded if they are blank.

**Comment by rickmanelius** [comment]
I would agree with Randy. For debugging purposes, it would seem that name would be good to swap out. Same with the removal of phpmyadmin. If there are no strong dissents, I think inventorying out the repos explicitly would make this reviewable (and therefore actionable). Added to v0.3 milestone because this will affect tests in the very near term.

**Comment by rfay** [comment]
This is complete
