### ISSUE TITLE
HTTP ERROR 500: This page isn’t working

### ISSUE THREAD

**Issue by alesrebec** [drud/ddev#1401]
**HTTP Error 500**
After "ddev start" I get HTTP Error 500 This page isn’t working 127.0.0.1 is currently unable to handle this request. And it shows on all url aliases suggested in CLI after ddev start.

![screenshot from 2019-01-25 10-22-39](https://user-images.githubusercontent.com/426177/51736893-8f67d380-208b-11e9-8205-a1fec1e6d4ad.png)

**To Reproduce**
1. ddev config
2. ddev start
3. Site works but I get the "semaphore" error because database is not yet imported
4. ddev import-db
5. After successful db import I get HTTP 500
6. If I visit install.php site it works, and I'm also able to visit other subpages like /user/login, just the front page is not working.

![screenshot from 2019-01-25 10-23-14](https://user-images.githubusercontent.com/426177/51737039-e077c780-208b-11e9-8408-8705f9c19629.png)

**Version and configuration:**
 - Ubuntu 18.04.1 LTD
config.yml
```
APIVersion: v1.5.2
name: the-project
type: drupal7
docroot: web
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"  // Tried with other port numbers too, no other docker containers running!
router_https_port: "443" 
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
provider: default
```

**Comment by alesrebec** [comment]
Interestingly it appeared to be something with the database update.

So I logged in successfully on /user/login, noticed there are some DB updates I need to run.
After those were applied the front page started working!

If anyone has the same error, I would suggest you check your logs and run all updates.
Closing it for now.

**Comment by linehammer** [comment]
The error is too generic and does not tell you exact problem. What you need is to find out what is the real issue. If your site is serving a Internal Server Error, this can be caused by a number of things, such as:

- Errors in .htaccess files
- Server permission
- Server timeout
- Script timeout
- Or some other Web Server Issues

Normally, a permissions issue on the file (or files) would be one cause of the [500 Internal Server Error](http://net-informations.com/q/mis/500.html). The simple solution is to run chmod 644 on the problem file(s) or chmod 755 on the directories.

`$ sudo chmod -R 777 /"your files location"`

The best way to debug the error depends upon the server and what’s actually running at the time. Consider some debugging tips to help diagnose and fix common causes of this problem.
