### ISSUE TITLE
Wrong URL to install_ddev.sh

### ISSUE THREAD

**Issue by Krisseck** [drud/ddev#1436]
**Describe the bug**
The docs have wrong URL for install_ddev.sh in it.

**To Reproduce**
1. Go to https://ddev.readthedocs.io/en/stable/
2. Check section "Installation/Upgrade Script - Linux and macOS"
3. The URL in the inline script is wrong (`https://raw.githubusercontent.com/drud/ddev/master/install_ddev.sh`) 

**Expected behavior**
The correct URL is `https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh`, note the `scripts` in the URL

**Comment by rfay** [comment]
Shoot, I thought I was making that change in a non-intrusive way, but I failed. I made the docs change so it would only show up in "latest", but of course when the merge happened, "master" was changed in the code.

This will be fixed by release next week. If you visit the "latest" doc, you'll see it has the right thing, https://ddev.readthedocs.io/en/latest/#installationupgrade-script-linux-and-macos

Sorry for this inconvenience. I'll think about whether there's an easy way to fix it before next week's release.

**Comment by rfay** [comment]
I fixed the docs so https://ddev.readthedocs.io/en/stable/#installationupgrade-script-linux-and-macos now has the correct URL. The downside is that people for a couple of days will find things in the docs that are *not* yet in the latest v1.5.2 release. But it seems important to fix this one.

Thanks for letting us know.
