### ISSUE TITLE
WARNING: [pool www] server reached pm.max_children setting (4), consider raising it

### ISSUE THREAD

**Issue by davdenic** [drud/ddev#1447]
**Describe the bug**
timeout when testing with several browsers

**To Reproduce**
testing with several browsers
in terminal run ddev logs:
`WARNING: [pool www] server reached pm.max_children setting (4), consider raising it`

**Version and configuration information (please complete the following information):**
- Mac
- ddev 1.5.2
- docker        	18.09.1
- TYPO3 8.7
- PHP 7.2

**Additional context**
please provide instructions how to change php-fpm parameters

**Comment by rfay** [comment]
First off, I think it's totally reasonable to raise the pm.max_children; a PR for that would be welcome, otherwise we'll get to it.

Second, you probably want a short-term approach. You can edit `/etc/php/$DDEV_PHP_VERSION/fpm/pool.d/www.conf` and `killall -1 php-fpm`

I think a good approach would be to add a post-start exec hook that did 
`bash -c "perl -pi -e 's/pm.max_children = 4/pm.max_children = 16/' /etc/php/*/fpm/pool.d/www.conf && killall -1 php-fpm"`

Could you try that out and post the resulting hook here?
