### ISSUE TITLE
WordPress: Errors with the wp-cli - Constant ABSPATH already defined

### ISSUE THREAD

**Issue by fschmittlein** [drud/ddev#1462]
**Describe the bug**
After some wp commands i see:
PHP Notice:  Constant ABSPATH already defined in phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1153) : eval()'d code on line 17
Notice: Constant ABSPATH already defined in phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1153) : eval()'d code on line 17

**To Reproduce**
1. ddev ssh
2. wp language plugin install --all de_DE

**Comment by fschmittlein** [comment]
My solution: change the wp-config.php

/** Absolute path to the WordPress directory. */
define('ABSPATH', dirname(__FILE__) . '/');

to

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Thanks for this!

**Comment by rfay** [comment]
This is a result of the (horrible) WordPress default of using constants for important things; they then can't be fixed. 

So https://github.com/WordPress/WordPress/blob/d4cec569fe3ff0a31afc498f5808b47fcd60405b/wp-config-sample.php#L85-L87 shows this setup in wp-config-sample.php. Once it's set up like that, there's nothing that another application can do to change it, and that's why you see the error you're finding.

Thanks for the report, carry on!
