### ISSUE TITLE
Improve CLI Validation

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#15]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature

**Information**:
We require improved CLI Validation. drud/bootstrap#261 took this on, but was merged after the work to split `ddev` out began. We should port those changes (along with tests, naturally).

**Comment by tannerjfco** [comment]
Since the time this issue was originally created, I believe we've managed to rework all of ddev's commands, improving help text and validation as we go. Is there anything further actionable here? We could take another pass through the commands and try to break them if we wanted, but I'm not sure how much that would actually turn up.

**Comment by rickmanelius** [comment]
I vote close and file tickets as we rework functions and discover gaps.

**Comment by rickmanelius** [comment]
We will surface at planning meeting and close then.

**Comment by rickmanelius** [comment]
While this didn't come up, I'm going to assume any issues with validation will get caught and filed separately, but I agree with @tannerjfco that this appears to have been addressed along the way.
