### ISSUE TITLE
Provide "ddev poweroff" that shuts down all running containers

### ISSUE THREAD

**Issue by jmarkel** [drud/ddev#1588]
After shutting down or removing the last running ddev instance, there is still one container left running - the ssh-agent container. This can play havoc with other docker-based systems if one forgets to do this (which is very easy to forget):
```
Jeffreys-MacBook-Pro:jnjhwsch jeff$ ddev stop --all
Network ddev_default is external, skipping
Project jnjhwsch has been stopped.
Jeffreys-MacBook-Pro:jnjhwsch jeff$ docker ps
CONTAINER ID        IMAGE                        COMMAND                 CREATED             STATUS                  PORTS               NAMES
544bb46ac6b2        drud/ddev-ssh-agent:v1.7.0   "/entry.sh ssh-agent"   45 hours ago        Up 45 hours (healthy)                       ddev-ssh-agent
Jeffreys-MacBook-Pro:jnjhwsch jeff$
Jeffreys-MacBook-Pro:jnjhwsch jeff$ docker kill 544bb46ac6b2
544bb46ac6b2
```
I am proposing that ddev either provide a new command to completely shut itself down (like Lando's ``lando poweroff`` or, preferably, simply to kill that final container when the last running ddev instance is shut down or removed.

**Comment by rfay** [comment]
`ddev remove --all --stop-ssh-agent` (which becomes `ddev stop --all --stop-ssh-agent` in v1.8.0

`ddev stop` hasn't been recommended usage for some time (which is why it's changing behavior in v1.8.0, people kept using it, leaving containers around)

But I still agree that something like `poweroff` is a good idea.

**Comment by jmarkel** [comment]
Thanks, @rfay.

OK, there's already a way to do it via command line - but it's too arcane to remember easily ;)

So yeah, ``poweroff`` or, better yet, recognize the need by context and do it without requiring any user intervention at all.

**Comment by rfay** [comment]
Well, the only thing that's left running currently (when no projects are running) is the ssh-agent container, and that's really intended to run until shutdown (because it keeps the ssh credentials for you). 

But something like poweroff is in our future I think. Related: https://github.com/drud/ddev/issues/1562 requesting cleanup and https://github.com/drud/ddev/issues/1465 about cleaning up unused volumes. People have also requested `ddev removedata` or something of the type to replace `ddev stop --remove-data`
