### ISSUE TITLE
Cannot execute mysql command in db container with 1.8.0

### ISSUE THREAD

**Issue by Ben305** [drud/ddev#1597]
**Describe the bug**
With 1.7.1 I was able to do the following:
```bash
ddev exec --service db mysql db -e "Update be_users SET password=md5('123456')"
```
With 1.8.0, this is not possible any longer.

```bash
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `mysql db -e Update be_users SET password=md5('123456')'
```

**Comment by rfay** [comment]
Shoot, I apologize for the change of behavior, mostly due to nested quoting behavior. This will work now:

`ddev exec "mysql -e 'Update be_users SET password=md5(\"123456\");'"`

I'm sure there are a few other ways to get the quoting right, but this was the first I hit.

BTW, you don't actually have to specify the 'db' container; you can execute anything you want in the web container, making the `--service db` unnecessary.

**Comment by rfay** [comment]
You might also want to try a post-start hook in your .ddev/config.yaml:
```
hooks:
  post-start:
    - exec: "mysql -e 'UPDATE be_users SET password=md5(\"123456\");'"
```

**Comment by Ben305** [comment]
Thanks, working very well!
