### ISSUE TITLE
oh-my-zsh as bash

### ISSUE THREAD

**Issue by rogoit** [drud/ddev#1642]
**Is your feature request related to a problem? Please describe.**
Add oh-my-zsh and the agnoster theme as bash terminal

**Describe the solution you'd like**
Just do it

**Additional context**
I can help you when you tell me the files i have to update

**Comment by rfay** [comment]
Could you please explain what you'd like with a bit more detail? Are you talking about installing zsh or oh-my-zsh in the container? 

As I'm sure you know, you can use whatever shell and configuration you want on your host, and ddev has nothing to do with it.

**Comment by rogoit** [comment]
I love that you are always on

I want the oh-my/ysh shell when i connect via ssh to the web container. This is a really great tool. Belive in...you will never live without :)

So give me the skills to add it and i will do a pull request. Rest is open source voting hehe :)

**Comment by rfay** [comment]
I do think that the adoption of zsh as the default shell by macOS Catalina will swing zsh usage, but bash (or sh) is still the default shell in most server environments, zsh never even appears I don't think. While I understand your enthusiasm, and I'm sure I'll share it someday, it's not the go-to environment that people expect to find in a server or a container.

**Comment by rogoit** [comment]
In need to run commands like bin/console for symfony and must have a db connection. Also there are super shortcuts like l, and .. to move fast. Most developers i know use it.

**Comment by rfay** [comment]
Again, if you could give an example of what you're trying to do and why you find it inconvenient, that would be great. I don't think that using zsh has anything to do with having a db connection does it? I understand shortcuts.

**Comment by rogoit** [comment]
Please install oh-my zsh and than add this .zshrc file to root home directory of the web user
[.zshrc file](https://gist.github.com/nevercodealone/2a12d692fdb1a33529e8834de5cf934b)

There is a manuel on the last lines to add some very good plugin like fish autocomplition

Also we need a .z file in der home directory with 777 rights.

Belive in and just check it. Thank you my friend!!

**Comment by rfay** [comment]
We won't be doing this at this time, but if others express interest we'll be happy to reopen! I know zsh users love their zsh!

**Comment by elgandoz** [comment]
Late to the party, but for future reference:
you can change your Dockerfile to use this repo: https://github.com/deluan/zsh-in-docker

**Comment by rfay** [comment]
@elgandoz I didn't understand what you were suggesting.  Since this issue was open many things have happened, with support for zsh completions, etc. https://ddev.readthedocs.io/en/stable/users/shell-completion/.  Also see https://ddevhq.org/ddev-local/oh-my-zsh-using-custom-commands-and-other-goodies-to-add-to-ddev/ for how to set up oh-my-zsh, easily customizable to other things.

**Comment by elgandoz** [comment]
Thanks @rfay. I found the first link, but those completion are about the host environment. The second links instead seems to sort what I'm after, which is having zsh when within the container.

I'm using "remote development" with VSCode in order to take advantage of PHP suggestions and intelligence, and de facto is like SSH in the container: I would like to have zsh there, within the integrated terminal.
