### ISSUE TITLE
Duplicate mount point: /var/lib/mysql

### ISSUE THREAD

**Issue by rogoit** [drud/ddev#1649]
**Describe the bug**
After a restart of my fedora linux system i run in this error.

**Expected behavior**
I want to run different ddev projects and use different project names. Can this be a issue?

**Version and configuration information (please complete the following information):**
 - Fedora 30
 - 19.03.0-rc2
 - v1.7.0
 APIVersion: v1.7.1
name: ncacommunity
type: php
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
nfs_mount_enabled: false
provider: default

**Comment by rfay** [comment]
I'm pretty sure this is fixed in 1.8, but regardless if you do ddev rm and ddev start I don't think you'll see it.

**Comment by rfay** [comment]
No response from OP, so I'm going to close. Hope this is working for you now. We do hear this periodically, and it seems like more on linux than elsewhere. I haven't figured out how to cause it except starting a project with a duplicate name, or starting a project with stopped containers ("paused" in v1.8) and new config.  Closing but happy to continue the conversation here.

**Comment by rogoit** [comment]
So i still got this issue when i start different projects.

**Comment by rfay** [comment]
If you `ddev stop -a` it still does it? Is it possible you're sharing the same project name (and thus database volume name) between two projects?

**Comment by rogoit** [comment]
ddev rm brings the answer but i can not say if i still got the db up to date because i am on a inital base project

**Comment by rfay** [comment]
Sorry, I'm not understanding your statement. If you use `ddev stop -a` and then `ddev start` do you get this problem?  (Assuming ddev v1.8.0)

**Comment by rogoit** [comment]
I make upgrade...and be good things...thx for support my friend...

**Comment by rfay** [comment]
Yay, happy to continue the conversation.

**Comment by Fischer-Simon** [comment]
Using ddev 1.10.2 I still get this error when starting paused instances.
So `ddev pause; ddev start` does not work. The same think happens when I restart the computer. To make the containers work I have to use `ddev stop; ddev start` to remove the container and let ddev recreate it.

I just tried to create a new empty ddev project, the same happens:
```bash
[sfischer-wr@fischer /tmp/a]$ ddev config
Creating a new ddev project config in the current directory (/tmp/a) 
Once completed, your configuration will be written to /tmp/a/.ddev/config.yaml
 
Project name (a): 

The docroot is the directory from which your site is served.
This is a relative path from your project root at /tmp/a 
You may leave this value blank if your site files are in the project root 
Docroot Location (current directory): 
Found a php codebase at /tmp/a. 
Project Type [backdrop, php, drupal6, drupal7, drupal8, wordpress, typo3] (php): 
Project type has no settings paths configured, so not creating settings file. 
Configuration complete. You may now run 'ddev start'. 
[sfischer-wr@fischer /tmp/a]$ ddev start
Starting a... 
Running   Command=ip address show dev docker0
Creating volume "a-mariadb" with default driver 
Building db 
Building web 
Creating ddev-a-db ... done
Creating ddev-a-dba ... done
Creating ddev-a-web ... done
 
ddev-router is up-to-date 
Successfully started a 
Project can be reached at https://a.ddev.site https://127.0.0.1:32794 
[sfischer-wr@fischer /tmp/a]$ ddev pause
Stopping ddev-a-web ... done
Stopping ddev-a-dba ... done
Stopping ddev-a-db  ... done
 
Project a has been paused. 
[sfischer-wr@fischer /tmp/a]$ ddev start
Starting a... 
Running   Command=ip address show dev docker0
Building db 
Building web 
Recreating ddev-a-db ... error
 
ERROR: for ddev-a-db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql 
 
ERROR: for db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql 
Encountered errors while bringing up the project. 
Failed to start a: Failed to run docker-compose [-f /tmp/a/.ddev/docker-compose.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> d6fa0cdaf8d6
Step 3/6 : ARG username
 ---> Using cache
 ---> 9748e9a0e89e
Step 4/6 : ARG uid
 ---> Using cache
 ---> aa0c686e2726
Step 5/6 : ARG gid
 ---> Using cache
 ---> 9da26f89bfd0
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> eedce18c3da1

Successfully built eedce18c3da1
Successfully tagged drud/ddev-dbserver:v1.10.0-10.2-built
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 6c0df14a692a
Step 3/6 : ARG username
 ---> Using cache
 ---> 36b58d89e385
Step 4/6 : ARG uid
 ---> Using cache
 ---> 36f6b28a79c9
Step 5/6 : ARG gid
 ---> Using cache
 ---> 9be7523d021a
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> a1cb4d8fbbf4

Successfully built a1cb4d8fbbf4
Successfully tagged drud/ddev-webserver:v1.10.2-built
', stderr='Building db
Building web
Recreating ddev-a-db ... error

ERROR: for ddev-a-db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql

ERROR: for db  Cannot create container for service db: Duplicate mount point: /var/lib/mysql
Encountered errors while bringing up the project.' 
[sfischer-wr@fischer /tmp/a]$ ddev stop
Removing container: ddev-a-web 
Removing container: ddev-a-dba 
Removing container: 17157307eae7_ddev-a-db 
Project a has been stopped. 
[sfischer-wr@fischer /tmp/a]$ ddev start
Starting a... 
Running   Command=ip address show dev docker0
Building db 
Building web 
Creating ddev-a-db ... done
Creating ddev-a-dba ... done
Creating ddev-a-web ... done
 
ddev-router is up-to-date 
Successfully started a 
Project can be reached at https://a.ddev.site https://127.0.0.1:32797 
[sfischer-wr@fischer /tmp/a]$ 
```

**Comment by rfay** [comment]
@Fischer-Simon do you have any customization, like docker-compose.*.yaml in the .ddev folder? Any possibility it's also trying to mount /var/lib/mysql?  

I do recommend using `ddev stop` rather than pause for reasons exactly like this. It basically costs nothing, all your data is saved, and you get clean docker startup.  Really, that's one of the fundamental reasons that we changed "stop" from being docker's "stop" and to being a complete container destruction is that docker wasn't predictable. 

I did test `ddev pause` followed by `ddev start` with no troubles just now on Fedora 30. I think you should make sure that `docker ps -a` shows *only* the containers you expect after you `ddev pause` - there should be only 1 web, 1 db. Both should be stopped. When you `ddev poweroff` there should be no containers at all in `docker ps -a`.

It may be that you just need a `ddev poweroff` and possibly a `docker rm -f $(docker ps -aq)` to kill off some orphaned forgotten db container?

**Comment by Fischer-Simon** [comment]
Alright, I use `ddev stop` instead of `ddev pause` and `ddev poweroff` when I restart the host system.

After a `ddev pause` the `docker ps -a` indeed only shows the expected containers. But after I start the project again with `ddev start` there seems to be a new database container with a random string as a name prefix:
```
[sfischer-wr@fischer /tmp/a]$ docker ps -a
CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS                        PORTS                      NAMES
ebf0093711ba        drud/ddev-webserver:v1.10.2-built       "/start.sh"              47 seconds ago       Exited (0) 18 seconds ago                                ddev-a-web
9eae4e6125b3        drud/phpmyadmin:v1.10.0                 "/run.sh phpmyadmin"     47 seconds ago       Exited (0) 18 seconds ago                                ddev-a-dba
b227672af98a        drud/ddev-dbserver:v1.10.0-10.2-built   "/docker-entrypoint.…"   47 seconds ago       Exited (0) 16 seconds ago                                b227672af98a_ddev-a-db
```
A `ddev stop` removes all those containers. There is no `docker-compose.*.yaml`, I created a completele empty and new ddev project for this test. Does ddev load system wide config files from the home directory or somewhere else? Maybe I screwed those up.

**Comment by rfay** [comment]
I imagine you're onto something with that weird-named db container. The container name should be ddev-a-db, not b227672af98a_ddev-a-db

The config is in the project's .ddev directory, most important are the config.yaml and any docker-compose.*.yaml overrides. 

Here's what I see on a trivial project (on Fedora 29) after a stop,start,pause:

```
$ docker ps -a
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                     PORTS               NAMES
b3991516b95e        drud/ddev-ssh-agent:v1.10.2-built       "/entry.sh ssh-agent"    25 seconds ago      Up 24 seconds (healthy)                        ddev-ssh-agent
40635d5639a4        drud/phpmyadmin:v1.10.0                 "/run.sh phpmyadmin"     2 minutes ago       Exited (0) 6 seconds ago                       ddev-junk-dba
b5d47c8ddf24        drud/ddev-webserver:v1.10.2-built       "/start.sh"              2 minutes ago       Exited (0) 6 seconds ago                       ddev-junk-web
d2703a5b4cf2        drud/ddev-dbserver:v1.10.0-10.2-built   "/docker-entrypoint.…"   2 minutes ago       Exited (0) 4 seconds ago                       ddev-junk-db
```

Docker version 19.03.1, build 74b1e89
docker-compose version 1.24.1, build unknown
ddev version v1.10.2

(You didn't mention your docker-compose version... does it match? Mine is installed with homebrew)

**Comment by Fischer-Simon** [comment]
I am indeed using another version of docker-compose (docker-compose version 1.22.0, build f46880f).
This seems to be a bug in docker-compose since I found two related issues there: docker/compose#5885 and docker/compose#4751
Unfortunately 1.22 is the newest version in the fedora repositories. But since I can use `ddev stop` without problems I consider my problem as solved.
Thank you for your help :).

**Comment by rfay** [comment]
On most Linuxes you really can't use the system repo for docker-compose (or docker). See the instructions at https://docs.docker.com/install/linux/docker-ce/fedora/

But glad it's working for you! And stop really is better than pause I think in all cases.
