### ISSUE TITLE
Upgrade/create config automatically (or with flag) on start

### ISSUE THREAD

**Issue by unn** [drud/ddev#1713]
**Is your feature request related to a problem? Please describe.**
So I've upgraded my ddev, but I just want to `ddev start` and have the config step happen automatically because I want to just accept the config as it is currently.

**Describe the solution you'd like**
`ddev start --force-config` or similar that re-writes the config file without input and runs start
`ddev config --accept-all` or similar that doesn't run me through the q&a input

**Comment by rfay** [comment]
I kind of wonder if that whole dance is even useful. It's been a long time since we introduced anything that was incompatible.

There is a problem with these strategies: A lot of teams now commit the config.yaml, so it's up to one team member to upgrade and push, other team members have to override with config.*.yaml if necessary. So we have to respect that workflow.

**Comment by unn** [comment]
My point is largely that, on my simple projects, I've never had to alter the config ever. It seems strange that I can't accept the config update automatically as part of my start workflow.

**Comment by rfay** [comment]
Yeah, totally understand, and works for me that way too. So your suggestion of a switch is the ticket. (One other side-effect is that comments get lost on `ddev config`)

**Comment by rfay** [comment]
Related (and better): Don't change APIVersion with ddev version. Or just drop APIVersion. #2116

**Comment by rfay** [comment]
In fact, I'm going to close this in favor of that #2116.
