### ISSUE TITLE
Support for PHP 5.3?

### ISSUE THREAD

**Issue by a8w4** [drud/ddev#1714]
I know PHP 5.3 is not supported and probably never will, but what would be the easiest way to achieve this?

Sometimes I need to run ancient systems in order to analyse an migrate them - e. g. an ancient version of typo3 that will not run on systems with PHP > 5.3.

**Comment by rfay** [comment]
I've definitely wanted to figure out how to do that, but the packages we use (deb.sury.org) only go to 5.6, and it's not trivial to build older versions. I pursued that quite heavily when sury was going to discontinue 5.6, https://github.com/oerdnj/deb.sury.org/issues/1092

But I think for now the easiest thing to do is to run a virtualbox instance with Ubuntu 12.04 and the basic standard packages that come with it. That's what I've done when forced to run an old site. Also... turn that old site into html!

**Comment by rfay** [comment]
If it's super important and you can figure out how to build the sury images from that comment, we'll figure out  a way to get old stuff available for ddev.

**Comment by WarpedOne** [comment]
As a developer, it is often important to go back to old releases to check and see how an older version acted, or to upgrade or migrate. Many sites are running on dangerously outdated PHP and need to be upgraded. Are there possibly archived versions of containers? Possibly only as difficult as locating these copies. Running on a dev box isn't as big a security issue as running on a live site. I would hope developer tools would be able to assist in these cases. (Just my 2cents worth)

**Comment by rfay** [comment]
I would absolutely love to provide old PHP versions, but it's quite a lot of work, since deb.sury.org doesn't provide these any more. If I could figure out from https://github.com/drud/ddev/issues/1714#issuecomment-512893053 how to build them, I'd even consider doing it, but that wasn't really very descriptive. We almost lost access to 5.6, and will likely in the future (although we have a workaround for that)

**Comment by rfay** [comment]
I did some poking around for non-Sury.org strategies for old php, and found

* [a package-based approach](https://github.com/zener05/debian-stretch-php-5-3) (which has real potential). The mentioned PPA repository also has 5.2 and 5.4/5.5 and even 4.x. 
* [a build-from-source approach](https://www.howtoforge.com/community/threads/the-perfect-server-debian-9-stretch-add-php-5-3.77549/#post-366596); I experimented with this but didn't finish the work.

**Comment by a8w4** [comment]
Thanks for exploring this further! I think I can point you to an alternative right in the middle of the two mentioned strategies: http://phpbrew.github.io/phpbrew/
No ready build packages but quite a lot of automation. I believe you especially will like the ` phpbrew switch` command: This way PHPBrew would allow to build only one image for all the old an upcoming unsupported versions of PHP!

**Comment by rfay** [comment]
phpbrew looks like it might just be pretty nice. It would probably mean a horrible image build session while building docker image. But way lots of flexibility. And if we used it, it might be possible for people to just go wherever they wanted to go with the versioning. Occasionally people will ask for a minor version.

The downside is that everything is currently built around the very nice sury.org multiple-supported-php-packages approach, and we'd lose that.

**Comment by a8w4** [comment]
You're right: it's a lot of building beforehand - but how about a two-way approach: sury.org for the supported versions and phpbrew for the unsupported versions? The unsupported versions image could also be pre-built, can't it? All those unsupported versions per definition don't move much anymore.

**Comment by rfay** [comment]
I immediately ran into https://github.com/phpbrew/phpbrew/issues/861, phpbrew completely failed; I actually ran into this same issue trying to build manually. I'm not sure phpbrew is as robust as it wants to be. Of course, it's always a mess trying to build old recipes on newer systems, and that's what's actually going on here. 

I do agree that it might be possible to use sury for current versions and phpbrew for older. Or just provide a recipe for people to do their own. But it would have to work better :) If you use Debian or Ubuntu... are you able to use phpbrew to build 5.3 or 5.4?

**Comment by rfay** [comment]
Yeah, for all its promise, phpbrew is an animal whose complexity is just the complexity of building old PHP on new systems. The biggest problem is openssl, whose current versions are incompatible with the ones that php5.x need. https://github.com/phpbrew/phpbrew/issues/939 gives a strategy for working around this with old libraries, but it's not actually compatible with using the machine for anything else.

**Comment by WarpedOne** [comment]
What I was hinting at was working with one of the other projects to find old images that might work. Might need older versions from several projects. Or working with them for suggestions. Maybe versions could be created just for DDEV use. I know Docker had a security issue a while back where some images were available that had malware. I believe they were 3rd party and recommended being careful whose images you used, but not sure if any others were compromised. Docker Toolbox uses https://github.com/boot2docker/boot2docker This contains the Linux kernel and base Linux. Possibly use older versions? It would be like using the older containers that remain after a DDEV upgrade, although Docker upgrades the containers to the latest when you upgrade Docker. Just throwing out some ideas, hoping to trigger other ideas.

**Comment by rfay** [comment]
I tried the libraries from https://github.com/zener05/debian-stretch-php-5-3 with lots of hopes. But too many of the modules wouldn't install, including gd but most importantly mysql, which depends on a library not included in stretch. 

Experimented with adding this to the Dockerfile, which hopes of transplanting it later to a `.ddev/web-build/Dockerfile` recipe:

```
RUN apt-get update && apt-get install -y logrotate  #libicu55 libmysqlclient18 libreadline6
RUN wget -nv https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/php53/+files/php53-cli_5.3.29-1sergeyd14.4~xenial1_amd64.deb https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/php53/+files/php53-common_5.3.29-1sergeyd14.4~xenial1_all.deb https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/php53/+files/libapache2-mod-php53_5.3.29-1sergeyd14.4~xenial1_amd64.deb https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/php53/+files/php53-fpm_5.3.29-1sergeyd14.4~xenial1_amd64.deb && \
( wget -nv $(for item in bcmath bz2 curl gd intl json mysql pgsql mbstring sqlite3 readline xdebug xml xmlrpc zip; do printf "https://launchpad.net/~sergey-dryabzhinsky/+archive/ubuntu/php53/+files/php53-mod-${item}_5.3.29-1sergeyd14.4~xenial1_amd64.deb "; done)  || true ) && dpkg -i php*cli*.deb php*common*.deb php*fpm*.deb && dpkg -i php53-mod*.deb
```

**Comment by rfay** [comment]
For @a8w4  though: The way I've dealt with this in the past seems to still be the easiest way. 
* Find the version of Ubuntu that matches the PHP version you need.
* Find a web recipe showing how to install it on that version of Ubuntu
* Spin it up in Virtualbox and set it up
* Spelunk in your website.

It's way easier than what I was just trying to do in this issue :)

**Comment by kaystrobach** [comment]
https://github.com/zener05/debian-stretch-php-5-3/blob/master/README.md

**Comment by rfay** [comment]
Yeah, that's what I tried above (package-based approach), https://github.com/drud/ddev/issues/1714#issuecomment-515966830

**Comment by kaystrobach** [comment]
Oh - sry missed that comment

**Comment by rfay** [comment]
While I would absolutely love to do this, it doesn't seem like it's in the cards. I'll be happy to help anybody set up an old Ubuntu in Virtualbox to get the job done.

**Comment by klonos** [comment]
Sad 😞 ...but understandable.

Despite its EoL, php5 is still around, and at a big % unfortunately.

...in Backdrop, we support back to 5.3, so our CI is configured to run tests for php53 and php70. Each time that php7 passes, but php5 fails, I am at a dead end, as it requires way much more work to get a php53 environment span up to test things. I eventually get frustrated and give up 😓

I have started an issue to discuss dropping support for php 5.3 entirely here: https://github.com/backdrop/backdrop-issues/issues/3992, but the fact that there are many outdated but still LTS linux distros that are used by hosting companies, makes it hard to decide. It is a pickle 🤷‍♂

**Comment by rfay** [comment]
I would dearly love to support earlier versions if it could be an appropriate level of attention, but I haven't figured out a way to do it, as you already know.

**Comment by kaystrobach** [comment]
maybe it makes sense to contact suri - then debian maintainer for php.

**Comment by kaystrobach** [comment]
```
php5.6/                                            09-Aug-2019 18:37                   -
php7.0/                                            09-Aug-2019 10:57                   -
php7.1/                                            09-Aug-2019 15:47                   -
php7.2/                                            10-Aug-2019 00:56                   -
php7.3/                                            09-Aug-2019 21:17                   -
php7.4/   
```

https://packages.sury.org/php/pool/main/p/

He only supports `supported` versions ...

**Comment by rfay** [comment]
Absolutely no way to get him to do it :) Have worked on that a bit :)  He almost turned off 5.6 and 7.0 earlier this year until somebody stepped up with security support for those.

**Comment by kaystrobach** [comment]
@rfay may using a dedicated docker image for fpm is the solution?

This would also ensure, that ddev can launch old environments.

**Comment by kaystrobach** [comment]
Right, would also mean a separate container per version. Might break the project - as we often also need the cli. Really hard to tackle problem.

**Comment by WarpedOne** [comment]
The reason I posted this issue was in case what was required was saving a resource that provided the older versions before they were deleted by the project owner, or asking them for older versions. I understand removing them when they are no longer supported, but devs sometimes need them for development work on older projects, as opposed to using them in a production environment, which none of us want to support. I've had to use older versions of Drupal to build a dev environment, and it wouldn't work with the latest PHP versions. Creating an environment that supports older versions is difficult and time consuming. If a project like DDEV made that easier, it would help pull people into using it that might stay permanently, because of how flexible it is. I'd rather suggest it now, when something easier might be done, than in a year, when it will be more difficult. And can we, as developers, really stop supporting something when hosting companies still provide them for their sites? Moving the latest production projects like Drupal off of deprecated dependencies is a good practice, but Dev environments are, by definition, not production.

**Comment by WarpedOne** [comment]
I'm not even sure if installing older versions of Docker would be possible, or if they would have already deleted the objects that contained the deprecated PHP versions. Maybe just saving those resources and providing a backup source for them is all that is required, before they are gone forever.

**Comment by rfay** [comment]
This [lando article](https://thinktandem.io/blog/2019/09/10/running-legacy-versions-of-drupal-on-lando/) has an interesting approach that could be much simpler in ddev (I think). Basically it would probably require a custom Dockerfile that used a FROM ubuntu:12.04, and then the use of deb.sury.org repos would have to be removed. It's similar to the "Run Ubuntu 12.04 in Virtualbox approach", but might have some standardization value.

**Comment by kaystrobach** [comment]
This! Sounds like a plan!

**Comment by WarpedOne** [comment]
I was kinda thinking it might require saving some files before they disappear. Or requesting files that may have been made unavailable. Whether older versions of docker, etc. In other words, something easier than creating it from scratch. Hopefully this is easy and sustainable. It's only for Dev environments temporarily, so security is not as much of an issue. How far back do current hosting allow you to go? I posted this in response to someone in slack looking for a PHP 5.3 environment.

**Comment by rfay** [comment]
The real problem is that old versions of PHP are not able to interoperate with current versions of openssl, which means that they're not able to build on current Debian, etc. So the key is to use *old* Debian/Ubuntu versions or images of old stuff, where that stuff plays happily. But, of course, doesn't play happily with current PHP versions.

FYI we *have* stored away versions of php5.6/7.0 packages, which sury was threatening to discontinue but backed off of. But *those* are after the key breakage of OpenSSL change.

**Comment by RedScourge** [comment]
I have compiled 5.3 successfully on Ubuntu 18.04 LTS recently. There's a lot of work involved, but I wrote out an entire guide on it a while ago so I do not forget in case I need it in the future. It doesn't generate packages, it just compiles it from source. It requires downloading the source for openssl 1.0.1 and the source of an old version of libGL for the main binary to compile, and a few other packages, but most of the modules can compile with OpenSSL 1.1 such as cURL and imap. It is actually a lot easier to compile on 16.04 as it comes with a choice of dev packages for openssl 1.0.1.

Perhaps that could be somewhat useful as a basis for someone to figure out how to package it?

**Comment by RedScourge** [comment]
oops, in my pastebin you will probably want to make a change as I did something custom:

look for this in the pastebin:
 export APACHE_RUN_USER=httpservice
 export APACHE_RUN_GROUP=httpusers

and change it to this:

 export APACHE_RUN_USER=www-data
 export APACHE_RUN_GROUP=www-data

**Comment by rfay** [comment]
Thanks @RedScourge - Have you tried this with *other* versions of PHP on the same machine? The problem has really been the coexistence of different versions of OpenSSL. (The ddev-webserver container has all versions installed on it.)

**Comment by RedScourge** [comment]
@rfay - If you compile it how I did, the main binary, which is the only part that seems to need the old version, links the OpenSSL libraries statically into the main binary, thereby making it no longer dependent on the OpenSSL version. However,  then the binary is like 25MB instead of the rather small size you get from whatever process Ondrej uses. I'm not quite sure how he gets it so small, but then again I am not an expert at compiling PHP. The compilation process uses the -dev packages, so I had the OpenSSL 1.1 libraries installed on the machine the whole time, but used the OpenSSL 1.0.1 source to compile against. I made it compile as few modules as possible in the main compilation step, then compiled all the modules which use OpenSSL against OpenSSL 1.1 as needed. Once it's all compiled, the -dev packages and OpenSSL 1.0.1 source can be removed completely and you'd only have 1.1 left on the system. 

The only (minor) problem I ran into was that after compile, I was getting warnings in syslog referring to /usr/local/lib/libcrypto.so.1.0.0, as according to the ldd command, apparently on Ubuntu 18.04 the /usr/bin/openssl binary looks for it there first before looking for it in /usr/lib/x86_64-linux-gnu/, though those warnings went away after I deleted the file and no functionality stopped.

**Comment by rfay** [comment]
A static binary id definitely the way to solve that problem. It would be cool if we could come up with a package that had the static binaries in it.

**Comment by RedScourge** [comment]
Indeed, and I am using PHP 5.3 on Ubuntu 16.04 in production and on 18.04 in test and it is very fast despite the large binary, so I know the file size is not a liability. I've never made a package before, so if someone here is good at packaging they may be able to use my guide to make one. I may go through Ondrej's guide at some point and try to do it myself but don't expect that any time soon.

Failing that, people can at least compile it as I did in my guide there. The way I did it, it can coexist with 5.6 and 7.3 on the same system, and allow switching via update-alternatives for cli+cgi, and via a2enmod/a2dismod for the apache module.

**Comment by RedScourge** [comment]
Just in case anyone was wondering which extensions my compile method works with, the answer is pretty much all of them. I went back and did a quick scripted "make test" in Ubuntu 18.04 on all of the ones that didn't require custom configure options and gathered the test fail/skip results here to give a little breakdown on that. Here's the commands I used to do that in case anyone was curious:

```
#to ensure I am compiling them against PHP 5.3
#update-alternatives --set php /usr/lib/php/5.3/bin/php
#update-alternatives --set php-config /usr/lib/php/5.3/bin/php-config
#update-alternatives --set phpize /usr/lib/php/5.3/bin/phpize

export NO_INTERACTION=true

function maketestphpmod(){
  cd /usr/src/php-5.3.29/ext/$1
  phpize
  ./configure
  make -j$(nproc) 2>&1 > build.make.$1.log
  make test > build.maketest.$1.log
  make clean
}

for i in bcmath bz2 calendar ctype dba dom exif fileinfo filter gettext gmp hash json mbstring mcrypt pcntl posix pspell readline ; do maketestphpmod $i; done
for i in recode shmop simplexml snmp soap sockets sysvmsg sysvsem sysvshm tidy tokenizer xmlreader xmlrpc xmlwriter xsl wddx zip ; do maketestphpmod $i; done

fgrep 'Tests failed' /usr/src/php-5.3.29/ext/*/build.maketest.*.log | fgrep -v 'Tests failed    :    0'
fgrep '100.0%' /usr/src/php-5.3.29/ext/*/build.maketest.*.log | grep skipped
```

The following are built-in when I compile PHP, because either the option to compile them as a separate module did not exist in PHP 5.3, or they require OpenSSL 1.0.x either to work at all or for all their extra options to work, or they're an SQL module which has to be built-in in order for its corresponding PDO module to work, or a combination of the last two:

openssl (has to be 1.0.1, is used by others which must be built-in such as mysqlnd)
mysql (because I do it with mysqlnd which must be built in)
odbc
pdo
pdo_mysql (because I do it with mysqlnd which must be built in)
pdo_odbc
pdo_pgsql
pdo_sqlite
sqlite
pgsql
zlib (must be built in)

The following modules built without any custom configure options:

bcmath bz2 calendar ctype dba dom exif fileinfo filter gettext gmp hash json mbstring mcrypt pcntl posix pspell readline recode shmop simplexml snmp soap sockets sysvmsg sysvsem sysvshm tidy tokenizer xmlreader xmlrpc xmlwriter xsl wddx zip

When I build those modules, here are the ones that fail tests with "make test", and how many test failures:

dom 1
fileinfo 1
pcntl 2 (i think it only works in cli/cgi i think)
readline 2 (make test says "warning: #warning Readline module will *NEVER* be thread-safe")
soap 2
sockets 1 (i think it only works in cli/cgi)
tidy 10 (did not test this, perhaps may need to compile against an older version of libtidy?)

Here are the ones that skip 100% of the tests:

recode (does not have any tests)
snmp (does not have any tests)
sysvsem 1/1
xml 81/81 (says "reason: xml extension not available", unsure if this indicates a problem)
xsl 35/35 (says "reason: xsl extension not available", unsure if this is a problem)

The following build with custom configure options:

curl (to specify openssl 1.1)
ftp (to specify openssl 1.1) skips 100% of tests, "make test" says "reason: fork not available"
gd (have to download a lot of source packages and specify them) skips 22 tests, fails 8 tests, passes 223 tests
imap (just --with-kerberos --with-imap-ssl)
ldap (--with-ldap=/usr --with-ldap-sasl --with-libdir=lib/x86_64-linux-gnu)
mssql (--with-libdir=lib/x86_64-linux-gnu)
xmlrpc (must export CC and CFLAGS before compile then unset after)

These ones should be installed as PECL packages, or an old version of the source should be downloaded from PECL and compiled by hand as they may have phased out PHP 5.3 support:

intl
imagick

With every single module enabled, PHP did not crash or segfault for me at all or behave buggy as far as I could tell, though I did not test any XML or tidy stuff, though I did test cURL and GD

**Comment by kaystrobach** [comment]
The long term question is, if the better long term solution would be to have a docker image for every php-fpm version supported, this way ddev can be extremely flexible and support more versions. Maybe also an image per master branch (5.x, 7.x) can be a solution

**Comment by RedScourge** [comment]
I'm not familiar with docker images or php-fpm, as most of what I deal with has depended on the apache2/apxs SAPI, but if that involves compiling PHP from source, whoever attempts it will probably find that my little guide there should have enough to give them everything they need. I really need to turn it into a blog post somewhere tbh.

Also just a minor deficiency I just found with my guide there while digging through my syslog, if you want the Ubuntu `/usr/lib/php/sessionclean` script to also work with it, you'll want to add running `ln -s /usr/lib/php/5.3/bin/php /usr/bin/php5.3` to tyhat process, as that script looks for the PHP 5.3 binary at that location

**Comment by kaystrobach** [comment]
Maybe these are a staring point

https://hub.docker.com/r/bitnami/php-fpm/tags?page=444

Still need tuning for ddev though

**Comment by RedScourge** [comment]
Regarding my tests above, the `make test` tests all being skipped for the xml module with the cryptic message `reason: xml extension not available` had me worried, so I whipped together a test script to find out if calls to its xml_parser() function work, and it worked.

With the following test script:

xml.php:
```
<?php

$xml = '
<response>
        <method>test</method>
        <result>this is a test</result>
</response>
';

$parser = xml_parser_create();
$bob = xml_parse( $parser, $xml, true );
if( $bob == 0 )
{
        echo xml_get_error_code( $parser );
        echo xml_error_string( xml_get_error_code( $parser ) );
}
var_dump( $bob );
xml_parser_free( $parser );

?>
```

I ran it on the command line via `/usr/bin/php5.3 xml.php` and the return was `int(1)`.

I also ran it with invalid XML and it did in fact go into the if() statement and dumped out an error code and message, so those 3 functions which are defined in the xml module, which should only work if the module is loaded, clearly work. I suspect that whatever caused all the xml module tests to be skipped also caused the same for xsl, and so if xml works xsl probably does too.

**Comment by RedScourge** [comment]
Also, have you guys heard of phpbrew (its on [GitHub](https://phpbrew.github.io/phpbrew/))? It's a shell tool which will help you build and manage several different custom builds of php on the same system through your /home folder.

I tried it and didn't like it because I don't think it was designed to be run as root, but then assumed you had root permissions if you wanted to install the apache2/apxs SAPI, and it messed around with your PEAR/PECL config parameters for your user, but for most people it's probably an easier solution for rolling your own PHP >= 5.3 binaries for testing, especially if you have a separate user account for using phpbrew that you can login to, so that it does not mess with any other account's environment variables.

I ran the following on Ubuntu 18.04 to get it to build me a static PHP 5.3 for just my non-root user:

```
cd ~
wget https://github.com/phpbrew/phpbrew/archive/master.zip
unzip master.zip
cd phpbrew-master/
./phpbrew init
echo source ~/.phpbrew/bashrc >> ~/.bashrc
source ~/.phpbrew/bashrc
curl -sS https://getcomposer.org/installer | php
php composer.phar install
phpbrew update --old

# export apache variables which Ubuntu writes in /etc/apache2/envvars:
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_PID_FILE=/var/run/apache2/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_LOG_DIR=/var/log/apache2

# to build cli SAPI on Ubuntu 18.04 it's easy:
# assuming you have already downloaded source and compiled openssl 1.0.x in /usr/local 
# and libcrypto.so.1.0.0 and libssl.so.1.0.0 exist in /usr/local/lib
# note: may want to move/remove/rename those two after, as they 
# conflict with package openssh-server
phpbrew install 5.3.29 +everything -fpm -apxs2 +cli -cgi -embed -gcov -- --with-curl=shared,/usr/include/x86_64-linux-gnu/curl

# to build apache2/apxs sapi module you must give phpbrew access to 
# make changes to your apache config, and you must have compiled cli first!
sudo chmod a+rw /usr/lib/apache2/modules
sudo chmod a+rw /etc/apache2
sudo chmod a+rw /etc/apache2/mods-available
sudo chmod a+rw /etc/apache2/mods-enabled
phpbrew install 5.3.29 +everything -fpm +apxs2 -cli -cgi -embed -gcov -- --with-curl=shared,/usr/include/x86_64-linux-gnu/curl
# and finally instruct phpbrew to use that newly compiled version assuming it worked:
phpbrew switch php-5.3.29
```
To examine installed extensions, run `phpbrew ext`
To have phpbrew compile an extension, for example the imap extension which requires custom parameters, run `phpbrew ext install imap -- --with-kerberos --with-imap-ssl`
To go back to system php, run `phpbrew switch-off`

Note that you may want to prefer to compile php with fewer modules and then use the phpbrew commands to add extensions after, especially if you have difficulty compiling on your system. This will become more of an issue as Ubuntu updates libraries and downloading more old versions of those libraries from source and compiling against them becomes necessary.

**Comment by rfay** [comment]
If you read above you'll find my completely disastrous experiences with PHPBrew. It has the same problems as every other build technique.

**Comment by kaystrobach** [comment]
therefore i'd opt for going with separated docker images per main version

**Comment by RedScourge** [comment]
@rfay - It's true that phpbrew does not resolve the OpenSSL issue, which causes both of those above mentioned phpbrew issues. To resolve them on Ubuntu 16.04, you should only need to issue this command first:
```
apt-get install libssl-dev=1.0.2*
```
This works because they released a 1.0.x openssl dev package for 16.04, though it is not installed by default.

On Ubuntu 18.04, they did not release any such package, so you end up having to download and compile your own in /usr/local, create a few symlinks, pass special parameters to the `./configure` command if compiling by hand (or the `phpbrew install` command if doing it through phpbrew) to make it look for openssl in /usr/local, and compile. You'd want to use the process I came up with for downloading and compiling OpenSSL 1.0.1, getting the PHP compile to use it, then adding ` -- --with-curl=shared,/usr/include/x86_64-linux-gnu/curl` at the end of the `phpbrew install` command if your phpbrew command includes curl, or the `phpbrew ext install curl` command if compiling it separately, though I think it makes more sense to do it in the main php compile.

**Comment by RedScourge** [comment]
Anyway, sorry for all the blabbing in here about this; I just wanted to make sure there's a record somewhere on the Internet that there is in fact a way to get PHP 5.3 to compile on Ubuntu 16.04 and 18.04, because I had been wanting to do this for years and only figured it out recently,

**Comment by rfay** [comment]
I spent some more time fiddling with external PHP containers today. It's pretty easy to get an external container like https://hub.docker.com/r/devilbox/php-fpm-5.2 going. (Built from https://github.com:devilbox/docker-php-fpm-5.2)

I created a "php" service with a docker-compose.php.yaml like this:

```

version: '3.6'

services:
  php:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-php
#    image: docker-php-fpm-5.2:latest
    image: devilbox/php-fpm-5.2
    restart: "no"
    ports:
      - 9000
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
    - type: bind
      source: ../
      target: /var/www/html
      consistency: cached
    - ".:/mnt/ddev_config:ro"
    - ddev-global-cache:/mnt/ddev-global-cache

#    user: "$DDEV_UID:$DDEV_GID"
    hostname: $DDEV_HOSTNAME

  web:
    links:
      - php:$DDEV_HOSTNAME
```

Then I switched to Apache, since older sites are more likely to work with apache, and moved to the oldest mariadb we explicitly support, so config.yaml needed
```
webserver_type: apache-fpm
mariadb_version: 10.1
```

Then I used a custom .ddev/apache/apache-site.conf, because it needs to go off-container for the fpm/cgi process:

```
<VirtualHost *:80>
    # Workaround from https://mail-archives.apache.org/mod_mbox/httpd-users/201403.mbox/%3C49404A24C7FAD94BB7B45E86A9305F6214D04652@MSGEXSV21103.ent.wfb.bank.corp%3E
    # See also https://gist.github.com/nurtext/b6ac07ac7d8c372bc8eb

    RewriteEngine On
    RewriteCond %{HTTP:X-Forwarded-Proto} =https
    RewriteCond    %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
    RewriteRule    ^(.+[^/])$           https://%{HTTP_HOST}$1/ [redirect,last]

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on

	ServerAdmin webmaster@localhost
	DocumentRoot $WEBSERVER_DOCROOT
	<Directory "$WEBSERVER_DOCROOT/">
  		AllowOverride All
  		Allow from All
	</Directory>
	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog /dev/stdout
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
	# Simple ddev technique to get a phpstatus
	Alias "/phpstatus" "/var/www/phpstatus.php"

    <FilesMatch ".+\.ph(ar|p|tml)$">
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>
    <FilesMatch ".+\.phps$">
        # Deny access to raw php sources by default
        # To re-enable it's recommended to enable access to the files
        # only in specific virtual host or directory
        Require all denied
    </FilesMatch>
    # Deny access to files without filename (e.g. '.php')
    <FilesMatch "^\.ph(ar|p|ps|tml)$">
        Require all denied
    </FilesMatch>
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/master.crt
    SSLCertificateKeyFile /etc/ssl/certs/master.key

    # Workaround from https://mail-archives.apache.org/mod_mbox/httpd-users/201403.mbox/%3C49404A24C7FAD94BB7B45E86A9305F6214D04652@MSGEXSV21103.ent.wfb.bank.corp%3E
    # See also https://gist.github.com/nurtext/b6ac07ac7d8c372bc8eb

    RewriteEngine On
    RewriteCond %{HTTP:X-Forwarded-Proto} =https
    RewriteCond    %{DOCUMENT_ROOT}%{REQUEST_FILENAME} -d
    RewriteRule    ^(.+[^/])$           https://%{HTTP_HOST}$1/ [redirect,last]

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on

	ServerAdmin webmaster@localhost
	DocumentRoot $WEBSERVER_DOCROOT
	<Directory "$WEBSERVER_DOCROOT/">
  		AllowOverride All
  		Allow from All
	</Directory>
	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog /dev/stdout
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
	# Simple ddev technique to get a phpstatus
	Alias "/phpstatus" "/var/www/phpstatus.php"

    <FilesMatch ".+\.ph(ar|p|tml)$">
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>
    <FilesMatch ".+\.phps$">
        # Deny access to raw php sources by default
        # To re-enable it's recommended to enable access to the files
        # only in specific virtual host or directory
        Require all denied
    </FilesMatch>
    # Deny access to files without filename (e.g. '.php')
    <FilesMatch "^\.ph(ar|p|ps|tml)$">
        Require all denied
    </FilesMatch>
</VirtualHost>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

But wow, I still wasn't there. Although a phpinfo() was fine and showed everything I wanted, I ran into other troubles, and wasn't successful doing an install of Drupal5 or Drupal6. 

I also tried installing Drupal 4.6... remember? You had to manually load the database, there was no install process. I had to remove TYPE=MyISAM from all the table creation stanzas. Didn't work anyway.

So this approach definitely ought to work, but it's once again a lot of work, with modest results. All failed in my case. 

The good news is that the devilbox php 5.2 project does demonstrate how and where to build a statically linked php on debian jesse, and installs what it needs there. As @RedScourge points out, this is a technique that ought be be do-able and repeatable. It's *possible* that php 5.2 could be built in our web container for special cases. 

It's possible that somebody could push this work through; the idea of using an external one-off PHP container certainly should work.

**Comment by rfay** [comment]
Well, I did do a basic Drupal5 install using an Ubuntu 12.04 VM with Apache/php5.3 using basically just the recipe in https://www.howtoforge.com/installing-apache2-with-php5-and-mysql-support-on-ubuntu-12.04-lts-lamp

I created a user, created a page or two, dumped the database, brought it down to just the setup in https://github.com/drud/ddev/issues/1714#issuecomment-538799770 and it worked. So it may be even though I can't get an *install* to work in this environment, it actually works for real life.

**Comment by rfay** [comment]
OK, I wrote this up in ddev-contrib, and it's now available as a pretty flexible recipe, https://github.com/drud/ddev-contrib/blob/master/docker-compose-services/old_php
