### ISSUE TITLE
Add cron support inside the web container

### ISSUE THREAD

**Issue by mfrieling** [drud/ddev#1715]
**Is your feature request related to a problem? Please describe.**
To test correct execution of cron tasks (e. g. `drush cron`, `drupal cron:execute` or packages/Symfony bundles depending on [`mtdowling/cron-expression`](https://packagist.org/packages/mtdowling/cron-expression), inculding `laravel/framework` ) it would be really helpful or in case DDEV is used for staging environments.

**Describe the solution you'd like**
Be able to run cronjobs via `crontab -e` inside the web container, e. g. using a file `.ddev/cron` which is loaded into crontab automatically on `ddev start` if it exists. 

**Describe alternatives you've considered**
The problem with using crontab from the host (I tested this only on Debian) is that the environment is completely different than if you execute the task manually. While it works fine manually executed by crontab it could fail due to missing stuff. The first error I got was that DDEV cannot be found. Calling it with the full path to the executable or loading `~/.profile` before running `ddev exec` didn't help as that produced other errors, like

> Failed to create required directory /home/.ddev, err: mkdir /home/.ddev: permission denied

or

> docker-compose does not appear to be installed.

**Comment by rfay** [comment]
I don't think crond is possible (at least easily), because it requires installing and running crond in the container. 

Note that the problem you had with not being able to create /home/.ddev should not happen any more in v1.10+ (prerelease today), at least I'd love to have you try it. Each user gets a real installed user now, with a home directory with the right perms, etc.

Any solution that does *not* require having crond running in the container is a possible win.

**Comment by mfrieling** [comment]
Understand. A solution running on the host which is capable of executing anything via `ddev exec` which can be executed manually this way should be sufficient too.

Maybe the mentioned `.ddev/cron` file which either just contains the (container-side) command to run via `ddev exec` or with a cron expression, in case something like [`mtdowling/cron-expression`](https://packagist.org/packages/mtdowling/cron-expression) exists for the language DDEV is developed with. Then either utilize native crond on the host if available or just run a background process which triggers in a defined interval (e. g. every minute) for each project which has cron enabled. The best would be to introduce a parameter similar to `xdebug_enabled` in config.yaml

`cron_enabled: false|true|[time-interval]`

- `false`: don't execute cron for this project
- `true`: execute cron for this project with the default (or maybe globally configured) time interval
- [time-interval]: something like `1m` (every minute), `5`m (every five minutes), `1h` (every hour), ...

**Comment by thomaskieslich** [comment]
Hi, I think have a Solution without change ddev. I will describe how it works, in my Case with TYPO3.
Step 1
Create a file 'typo3' inside a new created 'corn' Folder inside .ddev. 
`# m h  dom mon dow  user  command
*/1 * * * * root TYPO3_CONTEXT=Development/Local /usr/bin/php /var/www/html/public/typo3/sysext/core/bin/typo3 scheduler:run`

i have a docker-compose.override.yml with this content, the important Line is the last one:
`version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=Development/Local
    volumes:
      # mount composer cache
      - ~/.composer/cache:/home/application/.composer/cache
      # add php xdebug profile path
      - ./data/php-profiles/:/tmp/debug/:delegated
      # add crontab
      - ./cron/typo3:/etc/cron.d/typo3`
to link the cron file to the container.

To install the install cron into the Container i add this hooks to config.yml:
`hooks:
  post-start:
    - exec: sudo apt-get -y update
    - exec: sudo chmod 0600 /etc/cron.d/typo3
    - exec: sudo apt-get -y install --no-install-recommends cron
    - exec: sudo apt-get -y clean
    - exec: sudo service cron start`

It works with root because the php file can exec from all users.
Repo: https://github.com/thomaskieslich/ddev-typo3/tree/development/.ddev

I hope it works for you and perhaps this can be added to the docs ;-)

**Comment by rfay** [comment]
Wow, that's great, thanks. I imagine that adds lots of stuff, but if it's what anybody needs it's fine. 

I'd recommend doing the package in the config.yaml, much, much easier: `webimage_extra_packages: ["cron"]`, and you can probably do everything else you might want in .ddev/web-build/Dockerfile too... or maybe add the package there (same result). 

Would appreciate if you could expand on this and do a PR to github.com/drud/ddev-contrib ! Thanks!

**Comment by thomaskieslich** [comment]
With --no-install-recommends it needs 247kb on Disk ;-) I will see how i can realize it with webimage_extra_packages and then i can make a PR.
Thanks for the explanation of the Possibilities.

**Comment by davdenic** [comment]
I have errors in both ways, log says:

Setting up exim4-config (4.89-2+deb9u5) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Adding system-user for exim (v4)
adduser: No UID/GID pair is available in the range 100-999 (FIRST_SYS_UID - LAST_SYS_UID).
adduser: The user `Debian-exim' was not created.
dpkg: error processing package exim4-config (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of exim4-base:
 exim4-base depends on exim4-config (>= 4.82) | exim4-config-2; however:
  Package exim4-config is not configured yet.
  Package exim4-config-2 is not installed.
  Package exim4-config which provides exim4-config-2 is not configured yet.

dpkg: error processing package exim4-base (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of exim4:
 exim4 depends on exim4-base (>= 4.89-2+deb9u5); however:
  Package exim4-base is not configured yet.
 exim4 depends on exim4-base (<< 4.89-2+deb9u5.1); however:
  Package exim4-base is not configured yet.

dpkg: error processing package exim4 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of exim4-daemon-light:
 exim4-daemon-light depends on exim4-base (>= 4.89); however:
  Package exim4-base is not configured yet.

dpkg: error processing package exim4-daemon-light (--configure):
 dependency problems - leaving unconfigured
Setting up cron (3.0pl1-128+deb9u1) ...
addgroup: No GID is available in the range 100-999 (FIRST_SYS_GID - LAST_SYS_GID).
addgroup: The group `crontab' was not created.
dpkg: error processing package cron (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mailutils:
 mailutils depends on default-mta | mail-transport-agent; however:
  Package default-mta is not installed.
  Package exim4-daemon-light which provides default-mta is not configured yet.
  Package mail-transport-agent is not installed.
  Package exim4-daemon-light which provides mail-transport-agent is not configured yet.

dpkg: error processing package mailutils (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 exim4-config
 exim4-base
 exim4
 exim4-daemon-light
 cron
 mailutils
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by thomaskieslich** [comment]
you must use the --no-install-recommends Option.
apt-get -y install --no-install-recommends cron

**Comment by rfay** [comment]
Since that is in fact the correct approach, I added it to the implementation of *image_extra_packages in https://github.com/drud/ddev/pull/1776

**Comment by rfay** [comment]
BTW, I tested this technique and it works great. The magic is in starting cron in the post-start hook, which is what I hadn't considered before. I had always hesitated because systemctl or whatever has to start all the services... but here you are starting it manually. Nice work!

**Comment by thomaskieslich** [comment]
Thanks, i am new with ddev since Version 1.10 (because it has cmmands) and the TYPO3 Developer Days. Thanks for your nice Job. I will try out different Ways to run cron and then i will make a PR to ddev-contrib Repo. My current Favorit is to run cron with a Command File in commands/web because i can only Start it if i need it.
commands/web/cron
`
sudo apt-get -y update
sudo apt-get -y install --no-install-recommends cron
sudo apt-get -y clean
sudo chmod 0600 /etc/cron.d/typo3
sudo service cron start
`

**Comment by rfay** [comment]
https://github.com/drud/ddev-contrib/blob/master/recipes/cronjob/README.md now has a nice recipe for cron. Thanks @thomaskieslich .

**Comment by bfuzze** [comment]
Both of these approaches seem to work...
* First approach is typo3 specific, whereas I need a framework agnostic solution.
* Second approach modifies the Docker build which seems unnecessary and I prefer to avoid if possible.

I settled on the following composite solution...

**.ddev/config.yaml**
```
webimage_extra_packages: ["cron --no-install-recommends", "dos2unix --no-install-recommends"]

hooks:
  post-start:
    - exec: /bin/cat /mnt/ddev_config/crontab | /usr/bin/dos2unix | /usr/bin/sudo crontab -
    - exec: /usr/bin/sudo /etc/init.d/cron restart
```

**.ddev/crontab**
```
*/1 * * * * echo "CHECK2" >> /var/www/html/temp/cron.log
```

**.ddev/commands/web/reload-crontab**
(so we can adjust crontab with restarting the container)
```
#!/usr/bin/env bash

## Description: Reloads cron from .ddev/crontab
## Usage: reload-crontab
## Example: "ddev reload-crontab"

/bin/cat /mnt/ddev_config/crontab | /usr/bin/dos2unix | /usr/bin/sudo crontab -
```

Thanks.

**Comment by andrewbelcher** [comment]
FYI for those having issues with drush and loading `settings.ddev.php`, it is likely because the include checks for the `IS_DDEV_PROJECT` environment variable. You can provide that by setting up your crontab like:

```
IS_DDEV_PROJECT=true
*/5 * * * * /var/www/html/vendor/bin/drush --root=/var/www/html/web core-cron -l https://example.ddev.site >> /tmp/cron.log 2>&1
```

And for reference for those who need to do this along side a customer Dockerfile (as I did as I install some other built tools), instead of using `webimage_extra_packages` you can use a `.ddev/web-build/Dockerfile` containing:

```
ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN apt-get update

# Install cron.
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests cron

# Do whatever else you need to do...
```

I didn't bother with dos2unix as, but you can add that in the same manner.

**Comment by beanjammin** [comment]
If you are trying to run drush via cron in ddev the missing piece is that you need to set _both_ IS_DDEV_PROJECT=TRUE and DDEV_PHP_VERSION or settings.ddev.php won't load the correct database connection info.

In your /etc/cron.d/<file>:

`IS_DDEV_PROJECT=TRUE
DDEV_PHP_VERSION=8
# m h dom mon dow user command
* * * * * root /var/www/html/vendor/bin/drush --root=/var/www/html/docroot --uri http://mysite.ddev.site cron > /dev/null 2>&1`

**Comment by rfay** [comment]
@beanjammin inside the container IS_DDEV_PROJECT is always set. You must be talking about running cron on the host? 

```
rfay@rfay-tag1-m1:~/workspace/d9$ ddev exec 'echo $IS_DDEV_PROJECT'
true
rfay@rfay-tag1-m1:~/workspace/d9$ ddev ssh
rfay@d9-web:/var/www/html$ echo $IS_DDEV_PROJECT
true
```

**Comment by beanjammin** [comment]
@rfay I'm running cron inside the web container.

If I add the file /etc/cron.d/test:

# m h dom mon dow user command
* * * * * root /usr/bin/printenv > /tmp/root_cron_env.txt 2>&1

The logged output is:

HOME=/root
LOGNAME=root
PATH=/usr/bin:/bin
SHELL=/bin/sh
PWD=/root

I needed to add IS_DDEV_PROJECT=TRUE and DDEV_PHP_VERSION=8 in order to get settings.ddev.php to be used and to load the correct database connection info.

**Comment by rfay** [comment]
Odd, but you really don't want to be running things as root, but rather as your own user. Running as root causes all kinds of issues. And I do remember that cron has its own special issues with initialization, so maybe that's it.

**Comment by beanjammin** [comment]
Perhaps it's a misunderstanding on my part, but with multiple developers using the resulting dev environment and the need to add a username to cron tasks when used in /etc/cron.d, root seems like the only option as it's the only user common across all of our systems.  Is there another way I can accomplish this without using root?

FWIW I'm using cron to run drush cron to run queued tasks to clear varnish cache.

**Comment by andrewbelcher** [comment]
My above comment that adds the crontab via a post start hook will solve the multiple users issue as it will add it to whichever user is starting ddev.

**Comment by beanjammin** [comment]
Thanks @andrewbelcher, I hadn't paid enough attention to your comment.  Looks like a better approach.

**Comment by alanmels** [comment]
Hi everyone! 

The easiest way to get this working on my MBP turned out to be the simplest way:

1. cd ~/sites/mysite 
2. ddev describe // grab the last one in All URLs raw. Note aliased one won't work, so it must be numeric one.
3. crontab -e // fire up the old good crontask installation command.
4. and install your cron-job like so:

```
*/1 * * * * /opt/homebrew/bin/wget -O - -q -t 1 http://127.0.0.1:57248/core/cron.php?cron_key=PpegWRHV5H5t4ZQw1YgcjpxsHiGJw_NTRUB5553f5BI
```

Works like charm and you don't have to install anything additional.

**Comment by rfay** [comment]
You should know about the new ddev get add-on recipe, https://github.com/tyler36/ddev-cron - it's almost ready to be promoted to official. You can just `ddev get tyler36/ddev-cron`. /cc @tyler36

**Comment by avioli** [comment]
> You should know about the new ddev get add-on recipe, https://github.com/tyler36/ddev-cron - it's almost ready to be promoted to official. You can just `ddev get tyler36/ddev-cron`. /cc @tyler36

After adding `ddev-cron` via `ddev get tyler36/ddev-cron` I've used the following `.ddev/config.cron.yml` for my Drupal development environment:

```yml
hooks:
  # This will be executed whenever DDEV starts
  post-start:
    # This line creates a job, ddev-cron-drupal, and configures it to run every 5 minutes
    - exec: "{ env | grep DDEV ; echo ; echo '*/5 * * * * '$(whoami)' cd /var/www/html/ && ./vendor/bin/drush cron' ; } | sudo tee -a /etc/cron.d/ddev-cron-drupal | grep -v DDEV"
```

It outputs your DDEV env variables into `/etc/cron.d/ddev-cron-drupal` so Drush is happy:

```
DDEV_WEBSERVER_TYPE=nginx-fpm
IS_DDEV_PROJECT=true
DDEV_DOCROOT=web
DDEV_FILES_DIR=/var/www/html/web/sites/default/files
DDEV_PRIMARY_URL=https://my-site.ddev.site
DDEV_SITENAME=my-site
DDEV_ROUTER_HTTP_PORT=80
DDEV_PHP_VERSION=8.1
DDEV_TLD=ddev.site
DDEV_HOSTNAME=my-site.ddev.site
DDEV_PROJECT=my-site
DDEV_XDEBUG_ENABLED=false
DDEV_PROJECT_TYPE=drupal9
DDEV_ROUTER_HTTPS_PORT=443

*/5 * * * * user cd /var/www/html/ && ./vendor/bin/drush cron
```

**Comment by tyler36** [comment]
Thanks for posting feedback.  Glad to hear it working. 😄
