### ISSUE TITLE
"bash: ddev: command not found" after installing DDEV and Docker Toolbox for Windows 10 Home

### ISSUE THREAD

**Issue by JackG102** [drud/ddev#1771]
**Describe the bug**
After installing Docker Toolbox and DDEV on Windows 10 Home with the .exe file method, I receive "bash: ddev: command not found" when running "ddev" with administrator privileges in Quickstart Docker Terminal or the CMD prompt.  I have restarted my computer multiple times to see if that "refreshes" anything.

**To Reproduce**

I am installing DDEV on Windows 10 Home Edition.  Docker Toolbox is installed and I was able to get the "hello world" container to run to make sure that it was all in working order.

The problem that I am having is that I have installed DDEV using the .exe file (and then later chocolately) based on the DDEV installation instructions.  Afterwards, I restarted my computer, then relaunched Docker Quickstart Terminal, and then ran "ddev".  I get the error "bash: ddev: command not found".  I have tried to run "ddev" in the command prompt with the same "ddev: command not found" error.

I have also tried to install DDEV using chocolatey. Running "choco install ddev" on in the Docker Quickstart Terminal.  I receive the message "ddev v1.10.1 already installed..."

First time making an issue request on Github, so I am not quite sure if you need any more information!  It seems like it installed but Windows isn't recognizing it.

**Expected behavior**
I have installed Docker and DDEV on my Apple ProBook, but I will have multiple people using Docker and DDEV on various operating systems, so Windows 10 Home installation will be a likely scenario.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Windows 10 home 
 - Docker Toolbox 19.03.1.
 - DDEV attempted installation 1.10.1

**Comment by rfay** [comment]
So the problem is that ddev is not in your PATH. BTW, you don't need to have admin privs to run ddev. 

If you look in C:\Program Files\ddev using any tool, you'll see ddev.exe in there if it's been installed using the windows installer or using chocolatey.

That *should* be added to your path by any of the install techniques above, but you may have some kind of override on your system that is preventing that. But you can add it to the PATH using Windows own technique (the environment variable control panel) or any technique you want.

If you're using the Docker Quicstart Terminal  then `echo $PATH` will show you what's currently in your path

**Comment by JackG102** [comment]
Randy, thank you so much!  I went and added C:\Program Files\ddev to the $PATH variable, restarted my machine, and ddev was instantly recognized.  thank you for the explanation of what _should_ happen as well; I'll keep that in mind when we install ddev on various machines.  I should have made an issue here a few hours ago and saved some time.  Many thanks!
