### ISSUE TITLE
Unable to find .ddev/router-compose.yaml when restarting ddev when it has never been started

### ISSUE THREAD

**Issue by mherchel** [drud/ddev#1779]
**Describe the bug**
When following directions with the Drupal 8 quickstart, I receive the following error when attempting `ddev restart`:
```Restarting project xxx-d8...
.FileNotFoundError: [Errno 2] No such file or directory: '/Users/mherchel/.ddev/router-compose.yaml'
Failed to restart xxx-d8: Failed to run docker-compose [-f /Users/mherchel/.ddev/router-compose.yaml -p ddev-router down], err='exit status 1', stdout='', stderr='.FileNotFoundError: [Errno 2] No such file or directory: '/Users/mherchel/.ddev/router-compose.yaml''
```

Note that the `/Users/mherchel/.ddev/router-compose.yaml` does not exist

**To Reproduce**
1. Follow quickstart guide located at https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart
2. The only difference is I'm using an existing site along with it's composer files.
3. When running `ddev restart` per documentation, I receive the error.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: MacOS 10.14.5 Mojave
 - Docker version information: 19.03.1
 - ddev version information: v1.10.2
 - config.yaml contents for the misbehaving project
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? Nope. Evaluating for the very first time.

**Comment by rfay** [comment]
Thanks for the report I can recreate this, it's an interesting bug.

Basically, ddev has never been run before, and as a result it can't find the router_compose.yaml to *stop* anything. 

If you had used the more appropriate drupal8 quickstart git clone instructions instead it would have worked; in the composer situation you've already started it once.

But for you... just use `ddev start` instead of `ddev restart` and you'll be fine. Since it hasn't been started before it doesn't need to be stopped and started.

**Comment by mherchel** [comment]
Looks to be working! Thanks @rfay !

**Comment by rfay** [comment]
Might as well keep this open and fix the bug.

**Comment by rfay** [comment]
This also happens if your first-ever `ddev start` fails (like the bind-mount failure from docker) or is interrupted, and then you do a `ddev stop`
