### ISSUE TITLE
Include ImageMagick with WEBP support

### ISSUE THREAD

**Issue by mherchel** [drud/ddev#1780]
**Is your feature request related to a problem? Please describe.**
DDEV currently supports WebP through the PHP GD extension, but does not support WebP through ImageMagick (see image below).

Unfortunately, Pantheon is exactly the opposite, and supports WebP through ImageMagick but not GD. 🤷‍♂️

**Describe the solution you'd like**
It'd be super nice if DDEV included ImageMagick support for WebP :)

**Describe alternatives you've considered**
I could use Drupal 8 contrib's config split module to change configs depending on the environment. 

**Additional context**

![image](https://user-images.githubusercontent.com/1605905/62823453-f9932200-bb5e-11e9-8bfe-565ade164a1f.png)
![image](https://user-images.githubusercontent.com/1605905/62823513-7de5a500-bb5f-11e9-9f29-f776f152a3af.png)

**Comment by rfay** [comment]
It looks like you might just want to add the webp package, as in https://github.com/drud/ddev/issues/1460 - add `webimage_extra_packages: [webp]` to your config.yaml. If you think that should be done by default we'll listen, but as you know, adding every default package everybody wants is the road to amazing bloated container.

**Comment by mherchel** [comment]
Thanks for the response. I can't seem to get it to work, however.

1. `webimage_extra_packages: [webp]` to the bottom of the `.ddev/config.yml `
2. `ddev restart`
3. Refresh the phpinfo at `/admin/reports/status/php` (ensuring that browser isn't caching the HTML)
4. That didn't work, so I tried `ddev config --webimage-extra-packages 'webp'`
5. The command line indicated that worked, but PHPInfo still shows Imagemagick without WebP.

![image](https://user-images.githubusercontent.com/1605905/62824050-55ad7480-bb66-11e9-9bd6-81f37962effc.png)


 Agree that it doesn't need to be enabled by default, but it might be necessary to mention in the docs. I found the `webimage-extra-packages` option within https://ddev.readthedocs.io/en/latest/users/extend/config_yaml/, but it doesn't mention webp.

**Comment by rfay** [comment]
There's no difference between adding to webimage_extra_packages to config.yaml and --webimage-extra-packages=webp, they both add the same thing to the config.yaml, which is what matters. 

I see loads of confusion and manual compilation in web searches for solving this problem:
* http://www.imagemagick.org/discourse-server/viewtopic.php?t=35756
* https://github.com/rosell-dk/webp-convert/wiki/Installing-Imagick-extension
* https://stackoverflow.com/questions/25248382/how-to-create-a-webp-image-in-php

And many others. I don't have any visibility into what Pantheon has done; I'm certain it's do-able. The web container uses Debian Stretch, and anything you can do in debian (almost anything) is do-able. But I don't personally have any experience with webp, and it does look like there's lots of effort and confusion in that area on the web. 

Looking forward to working this through!

The docs don't mention webp because it's one of hundreds (thousands?) of Debian packages that can be installed on demand.  The ability to install whatever package you want or need gives enormous power.

**Comment by rfay** [comment]
Very happy to incorporate this or document it if a recipe for Debian 9 is discovered.

**Comment by rfay** [comment]
Imagemagick and gd both seem to include webp support out of the box in recent versions of ddev (probably since the web container moved to Debian Buster):

<img width="956" alt="PHP_7_3_15-4_0_20200224_55_debian10_1_gbpbea824_-_phpinfo__" src="https://user-images.githubusercontent.com/112444/77854104-623e1600-71a5-11ea-8cb0-7a9596579aba.png">
