### ISSUE TITLE
drupal8 settings.ddev.php should use accepted local dev settings

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1811]
**Describe the bug**

https://www.drupal.org/node/2598914 has a list of basic things that should be done for a local setup. We don't do all of them. These can be added to settings.ddev.php.

From @vordude's presentation https://www.youtube.com/watch?v=HnepxxHpvr4&list=PLNKGKLLALSkwihl2utw1ayLoincKouSih&index=21&t=0s

**Comment by mharmuth** [comment]
It would be nice to have the `settings.ddev.php` file in the .ddev directory (and remove it from the .gitignore) to make own modifications to the file without having it in the direct drupal context (sites/default). So for production purposes I only have to remove the .ddev directory.

**Comment by rfay** [comment]
I like that idea. 

BTW, there's no actual need (in most cases) to remove the .ddev directory for prod, since it's irrelevant. 

FYI though, settings.ddev.php is intended to never exist on prod because it never gets committed, and is created on each config or start by ddev.  So if you're committing it it isn't meant to be committed (it's gitignored), and so should never exist or arrive on prod.

**Comment by mharmuth** [comment]
I needed to be a little bit more clear with my `settings.ddev.php` statement 😄 

I want to commit this file in development because I want to make some changes (non sensitive information) that the whole team working on a project should have. 

For example: We are using drupal/swiftmailer module. On development we want to use ddev's mailhog option. On production, I want to use some other SMTP server. So I want to change drupal's config by adding this part to the settings.ddev.php file:

```
    $config['swiftmailer.transport'] = [
        'transport' => 'smtp',
        'smtp_host' => '127.0.0.1',
        'smtp_port' => '1025',
        'smtp_credentials' => [
            'swiftmailer' => [
                'username' => '',
                'password' => '',
            ],
        ],
    ];
```

I know that we could use the config split module, but I don't like that approach as we only need some little config changes that can be easily done with a few lines of code ;-)

**Comment by rfay** [comment]
So it's pretty easy to put stuff like that in a settings.local.php and manage the settings.local.php as you like. And if anything in the settings.local.php has to override settings.ddev.php, do the inclusion of it *after* the inclusion of settings.ddev.php in settings.php.

The reality is that if you want to take control of settings.ddev.php (which is by default regenerated with every `ddev start`) you'd be better off using project type 'php' and just managing all the settings yourself. Which in the case of somebody who clearly knows their way around like you do, is just fine and easy.

**Comment by rfay** [comment]
Closing this one in favor of https://github.com/drud/ddev/issues/1097 (base settings.ddev.php on default.settings.php); I think I copied the key things over there.
