### ISSUE TITLE
Improve ddev snapshot UI - Suggest or require snapshot name, etc.

### ISSUE THREAD

**Issue by shaal** [drud/ddev#1886]
Snapshot is such a great feature, but very difficult to restore the correct one when multiple snapshots exist.

**Describe the solution you'd like**
`ddev create-snapshot` - creates a new snapshot
`ddev restore` - will jump to step 2 in the following option.
`ddev snapshots` - open CLI UI, 

Step 1
What would you like to do?
1. Create a new snapshot
2. Restore a snapshot

Step 2
If the user choose 'restore a snapshot', a scrollable list of 5 latest snapshots will appear with a human display of date/time. The user can go up/down and choose the snapshot to restore.

**Comment by rfay** [comment]
What I always do is name the snapshot, with `ddev snapshot --name=<something>` and that helps. But I agree that listing snapshots and making them more available would make things easier. I don't probably agree with a stack approach like you suggested, as that's pretty obtuse for lots of less-computer-sciency people.

**Comment by shaal** [comment]
Can we add to 'create snapshot', that it will always ask for a name, but when user doesn't provide a name and hit enter, it will get by default the date/time stamp ?

**Comment by rfay** [comment]
Sounds reasonable, although a change of behavior.

**Comment by WarpedOne** [comment]
The problem with `create snapshot` prompting for a name is scripting. Do you really want a script pausing for a name? That is not a standard UI practice.
For restore, if a sequence (ex. sitename_001_20191014-152104) with auto-complete would make it easier to select, even by last created.
Just some ideas.

**Comment by rfay** [comment]
We were talking about the idea if you *didn't* give --name, then it would prompt.

**Comment by MrPaulDriver** [comment]
I like the other suggestions and think it would also be helpful if a command was available which restored the most recent snapshot.

Something like `ddev restore-snapshot -latest`

**Comment by chellman** [comment]
I'd certainly like to see some enhancements to snapshots.  I agree with @WarpedOne that pausing for a name by default isn't ideal, so keeping the current behavior where not providing a name results in the creation of a new, default-named one seems fine.

I would like a way to list snapshots, as `snapshot --list` or the like, and for `restore-snapshot` called with no options to list the snapshots that are available, instead of telling me to list them myself (not that doing so is a great hardship, it would just be better UX).

I would also like `restore-snapshot --latest` as @MrPaulDriver mentioned.

**Comment by cmuench** [comment]
@chellman I will try to add the `--latest` option to the command.

**Comment by chellman** [comment]
@cmuench I just looked through the work over on #2724, and it looks great! Thank you!

**Comment by rfay** [comment]
Hoping you'll try out v1.17.0-alpha3 and give your feedback!
