### ISSUE TITLE
ddev dont update   ssl https mkcert certificate

### ISSUE THREAD

**Issue by AlexOwlCode** [drud/ddev#1924]
I have ddev Drupal 8 project.

i have created  with mkcert first   a  certificate with mkcert-install

after i create a certificate  with other andress allowed 

mkcert -install   {old andress}  new andress1  ...

but ddev dont refresh the certificate

**Comment by rfay** [comment]
So you don't create the cert. 

You do `mkcert -install` one time, and that sets up a trusted CA for your system and browser. Then after that, if you do a `ddev poweroff` (so that the ddev-router picks up the new info on start) and then do a `ddev start`, all projects after that should have trusted https. 

It may be that you didn't do the `ddev poweroff` so that the ddev-router got reset? Just a one-time thing. But you don't run anything like "mkcert -install {old andress} new andress1" ever. Just that one-time `mkcert -install`.

If you're still having trouble after `ddev poweroff` and `mkcert -install` and `ddev start`, please let me know what operating system and browser you're using.

**Comment by AlexOwlCode** [comment]
I'm using windows 10 : 
I  have notice: C:\Users\****\AppData\Local\mkcert   *pem file don't update  when create new mkcert with new  address and ip .

However  i  need to use a certificate with  No default address , because i want that some people can  connect to my  web site machine for a demo (i have edit my docker file 127.0.0.1 to 0.0.0.0) and disable firewall.

However when try to connect  https with firefox i have two error 
1) SSL auth not recognized (ok it's self signed)
2) **the name of the web site and  address of certificate it not right , but i have build  it  with  also this address!!**

**Comment by rfay** [comment]
So ~/Appdata...mkcert is not a certificate, it's a CA. It doesn't get updated when you use mkcert to make a cert. And for usage with ddev, there's never a reason to create a cert using mkcert. 

If you want people to connect to your machine for a demo, I strongly recommend using `ddev share` (uses ngrok) instead. It's way better. But if you have to install the *CA* on their machine, you do it using this technique: https://github.com/FiloSottile/mkcert#installing-the-ca-on-other-systems

Also please note that firefox is not supported by mkcert on WIndows, see https://github.com/FiloSottile/mkcert#supported-root-stores

**Comment by rfay** [comment]
Hoping that you got past this and are having success. Happy to continue the conversation. 

BTW, since your post new documentation was added about how to deal with Firefox on Windows, https://ddev.readthedocs.io/en/latest/#windows-and-firefox-mkcert-install-additional-instructions

Closing, but happy to continue the conversation here.
