### ISSUE TITLE
Readiness Check for Drupal Automatic Update returns errors running on DDEV

### ISSUE THREAD

**Issue by rpkoller** [drud/ddev#1929]
**Describe the bug**
I tried the Automatic Update Module out of curiosity locally with DDEV. I am uncertain if it is intended that it should also work and be testable in local environments but I gave it a spin a few minutes ago and it returned the following errors: 

![Bildschirmfoto 2019-11-08 um 11 40 31](https://user-images.githubusercontent.com/1665422/68472354-9a59b200-0220-11ea-8243-2e3784ee06ba.png)

**To Reproduce**
1. Install `https://www.drupal.org/project/automatic_updates`

**Version and configuration information (please complete the following information):**
 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.11.2
commit            	v1.11.2
db                	drud/ddev-dbserver:v1.11.0-10.2
dba               	drud/phpmyadmin:v1.11.0
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.11.0
docker            	19.03.4
docker-compose    	1.24.1
os                	darwin
router            	drud/ddev-router:v1.11.0
web               	drud/ddev-webserver:v1.11.0
```

**Comment by rfay** [comment]
As far as I can tell all of those complaints have to do with what you have set up in your site, right? I don't think it  has anything to do with ddev.

**Comment by rpkoller** [comment]
hmmm the permissions for the vendor and core are identical on my computer and inside the container. guess I will post that ambiguity on my side to the modules maintainers issue tracker (they asked for feedback anyway. ;) ). But in regards of the insufficient space error i thought that it  isn't based on the setup of my site but it sounded more like that there is not enough space in the container left? which is more in the field of DDEV? Am not sure if it would be possible at all to alter and adjust anything in that regard in any config file?

**Comment by rfay** [comment]
So "space in the container" is about Docker. If you're on macOS you'll want to bump the file space allocated, check that. 

I guess I was reacting to the hash complaints, which are just warnings.

Are you running on Windows?  Both macOS and Linux mount into the container with the regular user privs, so I'd expect vendor to be writable. But Windows can't do that due to big differences in user ids. 

You're running 8.9.x for this test?

**Comment by rfay** [comment]
You should definitely `ddev ssh` and inspect the permissions in there. `ps -ef` will show you the php-fpm and nginx processes, you'll see them running with your UID. 

You may want to `chmod -R u+w /var/www/html` either on the host or in the container. Anyway, that's the direction to be looking.

**Comment by rpkoller** [comment]
I am running on MacOS 10.13.6. And as I already mentioned above the permissions are identical. I already ssh'ed into the container already there before: 
```
drwxr-xr-x  44 myuser  staff  1408  8 Nov 11:13 core  (My System)
drwxr-xr-x 44 myuser myuser 1408 Nov  8 10:13 core (Container)

drwxr-xr-x  53 myuser  staff    1696  8 Nov 11:13 vendor   (My system) 
drwxr-xr-x 53 myuser myuser   1696 Nov  8 10:13 vendor (Container)
```
Checked also the `ps -ef`inside the container as you suggested and it also shows `myuser`as UID. Will investigate later. Am a few hours afk now unfortunately. Also will check in regards of the file space allocation for the container. Thanks for the heads up in that regard!

**Comment by rfay** [comment]
Ah, I tried it and read more carefully. It's looking in the wrong place for these things, at least on a drupal-composer build. Here's the message:

`Your site is currently failing readiness checks for automatic updates. It cannot be automatically updated until further action is performed:
Drupal core filesystem at "/var/www/html/web/core" is read only. Updates to Drupal core cannot be applied against a read only file system.
Vendor filesystem at "/var/www/html/web/vendor" is read only. Updates to the site's code base cannot be applied against a read only file system.
Vendor filesystem "/var/www/html/web/vendor" has insufficient space. There must be at least 10 megabytes free.`

1. It's looking for vendor in web/vendor, the wrong place. Should be looking in /vendor, not /web/vendor
2. Apparently it's reporting as "inadequate space" because the directory doesn't exist (/var/www/html/web/vendor)

Then the report of ""/var/www/html/web/core" is read only" is just incorrect, it's easy to see. All the files in there are writable, as is the directory. You can demonstrate it by just `touch /var/www/html/web/core/junk.txt`, succeeds just fine.  On macOS or Linux, you're doing this as the same user that's running web daemons (use `ps -ef` to see that, and the files are all mounted with that privilege.

#1 and #2 are https://www.drupal.org/project/automatic_updates/issues/3093028 - @heddn reports that composer based workflows are not supported. So since this is D8... I'm not sure what workflows are supported. 

> You'll need to test this on a site that was installed using tarballs

**Comment by rfay** [comment]
And... with a tarball of drupal 8.7.9...

<img width="807" alt="Automatic_Updates___Site-Install" src="https://user-images.githubusercontent.com/112444/68530750-836e9a80-02c8-11ea-8bb0-d2db44717b4f.png">

**Comment by heddn** [comment]
Thank you @rfay and @rpkoller for your valuable feedback here. It is sad that a more fully composer-based workflow isn't currently supported in `automatic_updates`. I'd really like to see that change.

For now, I've opened https://www.drupal.org/project/automatic_updates/issues/3093700 to address the user experience of installing the module so 1) we fix the errant errors and 2) we make it more obvious what workflows are and are not supported.

**Comment by rfay** [comment]
I'm going to close this for now, since it's all about automatic_updates, not ddev. Happy to continue the conversation here though. Thanks for checking in @heddn and congrats on the good work in automatic_updates.
