### ISSUE TITLE
Add config.yaml option to disable creation/management of settings files

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2024]
**Is your feature request related to a problem? Please describe.**

Many (most?) advanced developer teams want to manage CMS settings files themselves. ddev's approach is to create the CMS-type's settings files (and .gitignores, etc) to make things easiest for most people. But teams with specific workflows tend to react badly to this. They have the option, of course, of using the "php" project type, which turns off all that behavior. The problem with that is then they don't get the nginx config which is tailored to their CMS. 

We could have an option `disable_settings_management: true` or something like that.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gilbertsoft** [comment]
Interesting feature imho!

**Comment by Azovsky** [comment]
This option will be very useful.

**Comment by opdavies** [comment]
Rather than removing in completely, what about making the site names configurable via a list?

Something like`site_directory_names: [default]` could be the default setting which would have the same functionality as does now, but you could override it to something like `site_directory_names: [foo, bar]` if you're working on a multisite without the default site directory? It would still be beneficial to generate settings files within those directories.

**Comment by cweagans** [comment]
We would definitely use this flag if it were available to us.

**Comment by rfay** [comment]
Hope you can test this out and see if you like it in prerelease (edge) https://github.com/drud/ddev/releases/tag/v1.13.0-rc1
