### ISSUE TITLE
Allow global homeadditions configuration

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2055]
**Is your feature request related to a problem? Please describe.**

The homeadditions feature is nice, allowing people to add things that will always be added to theeir home directory. But they have to add it explicitly to each project. It would make more sense to also copy from (suggested: ~/.ddev/homeadditions/

Decisions will have to be made about collisions between global and project config.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewbelcher** [comment]
I think this is a great idea and `~/.ddev/homeadditions` seems a sensible place. In terms of collisions, I'd be inclined to suggest simply use the project specific version if there is a collision.

The biggest use case I can see for this is `.gitconfig` which I keep forgetting to add and end up commiting as `DDev user` :rofl:

**Comment by FamousWolf** [comment]
We'd also use this for a global ~/.composer/auth.json. We need it for just about all projects we have (almost 200 now) because we use a private composer repository for our own developed TYPO3 extensions and on some the ELTS repository for TYPO3.

I agree about the collisions. It would be handy if you can override the global files in certain projects. So if a file is both in global and project homeadditions it should use the project.

**Comment by Mon-Tea** [comment]
I'd like to have this feature for simple aliases and complex bash-functions, that makes my life easier.

It makes more sense to me, that I configure that once and not for each project again.
