### ISSUE TITLE
Organize DDEV-Local Advisory Group

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2057]
We'd like to organize a group of advisors who are regularly involved with DDEV-Local and have different perspectives so that we get regular feedback about the product and wide input for roadmap planning. 

The goals are pretty simple:

* Get input from a variety of people who are invested in DDEV-Local to help maintain the roadmap in a way that meets community needs.
* Encourage those people to always communicate the needs/problems/wants of their teams and what they hear from others. 

What we're envisioning at this point is just a simple online meeting quarterly, either Zoom or the like or even an asynchronous Slack or Discord or gitter meeting.

**Comment by RobertLang** [comment]
You can count me in :-)

**Comment by cyberswat** [comment]
It would be nice if the people that are intrested in participating could help us understand the CMS that they are interested in representing. Ultimately, we'd like to encourage representation from several CMS communities.

**Comment by andy-blum** [comment]
I'd love to contribute! I use ddev for Drupal (mainly 8, soon 9).

I don't have tons of knowledge of the nitty gritty backend or devops stuff but I do use ddev daily.

**Comment by jcnventura** [comment]
I also would love to contribute. Mainly using Drupal 8. Was using Lando before, and I admire it's simplicity in adding services.

Would love to see if we can simplify DDEV-Local through the use of recipes for different services, where DDEV ifself would take care of grabbing the recipe from an upstream repo.

Ah, and local DDEV config overrides so that Mac users can just have NFS permanently enabled regardless of what the project config says.

**Comment by leymannx** [comment]
@jcnventura – You can put a `config.local.yaml` into your `.ddev` folder containing `nfs_mount_enabled: true` or `false` to override the global config. This `config.local.yaml` is already exclude in the default `.gitignore`.

**Comment by jcnventura** [comment]
@leymannx That's interesting. Can we make it run from a  ~/.ddev/config.global.yml file so that developers don't have to add that file to all projects (we have a lot of ddev projects).

**Comment by rfay** [comment]
Please spin off separate discussions, thanks. For global nfs config, you probably want to say "me too" on https://github.com/drud/ddev/issues/1985

**Comment by truls1502** [comment]
I also would love to contribute use it for daily and work need.

**Comment by deviantintegral** [comment]
Glad to see this happening! We just kicked off a "Local Container Development Environment" working group at Lullabot to operate over the next three months. We're evaluating both local environment tools (ddev, lando, docker-compose, etc) as well as Docker support on non-Linux hosts (Docker Desktop, lima, etc). We're still in the information gathering phase, but should we end up using ddev on more projects we will want to support the project more formally in some way.

**Comment by cmuench** [comment]
@rfay Hi. I am interested to be part of the advisory group. I can also be the "Magento" part here.

**Comment by rfay** [comment]
You already are of course :) But thanks!

**Comment by rfay** [comment]
Thanks to all of you for participating in this issue and volunteering, some of you so very long ago. 

I'd love to do a zoom next week, sometime that works here in Colorado and also in Europe. Would it be possible to meet at 8am US MT, 4pm CET, 1400 UTC on Wednesday October 27?  https://www.timeanddate.com/worldclock/fixedtime.html?msg=DDEV+Advisory+Group&iso=20211027T08&p1=2223&ah=1

Thanks for being willing!

**Comment by rfay** [comment]
The month has been getting away from us. I don't think that the last Wed or Thurs of the month will work this month, because they're both Thanksgiving holiday in the US. But I wonder if we could stretch things and do it on Wed, December 1, 2021, 9am US MT, 5pm CET, zoom link to be provided later. (Apologies to those in Australia/Japan/etc. Will try to at least turn on the recording this time.)

Agenda items:
* Status of DDEV's github repo, finish discussion of what org to move to.
* Status of DDEV trademark and discussions with Fruition about it, possible need to change name (and how much would have to change)
* Creation of budget subcommittee

Could you each please PM me your email address so I can do a calendar invite to everybody?

**Comment by Lefaux** [comment]
I would advise against using Slack for a new community hub.
Slack is a temporary solution because once the community becomes too big, Slack will ask you to move off their platform eventually.

We're currently in planning phase to get 8k people off Slack and I have to say... it's not pretty :)

**Comment by cmuench** [comment]
@Lefaux Can you recommned a platform?

**Comment by andy-blum** [comment]
@Lefaux I'd be extremely hesitant to move away from slack. It's the de facto hub for distributed async discussion and I know that I wouldn't likely keep a new chat application open when my agency chat, client chat, and open source communities chat are all already on slack.

**Comment by rfay** [comment]
This is an important discussion - Why not open a new issue for it?

**Comment by Lefaux** [comment]
@cmuench hard to tell, because a lot comes down to preference.
We will be moving to Discord for a few reasons:
* Risk of Slack moving us off their platform unannounced or on short notice is too high
* Slack does not offer specific support for OSS communities, so you're stuck to the free plan which is very limited
* Slack doesn't scale well beyond about 1k users (not in terms of performance, but in terms of managing those users)
* Slack isn't built for communities, we currently spend around 30 hours per month cleaning up stuff because of Slack's philosophy (which is a great philosophy for teams, don't get me wrong)
* We needed integration with our LDAP for TYPO3 so we can assign group membership at a central place
* Discord is built for communites from the ground up
* Discord is widely used in both OSS projects as well as the gaming world and other communities
* Discord works by having ONE account for any Discord server - easier to stay in touch across communities, so manual invites necessary (which is ultra PITA in Slack)
* Discord offers multiple easy ways to show "status" within the community - this is not about braging, more about who does what
* Discord has persistent voice channels, making it easier to engage with people from the community you don't yet know by simply hanging out without any specific reason
* Discord has a scalable business model that does not rely on DDEV paying money, but rather the users paying to "boost" the Discord communities they like (plus the all-out boost are about $400/year, so it's VERY affordable.
I'm not saying Discord is the best solution for everyone, I'm just trying to explain why it fits TYPO3 best.

**Comment by BrianGilbert** [comment]
> @Lefaux I'd be extremely hesitant to move away from slack. It's the de facto hub for distributed async discussion and I know that I wouldn't likely keep a new chat application open when my agency chat, client chat, and open source communities chat are all already on slack.

I only have 2 work related Slacks, vs the other systems I need to use for work which far outweigh Slack

- WhatsApp
- Discord
- Rocket Chat
- Facebook Messenger
- Skype

May I alert you to the existence of Ferdi Multi IM messenger https://getferdi.com/

**Comment by cmuench** [comment]
@Lefaux Thanks for sharing your thoughts.

**Comment by rfay** [comment]
Calling this one done. We now have regular meetings and are moving forward.
