### ISSUE TITLE
vim+xdebug pretty please

### ISSUE THREAD

**Issue by ahillio** [drud/ddev#2113]
One day in my diy local LAMP stack I eventually (after much toil) got xdebug working inside Vim using the Vdebug plugin.  But it crashes.  And my LAMP stack has PHP7.0 installed.  And both of these issues with my DIY hack-it-together dev environment could and should be solved by my Docker and DDEV toolkit... right?

Could you please provide a Vim that's already configured to work with Xdebug?  Pretty please?

**Comment by rfay** [comment]
I guess you want https://github.com/vim-vdebug/vdebug to work on the host with ddev right? 

You're not currently using vdebug? But you use vim on the host?  What OS do you use? 

Our xdebug is configured by default to interact with tools like PHPStorm and vscode on the *host*.

**Comment by rfay** [comment]
AFAICT Vdebug works out of the box using ddev. 

* On the host (mac or Windows or Linux) install vim and install the Vdebug plugin.
* Start your project
* `ddev exec enable_xdebug`
* In vim, `:VdebugStart`
* Visit your project in a web browser. 
* Vdebug wakes up (slowly) with "Found connection, starting debugger". 

I tested this on macOS, and don't actually know how to use Vdebug, but it works just like every other debugger IDE I've tested. per https://ddev.readthedocs.io/en/stable/users/step-debugging/#step-debugging-with-ddev-and-xdebug

If you wanted to do this with vim inside the web container, you'd want to 
* Add the vim-nox package by adding `webimage_extra_packages:[vim-nox]` to your config.yaml
* install the plugin in there (you can do this by putting it in .ddev/homeadditions/.vim and it would be installed for you on every start. 
* Override the PHP configuration for xdebug.remote_host in a .ddev/php/xdebug.ini with 

```
[PHP]
xdebug.remote_host=127.0.0.1
```
* `ddev exec enable_xdebug` (or just `enable_xdebug` within the container)

I was not able to get this going inside the container because Vdebug always reported errors when starting vim:
```
$ vim
Error detected while processing function Vdebug_load_options[8]..<SNR>42_DefineSigns:
line    1:
E239: Invalid sign text: �~V�
line    2:
E239: Invalid sign text: �~V�
line    3:
E239: Invalid sign text: �~V~L�~V~L
Press ENTER or type command to continue
```

But... you can explore and I'm sure you know far more about it than I do. 

And... You're really, really like a full IDE like PHPStorm or vscode. They're worth their weight in gold. I imagine you are very partial to vim (and I'm a vim user since 1990) but I very much doubt that you wouldn't fall in love with a real IDE for debugging.

**Comment by cweagans** [comment]
FWIW, VSCode has excellent vim keybindings. I switched about a year ago and haven't looked back.

**Comment by rfay** [comment]
No response from OP, but the basic fundamental usage of xdebug works fine with vim with vdebug. Closing for now, happy to continue the conversation here or elsewhere.

**Comment by benjifisher** [comment]
As usual, @rfay, your support goes above and beyond what we have a right to expect.
 
+1 for Vdebug. There are some older plugins to get Vim to work with Xdebug, but this is the right one to use IMO.

From the project page:

> **Requirements**:
> 
> - Vim compiled with Python 3 support, tabs and signs (for Debian/Ubuntu this is provided in the vim-nox package)

From the notes in the earlier comment (Thanks for the detail!) it looks as though the version of Vim installed on DDev was not compiled with signs. The version used now ("Huge version without GUI" according to `vim --version` on the container) does not have that problem.

The link in the earlier comment is stale. Try this instead: https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/. According to that, the way to enable Xdebug is `ddev xdebug` or `ddev xdebug on`.

Another point from that doc:

> This was port 9000 through DDEV v1.18, changed in v1.19+ to port 9003.

Vdebug has not been updated recently, so it defaults to the old standard, `:9000`. For a quick test,

```
:VdebugOpt port 9003
```

will set the correct port for the current session.

The last part of configuration is to map the paths on the DDev container to paths on the host. For the current session, this works:

```
:let g:vdebug_options.path_maps = {'/var/www/html': '/home/benji/Sites/drupal'}
```

I will have to think of a convenient way to set it up so that I can switch between projects.

The advantage of running Vim+Vdebug on the container instead of the host is that you can skip the `path_maps` configuration.

It has been a few years since I have used Xdebug. I had forgotten how much fun it is!

**Comment by rfay** [comment]
Do you know the name of the debian package you want for vim? If so, just add it to `webimage_extra_packages`... Then when you get Vdebug going, you can make a DDEV add-on for those that want to use it?

**Comment by benjifisher** [comment]
> Do you know the name of the debian package you want for vim?

The version that DDEV currently uses is fine. I do not think I customized this:

```
benji@drupal-web:/var/www/html$ dpkg -l vim* | grep ii
ii  vim            2:8.2.2434-3+deb11u1 amd64        Vi IMproved - enhanced vi editor
ii  vim-common     2:8.2.2434-3+deb11u1 all          Vi IMproved - Common files
ii  vim-runtime    2:8.2.2434-3+deb11u1 all          Vi IMproved - Runtime files
benji@drupal-web:/var/www/html$ vim --version | head -1
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
benji@drupal-web:/var/www/html$ vim --version | grep sign
+diff              +mksession         +signs             +writebackup
```

I will at least make a PR for the docs. (The IDEs on https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/ are listed alphabetically, right?) If I can find time, I will try to make a DDEV add-on. I guess we want it to

1. Install Vdebug.
2. Provide a command to toggle `xdebug.remote_host`. Or maybe add an option to `ddev xdebug`.

**Comment by rfay** [comment]
I would imaging just changing the default port is all that would be required, and that's already covered.  I don't know why you'd change `ddev xdebug`. 

In a PR for the docs it would go last, thanks.

**Comment by bfcmaintenance** [comment]
you can use `jq` to get the approot and automatically set `g:vdebug_options.path_maps`:

    let ddev_approot = system("ddev describe -j | jq '.raw.approot'")
    let g:vdebug_options.path_maps = { '/var/www/html': ddev_approot }

if you are not in a ddev dir it will fail silently.
