### ISSUE TITLE
export-db should have a sensible default

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2192]
**Is your feature request related to a problem? Please describe.**
Running `ddev export-db` with no flags or output path begins a chaotic, unreadable output to the terminal

**Describe the solution you'd like**
Running the `export-db` command should have a more idiot-proof default like exporting the database to [project-root]/[timestamp]-[project-name].sql

**Describe alternatives you've considered**
- I prefer my sql dumps compressed, so maybe also gzip by default
- another option would be to default to the `export-db -h` output

**Additional context**
<img width="921" alt="Screen Shot 2020-04-17 at 12 19 06 PM" src="https://user-images.githubusercontent.com/25532785/79590894-c453b200-80a5-11ea-9337-9fc193ae87b5.png">

**Comment by rfay** [comment]
It is gzipped by default, that's why you see what you see. 

I would certainly be hesitant to change the current setup, as it's been this way for loads of releases and people have scripts built around it. 

The reason it outputs to stdout is that's how lots of things do, like mysqldump, or `mysqldump | gzip`

But I'm sure you're not the only person to have felt uncomfortable with this. What is "sensible" definitely depends on point of view and previous tool usage though.

**Comment by rfay** [comment]
So basically `ddev export-db` has a default which is sensible to at least some people, and it wouldn't do to change what people are used to. `ddev help export-db` does explain the patterns that are available for it. And since v1.13, it also tells you what it did and what format it did it with. So I don't think I'm willing to mess with this at this time. Thanks for making the issue and for all your creative thinking though!
