### ISSUE TITLE
docker-compose.*.yml no longer supported After 1.14.0 update (use docker-compose.*.yaml)

### ISSUE THREAD

**Issue by Jesmaster** [drud/ddev#2217]
Just an FYI to anyone having this problem after doing the update.

Before 1.14.0 the extension `yml` was working for additional services.

For example in one of my projects I had `docker-compose.redis.yml`. 

After the update these services were not starting when I ran `ddev start`. I checked the docs to see if there was any kind of change to additional service and there wasn't. After trying a few things I eventually fixed it by renaming the file extension to `yaml` instead of `yml`. As far as I can tell this isn't documented anywhere. Not sure if this is intentional (but undocumented) or was an unintentional bug introduced in the new version.

**Comment by rfay** [comment]
That was intentional, but I'm really sorry it broke you. The docs were updated to only specify "yaml", but I didn't add anything to the release notes, I will do that now.

In the past, adding the complexity of supporting .yaml and .yml for no reason caused some unnecessary code complexity that led to an obscure bug, so when reworking services this round I just removed the .yml option; I'd never seen an example or heard of anybody using a .yml.

I apologize, and will make a note in the release notes.

**Comment by Jesmaster** [comment]
No worries, I'm a Drupal dev so I'm used to seeing/using yml rather than yaml.

I see the change you made to the docs.

**Comment by rfay** [comment]
I'm going to leave this open. Even though this was deliberate, it may be annoying enough to people to be a bug, so we'll see what people say.

**Comment by rfay** [comment]
@Jesmaster thanks so much for reporting this and pointing out why it's important to you. It will be in the next point release, in a day or two.
