### ISSUE TITLE
Bump mariadb default install to 10.3.x

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#2232]
Drupal 9 requires mariadb 10.3.7, the default 10.2.31 doesn't work.

Given there is likely not much harm in doing so, I think it would be useful to bump the default mariadb to 10.3.

**Comment by rfay** [comment]
We'd need to know what CMSs this might affect before doing it. 10.2 has been great for everything, until Drupal 9 decided at the last minute that 10.3 was a requirement.

Would 10.3 break any versions of TYPO3? WordPress? Magento? Magento2? Drupal 6 or 7? 

If we don't know, I don't really see the reason to move on and change the default.

TYPO3 v7 and below have long had trouble with MariaDB 10.2, so those folks always have trouble and have to use 10.1. And, of course, the results are very obscure and only a person in the know would ever be able to "read" them.

**Comment by rfay** [comment]
For the reasons above (https://github.com/drud/ddev/issues/2232#issuecomment-622553095) this isn't going to happen at this point.

**Comment by mvance** [comment]
I just finished installing [ddev on a Chromebook](https://ddev.com/ddev-local/ddev-docker-chromebook/); thanks @rfay!

I ended up here because I ran the `ddev config --project-type=drupal8 --docroot=web --create-docroot` command but surprisingly the site ended up being Drupal 9.0.2 instead of D8 and it won't let me complete the install process due to the Mariadb 10.3.7 requirement.

I thought I'd mention it here because the out-of-the-box experience for someone new to ddev is a bit confusing due to this issue.

**Comment by rfay** [comment]
Thanks for pointing out the problem with the article, @mvance. I'm confused why you're commenting here I guess, but I've just updated the ddev-on-chrome article to use the new (post-Drupal9-release) recipe. 

When Drupal 9 was released, it started being the default target of `composer create-project drupal/recommended-project`, so this is just a matter of time moving along in the tech world.

Since articles like this can always get out of date, it's important to look at the docs, especially the quickstarts, for the current best practice. See the [drupal 8 quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart) and [drupal 9 quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-9-quickstart)

**Comment by mvance** [comment]
Wow, thanks for the quick reply. I was just coming back to comment that using the following allowed me to install D8:

    ddev composer create drupal/recommended-project:8.9.2

...similar to your update to the article of:

    ddev composer create drupal/recommended-project:^8

I only commented here because it was the first place I landed when doing some searches around the issue and I thought others might land here as well. Thanks again!

**Comment by rfay** [comment]
Thanks! Yeah, when that article was written in December, drupal/recommended-project didn't work like that... and drupal 9 also didn't require MariaDB 10.3! It only changed its requirement at the last minute before release. Caused consternation for lots more than you. But in the meantime DDEV-Local got full Drupal 9 support and it automatically selects MariaDB 10.3 when you config for --project-type=drupal9.

**Comment by damienmckenna** [comment]
Might it be useful to change the database default for D8 to mariadb 10.3?

**Comment by rfay** [comment]
Reopening, hoping to bump default to 10.3 in v1.17 cycle.
