### ISSUE TITLE
Allow tab-completion for file path prompt in `import-db`

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2244]
**Is your feature request related to a problem? Please describe.**
When using `ddev import-db`, I have to manually type out or copy/paste the filepath because the prompt does not allow tab-completion

**Describe the solution you'd like**
Allow tab completion for filepaths

**Additional context**
![Screen Shot 2020-05-07 at 11 24 07 AM](https://user-images.githubusercontent.com/25532785/81313396-d1851080-9055-11ea-92d1-f9146f43af84.png)

**Comment by rfay** [comment]
Please use `ddev import-db --src=...` and you'll be happier!

I never use or recommend the prompted import. I didn't know anybody did!

**Comment by rfay** [comment]
No response from you @andy-blum, so closing, but I definitely recommend using the command-line version rather than the prompted version. `ddev import-db --src=/path/to/import.sql.gz` or `ddev import-db --src /path/to/import.sql.gz`. Both of those do autocomplete.

**Comment by alechko** [comment]
hi @rfay , I know that this is a closed issue but I'm having this problem as well, no command I try will allow me to complete the path or filename using tab.

I've tried `ddev import-db -f ...` and `ddev import-db --src ...`  and `ddev import-db --src=...`, none of them will allow me to autocomplete the path or filename with Tab.

Is there something I'm missing?

ddev v1.16.4
macos 11

![example](https://user-images.githubusercontent.com/1391846/105048598-6c067200-5a74-11eb-8150-f0be13752470.gif)

**Comment by rfay** [comment]
Have you [installed the autocompletion](https://ddev.readthedocs.io/en/stable/users/shell-completion/)? You don't mention whether you're using bash or zsh, or any details like that. Please explain the whole setup.

Bash autocompletion with `ddev import-db --src=<whatever>` autocompletion works fine for me (bash, homebrew autocomplete).  But.. even without autocompletion, this will work for you if you leave off the =, so `ddev import-db --src partial<tab>`

I note that your issue is completely unrelated to the original issue (prompted `ddev import-db` autocomplete) so please read carefully and open a new issue for a new problem.  Still, happy to follow up here or in any of the [support channels](https://ddev.readthedocs.io/en/stable/#support)

**Comment by rfay** [comment]
One other thing you might want to do is try ddev v1.17.0-alpha3, which does have some updates on autocomplete. https://github.com/drud/ddev/releases/tag/v1.17.0-alpha3

**Comment by alechko** [comment]
Thanks for the quick reply, apologies for leaving the shell details out, I'm on iterm2 with zsh.
I do have autocompletions installed and there's no issues for commands/subcommands autocompletion, only when trying to automcomplete the filename for `import-db`.
I thought it's related because I cannot get autocomplete both when using the `-f` or `--src` flags or when trying to use the `ddev import-db` without arguments.

**Comment by rfay** [comment]
Yeah, zsh autocompletion with or without = seems to work for me with latest, so https://github.com/drud/ddev/issues/2244#issuecomment-762894962

**Comment by alechko** [comment]
I've upgraded to the 1.17 version but the result is the same for me...

![Kapture 2021-01-19 at 17 05 06](https://user-images.githubusercontent.com/1391846/105052469-9823f200-5a78-11eb-9f40-a9523ac8cc7f.gif)

**Comment by rfay** [comment]
You don't say whether you use homebrew or not, whether you have the autocompletion set up as described in https://ddev.readthedocs.io/en/stable/users/shell-completion/#zsh-completion, whether you're using oh-my-zsh. So many things to consider with zsh. It's not easy.

**Comment by alechko** [comment]
I do use brew, but I cannot remember how I've setup the autocompletion, it was long time ago... :)
I will try to reset the autocompletion according to the guide you've provided and will report back as soon as possible!

**Comment by alechko** [comment]
Glad to report that it's working now!

I'm not sure how the previous completions worked, but as soon as I've installed `zsh-completions` and added it to my `.zshrc` everything started working fine!

Thanks!

**Comment by rfay** [comment]
Yay!
