### ISSUE TITLE
app.Down() behavior implements "remove"

### ISSUE THREAD

**Issue by rfay** [drud/ddev#228]
## What happened (or feature request):

I note that `ddev rm` is implemented in terms of Down(). Those are not the same semantics, and it would be a good thing to merge them.

## What you expected to happen:

I expect something that destroys data to be named "Destroy()" or "Remove()" or something like that. Not "Down()" which would seem to imply a stop.

## Related source links or issues:

**Comment by beeradb** [comment]
This is implemented as down because it directly maps to `docker-compose down` https://docs.docker.com/compose/reference/down/

That doesn't mean we can't change it, of course, but I'm more hesitant than I normally might be since it's mirroring compose language.

I do agree down was a crappy name for them to pick, though :)

**Comment by rfay** [comment]
Seems like a reasonable choice. Closing this for now. We may want to figure out a way to change this in the future.
