### ISSUE TITLE
On WSL2, Drush cannot be run because php (cli) is not found

### ISSUE THREAD

**Issue by karikaariainen** [drud/ddev#2363]
ddev is working fine, I can install Drupal 8 sites, but Drush doesn't work.

```
kari@mymachine:/var/www/html/drupal8$ vendor/bin/drush
/usr/bin/env: ‘php’: No such file or directory
```
Yes, it really prints those nice looking single quotes.

Trying just php does this:
```
kari@mymachine:/var/www/html/drupal8$ php
Command 'php' not found, but can be installed with:
sudo apt install php7.4-cli
```

Drush was installed with Composer:

```
ddev composer require drush/drush
Using version ^10.3 for drush/drush
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
```

Windows 10 Pro
WSL2, Ubuntu-20.04 repository.

Docker Desktop version 2.3.0.3. (45519)
ddev version v1.14.2
config.yaml:
```
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
```
No custom configuration.

**Comment by rfay** [comment]
I can't recreate your problem. What you're saying is that the php cli isn't installed, which it very much is. 

It looks like you might be running commands on the WSL2 side instead of inside the container? What does `ddev exec php --version` say, or `ddev exec drush status` ?

If you did a `ddev composer install` or a `ddev composer create` to make your Drupal8 site (as with the Drupal 8 quickstart, https://ddev.readthedocs.io/en/stable/users/cli-usage/#drupal-8-quickstart) then that requires the php cli to work, so... I think there must be something about your context that throws this off. Maybe you've added to homeadditions and changed the path?

**Comment by karikaariainen** [comment]
"It looks like you might be running commands on the WSL2 side instead of inside the container?" Exactly! I didn't realize I needed to still go inside the container with `ddev ssh` or use `ddev exec`. Thank you!

**Comment by rfay** [comment]
From your examples, it looks like you're working in /var/www/html/drupal8 on the WSL2 side (on the "host" in this case). 

I really don't recommend that. You'll want to work in your home directory, so probably /home/kari/sites or something like that.
