### ISSUE TITLE
Create a basic performance test script for ddev

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#238]
## What happened (or feature request):
Per #195, we would like a consistent and repeatable way to test performance of several key operations on our supported CMS.

## What you expected to happen:
I propose that a script be added to the ddev project that can be run at an ad-hoc basis from desktop systems. I am thinking this could be a bash script that downloads d7, d8, and wp, and for each of them output the time to perform the following operations:

- `ddev start`
- `curl http://sitename.ddev.local`
- `drush site-install` / `wp core install`
- `curl http://sitename.ddev.local` after install
- `drush pml` / `wp plugin list`

I don't feel like we should pursue this as part of our automated testing for the following reasons:
- I believe our performance concerns are largely surrounding Mac and possibly Windows, since we are dealing with a virtualization layer in both scenarios (and these are larger market shares than desktop Linux).
- Our automated testing uses a linux-based VM in the cloud, which we experience a fair bit of variance in our test run times
- An approach such as running a bash script should be adaptable for testing other products, which should help us gain metrics in a consistent way. It's also unlikely we want to take on and maintain testing other products on a routine, automated basis.
- I'm not certain how long collecting these metrics will prove beneficial to us. This is not to say this should be all we do for performance, but I expect future performance concerns will be more focused, and should have before and after results captured for solutions to them.

## Related source links or issues:

**Comment by rfay** [comment]
I think you make a good point that linux metrics on the random containers we see on CircleCI are questionable for the reasons you state. However, it would be worth *considering* a technique that would notify us if there were a major change in performance characteristics due to our code. There are certainly major differences in behavior among the various platforms, and Mac and Windows are more valid concerns than Linux (where we typically test). However, if we make a mistake that increases load times or start times, that would likely show up proportionately on all environments unless it was a docker deviation.

In https://github.com/drud/ddev/issues/256 I proposed a more complete (and probably longer-term) set of tools that would aim higher and cover authenticated situations and more complex page loads. 

However, the tool suggested here is a great start, and we're more likely to implement it in the short run..

**Comment by rickmanelius** [comment]
@rfay left a comment in the PR, but I wanted to pull it back into the main issue. There is a further desire to create scripts to help automate testing, particularly as it pertains to authenticated users https://github.com/drud/ddev/pull/264#issuecomment-304929161.

**Comment by rickmanelius** [comment]
All PRs closed. Closing this one!
