### ISSUE TITLE
ddev config did not properly set required settings in existing project

### ISSUE THREAD

**Issue by jennypanighetti** [drud/ddev#2392]
**Describe the bug**
`ddev config` with project type of `drupal9`, when ran in a folder which had a previous project type configured, did not fully set up the config.yaml with the proper drupal9 requirements.

**To Reproduce**

1. Run `ddev config` and accept defaults for a PHP project type.
2. Later, run `ddev config --project-type=drupal9 --docroot=web --create-docroot` and finish installing Drupal and Composer
3. After launch, use the web UI to install Drupal with the _minimal_ profile.
4. An error will appear, "The database server version 10.2.32-MariaDB-1:10.2.32+maria~bionic-log is less than the minimum required version 10.3.7."

**Expected behavior**
The .ddev/config.yaml file should include `mariadb_version: 10.3` from the drupal9 configuration type, but there was no mariadb_version key present.

**Screenshots**
![drupal 9 install error from ddev launch](https://user-images.githubusercontent.com/2882837/87825731-7da06000-c82c-11ea-8871-a003e8d2d781.png)

**Version and configuration information (please complete the following information):**

-  macOS Catalina
- Docker Desktop 2.3.0.3
- ddev version v1.15.0
- config.yaml file is attached. Note that I had to un-comment line 45 to get it to work.
[config.yaml.txt](https://github.com/drud/ddev/files/4939914/config.yaml.txt)

**Comment by rfay** [comment]
Thanks so much Jenny - I'll try to replicate that.

**Comment by rfay** [comment]
Thanks, I can confirm these results. The 
> You have specified a project type of drupal9 but no project of that type is found in /Users/rfay/tmp/j3/web

is not the issue, the issue is that ddev is respecting the existing settings for mariadb_version (the default 10.2). 

This is related to https://github.com/drud/ddev/issues/1919, which is essentially requesting *this* behavior. 

I'm not entirely sure what the correct resolution is here. Of course, `ddev config --project-type=drupal9 --mariadb-version=10.3 --create-docroot --docroot=web` would work. 

In a perfect world, `--project-type=drupal9` would definitely reset the mariadb_version to 10.3. 

But... Drupal 9 also works with mysql 5.7 and 8.0. And mariadb 10.4 and 10.5. So we wouldn't want it to be changing it if it were set to one of those. 

So maybe? this is already correct behavior?

**Comment by rfay** [comment]
I'm going to say this is as good as we can get on behavior, but I sure appreciate you pointing out what happened here. Will continue thinking about it as well.

**Comment by pcambra** [comment]
I was able to reproduce this with the following setup:

- Ubuntu 20.04
- Drupal 9 installed via composer with` composer create-project drupal/recommended-project drupal9` as per https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies
- ddev config to have composer
- composer install
- ddev config again
- Install via UI the umami demo, the mariadb error appears in the installer

**Comment by rfay** [comment]
So the problem is that the existing .ddev/config.yaml is configured for mariadb 10.2, right? Then you configure it for drupal9, which requires 10.3, but it respects the existing 10.2 setting?

**Comment by pcambra** [comment]
I think yes, the first time I configure as "php" (default setting as I only have a composer.json file), second time I configure as "drupal 9" (again default setting) and it seems it doesn't update the setting. But I'm not sure if it should even, I thought reporting it in case is relevant.
