### ISSUE TITLE
Router always forwards to HTTP, even if connected via HTTPS

### ISSUE THREAD

**Issue by mkrauser** [drud/ddev#2438]
**Describe the bug**
The router always forwards the requests to port 80 of the web-container. 

**To Reproduce**
e.g. define some rewrite-rules just just for SSL, they will be ignored.

**Expected behavior**
I guess this can be seen as feature, not a bug, because the current solution is a bit faster. 
But if you have special directives (e.g. rewrite-rules) for the ssl-version of your site (which is not that uncommon), this behaviour breaks the site. 

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version: 2.3.0.4
- ddev version: 1.15.3
- config.yaml contents for the misbehaving project: nothing special
- custom apache vhost, with rewrite-rules just for SSL

**Comment by rfay** [comment]
Hi @mkrauser - This is by design. The https web-container configuration is only for direct access to the container, for people who need that for some reason. I actually am not sure I've ever known anybody to need it. 

But this design, a reverse proxy (ddev-router) terminating https and forwarding requests via http is super standard in server environments, and I don't see any particular reason to change it.

Can we talk about the problem you're actually trying to solve?

**Comment by rfay** [comment]
Happy to continue the conversation, but this was always the design of the system, with http being used behind a reverse proxy that did TLS termination. Direct https was added to the direct-bound port as a convenience for certain types of testing.

**Comment by mkrauser** [comment]
Sorry, I overlooked your first message. I encountered this problem while working on a legacy project. I worked my way around that.
You are right, terminating SSL at the LB is standard and I guess this is not a very common requirement.
