### ISSUE TITLE
Network ddev_default is external

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#2463]
Not a bug report, only a question. Several times, in various things, I've seen the statement

`Network ddev_default is external, skipping `

I've hunted around, but I've not been able to find anything saying what that is. It doesn't seem to be causing any problems, but I'm unclear what ddev is telling me.

**Comment by rfay** [comment]
I've been ignoring that for years :) Maybe now I'll have to go figure out what it means. It's output from docker-compose. Looks like https://stackoverflow.com/questions/36319613/docker-compose-down-network-is-external-skipping

**Comment by rfay** [comment]
Here's what it all seems to mean!

The `ddev_default` network is a default network created and used by all ddev projects. By default, only services (containers) in the same docker-compose file could communicate with each other. 

However, the `ddev_default` network is declared as "external", which means that docker-compose shouldn't take responsibility for deleting it when a project is being stopped. That would lead to an error if more than one project were running, because you really should not delete another project's network.

That's why it says it's "Skipping", and it says it once for each service in the docker-compose files that are being executed.

Thanks for bringing this up and making me chase it down!

I think the best resource for this is https://docs.docker.com/compose/networking/, but the reference is also good, https://docs.docker.com/compose/compose-file/#network-configuration-reference
