### ISSUE TITLE
"internet connection not detected": Improve warning, perhaps only do on start

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2578]
**Describe the bug**

The "internet connection not detected" warning when commands are issued is confusing to people, because they think it's an error.

1. The verbiage can be improved to say "warning: internet connection not detected"
2. Shouldn't the check only happen on `ddev start`, where we need to know because we need to add hostnames to /etc/hosts?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Catalina]
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version information (use `ddev version`)
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by therobyouknow** [comment]
Thank you for opening this ticket @rfay 

Please could  you check what output stream this warning is using. I'd perhaps suggest using stderr if not already, if that helps avoid the MySQL error I saw during import, as described here: https://github.com/drud/ddev/issues/2409#issuecomment-715911745

**Comment by rfay** [comment]
I don't know how this could affect an import if it were wrong, but it sure could affect an export. Is that what happened. 

It also wouldn't happen if you used `ddev export-db --file` instead of `ddev export-db >something.sql.gz`, so that's a good workaround.

The code is at https://github.com/drud/ddev/blob/2257122e054dbf16f7389aef5228dc991275ff0a/pkg/globalconfig/global_config.go#L451-L453 and it appears to use stderr

Could you clarify what you did (and whether it's recreatable)? I really don't think the problem could have been on import, but would have had to be on output. 

I definitely see it going to stderr with a simple test (turn off wifi and do a `ddev export-db`:

```
$ ddev export-db >~/tmp/junk.out
Wrote database dump from junk database 'db' to stdout in gzip format.
Internet connection not detected, see https://ddev.readthedocs.io/en/stable/users/faq/ for info.
```

**Comment by wolcen** [comment]
If we are discussing changing the verbage here, I would like to note again that part of the problem we've seen with this issue is that the warning itself is rather deceptive.

The message ultimately indicates that: "Automatic DNS resolution of *.ddev.site to local host failed". That a faulty internet connection can be the cause does not describe the actual issue DDEV is having.

**Comment by rfay** [comment]
Great comment, thanks. Your suggestion offers a good path.

**Comment by wolcen** [comment]
I realize you are aware, since it's been updated so well to date, but just a reminder to ensure [faq.md](https://github.com/drud/ddev/blob/master/docs/users/faq.md) stays in sync.

I looked back for that on troubleshooting.md first, forgetting it was in the FAQ...I guess the location of that text is debatable, but I'd argue for it being primarily on the troubleshooting page given it becoming less confusing to begin with (less "FAQ-like") and it is certainly something that fits into troubleshooting to determine the root cause of given a few possible solutions. Thanks!

**Comment by rfay** [comment]
Woudl appreciate your review of #2605 @wolcen

**Comment by wolcen** [comment]
Gah, sorry I missed your ping @rfay - thanks for (trying to) keep me involved and moving this ahead. Here's hoping all the extra context/clarity means less support time for you on this one :wink:

**Comment by rfay** [comment]
I hope you'll try it out, v1.16.0-rc3 has it. Lots less intrusive. Hope it's useful though. Thanks @wolcen
