### ISSUE TITLE
Consider using docker networking for separate IP addresses instead of nginx-router

### ISSUE THREAD

**Issue by rfay** [drud/ddev#272]
## What happened (or feature request):

I happened to note in [drupal-vm writeup by geerling guy](https://www.jeffgeerling.com/blog/2017/drupal-vm-does-docker) that he's using separate IP addresses for containers, instead of the nginx-router approach we're using. That might be pretty nice, and is worth keeping in mind. The nginx-router requires extra maintenance and complexity.

## Related source links or issues:
[Example docker-compose](https://github.com/geerlingguy/drupal-vm/blob/master/example.docker-compose.yml)
[Geerling guy drupal-vm article](https://www.jeffgeerling.com/blog/2017/drupal-vm-does-docker)

**Comment by tannerjfco** [comment]
Based on the testing and documentation/issue/forum digging I've done on this subject, I do not believe an IP-based approach is feasible for Docker for Mac. Due to how networking is implemented with HyperKit on Docker for Mac, it is not possible to route traffic to the containers. It is currently listed in known limitations as "not possible" to achieve per-container IP addressing. https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds.

The referenced project documents using an alias IP address on the loopback interface (`sudo ifconfig lo0 alias 192.168.88.88/24` is the specific command documented). This is a workaround Docker documents to facilitate connecting *from* the container to a service on the host. While this workaround does seem to also allow you to access ports exposed on the host from the defined IP, the ports are still exposed on the host itself, so we couldn't start another container wanting to serve port 80.

As for other platforms, while I haven't explicitly tested on Linux, it looks like defining IPs per container works like you would expect. I can't find anything specific indicating troubles on Windows. Happy to test if we want, but I feel like the Docker for Mac limitations make this a non-starter.

Relevant issues:
https://forums.docker.com/t/access-a-container-by-ip-address/12694/2
https://forums.docker.com/t/ip-address-given-to-container-is-not-routable-in-bridge-mode/12725
https://forums.docker.com/t/host-excluded-from-bridge-network/12015/12

**Comment by rickmanelius** [comment]
Moving to "hibernate" for now unless there are any counterpoints to @tannerjfco's comment regarding the viability. FWIW, additional discussion and a path forward are in this comment in the related issue https://github.com/drud/ddev/issues/277#issuecomment-305042775.

**Comment by tannerjfco** [comment]
I think we're safe to close this. In my search through issues and forum posts, there was no indication as to when or if the limitations surrounding per-container IP addressing would be resolved. If that changes in the future, we can dig this out or open a new ticket to investigate.

**Comment by rfay** [comment]
IMO this should be closed.
