### ISSUE TITLE
Add an optional `minimum-ddev-version` in .ddev/config.yaml

### ISSUE THREAD

**Issue by shaal** [drud/ddev#2752]
**Is your feature request related to a problem? Please describe.**
While working on a project together with a team, ddev was setup in latest stable version, but one of the team member is using older ddev version and getting into issues that wouldn't be there if they would use the version ddev was setup with.

**Describe the solution you'd like**
Add an optional `minimum-ddev-version` in .ddev/config.yaml

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
The easiest way to accomplish this is to add a pre-start exec-host hook that runs `ddev debug capabilities | grep <capability-youwant>` That way you can warn about the situation. If you want it to be really aggressive, your config.yaml can include `fail_on_hook_fail: true` (the default is false).

Since there's an easy way to do this, I'm going to close this for now.
