### ISSUE TITLE
Always getting "not adding command *" message, after customizing ddev default commands

### ISSUE THREAD

**Issue by robiasto** [drud/ddev#2754]
Every time I start a ddev  command I get this message on first line:
`not adding command typo3 (/Volumes/Development/TYPO3SRC/...) because it was already added to project t3-project
not adding command typo3 because it was already added to project`

I need to add my customized typo3 command to `command/web` folder, because there is a not default path to the typo3 command in my project.

Is there a way to remove this message?

**Comment by rfay** [comment]
Hi @robiasto - 

* The easiest way to solve this is to make your changes to the global ~/.ddev/commands/web/typo3 script instead of adding it to the project. (Don't forget to remove the "#ddev-generated" line at the top of the script). ddev v1.16+ has a built-in typo3 command, as you already know. 
* You might consider just adding to the in-web-container $PATH instead of changing the typo3 command. It's not hard. 
    * You can add to the $PATH using a docker-compose.path.yaml, see https://ddev.readthedocs.io/en/stable/users/extend/custom-compose-files/#docker-compose42yaml-examples
    * You can add to the path using a .bashrc added in .homeadditons (global or project)
    * Starting [v1.17.0-alpha3](https://github.com/drud/ddev/releases/tag/v1.17.0-alpha3), you can [set environment variables like $PATH in the config.yaml](https://ddev.readthedocs.io/en/latest/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container)
    
On a side note - where does your project put the typo3 command in the web container? Should we be adding more to the default PATH?

**Comment by robiasto** [comment]
Thanks, that works.
