### ISSUE TITLE
ddev ignores docker-compose command syntax to pass arguments to entrypoint on db container

### ISSUE THREAD

**Issue by Roizan** [drud/ddev#2760]
**Describe the bug**
docker-compose utilizes the 'command:' syntax within docker-compose.yml files to pass additional arguments to the entrypoint of the container.

ddev seems to ignore this behavior when a command directive is injected into the built docker-compose files via docker-compose.override.yaml

While the built docker-compose files (..ddev-docker-compose-full.yaml etc.) contain the added argument from the docker-compose.override.yaml nothing is passed to the entrypoint.

[Visible in line 100](https://github.com/drud/ddev/blob/master/containers/ddev-dbserver/files/docker-entrypoint.sh#L100) in entrypoint.sh of the ddev-dbserver, the mysqld is fired up only with ```--server-id=0``` without passing more arguments from any source

**To Reproduce**

1. create new ddev project (mysql 8.0)
2. add a docker-compose.override.yaml to the .ddev folder with content as following
    ```
   services:
     db:
        command: "--lower_case_table_names=1"
    ```
3. start the project
4. enter the mysql container -> ```ddev ssh --service db```
5. start mysql client and enter following ```show variables like 'lower_case_%';```

**Expected behavior**
This would be the expected behavior (taken from a regular docker setup with mysql 8 and command argument within docker-compose.yml), showing the variable lower_case_table_names switched to 1
```
mysql> show variables like 'lower_case_%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | OFF   |
| lower_case_table_names | 1     |
+------------------------+-------+
2 rows in set (0.02 sec)
```

**Screenshots**

This is the current behavior of ddev

```
mysql> show variables like 'lower_case_%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| lower_case_file_system | OFF   |
| lower_case_table_names | 0     |
+------------------------+-------+
2 rows in set (0.00 sec)
```

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version: 3.1.0 (Engine 20.10.2 / compose: 1.27.4)
- ddev version information: 1.16.4
- config.yaml 
```
name: customer-xyz
type: php
docroot: web
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: ""
mysql_version: "8.0"
provider: default
use_dns_when_possible: true
composer_version: "1"
```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? - none

**Comment by rfay** [comment]
The database images use `entrypoint` to specify what to run; that's what their upstream images do, so that's why.  You should be able to do what you want with `entrypoint`

However, wouldn't it be ever-so-much easier just to add custom mysql config? https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-mysqlmariadb-configuration-mycnf

**Comment by rfay** [comment]
Here's the code: https://github.com/drud/ddev/blob/a7cb1488d0cf237c44c9880014c0d4397db9e2b2/containers/ddev-dbserver/Dockerfile#L46-L51

Reading your issue again, I see that you already understand that entrypoint is used. But we won't be changing this approach.

**Comment by rfay** [comment]
Happy to help you get your issue solved, happy to continue the conversation here or elsewhere.

**Comment by Roizan** [comment]
Hi @rfay - thanks for the follow up!

Adding custom mysql config to switch the server variable lower_case_table_names does indeed work with **mariadb**, but **mysql8** instead only allows setting lower_case_table_names during the initialisation and creates this error when you try to set it after initialisation via additional config.

```
[ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('1') and data dictionary ('0').
```

We only stumbeld across this problem as we started porting over older projects based on regular docker-compose files (using the official mysql8 baseimage) to ddev.

**Comment by rfay** [comment]
You can overwrite the /etc/my.cnf with a .ddev/db-build/Dockerfile - that might be an easy way around this. Or you could just append to the existing one.

**Comment by rfay** [comment]
Here's a technique to do what you want @Roizan 

1. Create the file .ddev/db-buld/Dockerfile with contents:
```dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN printf "[mysqld]\nlower-case-table-names=1\n" > /etc/mysql/conf.d/lower-case.cnf
```
2. `ddev delete` and then `ddev start` (have to load database again from dump or snapshot)

```

$ ddev delete -Oy && ddev start && echo "show variables like 'lower_case_%';" | ddev mysql
Stopping ddev-d9-web  ... done
Stopping ddev-d9-dba  ... done
Stopping ddev-d9-solr ... done
Stopping ddev-d9-db   ... done

Removing container: ddev-d9-web
Removing container: ddev-d9-dba
Removing container: ddev-d9-solr
Removing container: ddev-d9-db
Deleting database. Volume d9-mariadb for project d9 was deleted
Deleting third-party persistent volume ddev-d9_solr for service solr...
Deleting docker image drud/ddev-dbserver-mariadb-10.5:switch-to-github-actions-d9-built
Deleting docker image drud/ddev-webserver:20210115_platform-d9-built
Project d9 was deleted. Your code and configuration are unchanged.
Starting d9...
Creating volume "d9-mariadb" with default driver
Creating volume "ddev-d9_nfsmount" with local driver
Creating volume "ddev-d9_solr" with default driver
Building db
Building web
Creating ddev-d9-solr ... done
Creating ddev-d9-db   ... done
Creating ddev-d9-dba  ... done
Creating ddev-d9-web  ... done

ddev-router is up-to-date
Ensuring write permissions for d9
Ensuring write permissions for d9
Existing settings.php file includes settings.ddev.php
Successfully started d9
Project can be reached at https://d9.ddev.site https://127.0.0.1:9998

Variable_name	Value
lower_case_file_system	OFF
lower_case_table_names	1
```

**Comment by Roizan** [comment]
@rfay thanks you so much for diving in so deep into this issue ❤️  
Your approach does work with mariadb, mysql 8.0 still refuses to accept it and aborts with the same error as before.

```
2021-01-26T22:38:21.509753Z 1 [ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('1') and data dictionary ('0').
2021-01-26T22:38:21.510085Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2021-01-26T22:38:21.510295Z 0 [ERROR] [MY-010119] [Server] Aborting
2021-01-26T22:38:22.010924Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.21)  MySQL Community Server - GPL.
```

But as this seems an issue with mysql 8 only and our projects are easy to switch over to mariadb - we will use maria in the future 😁

**Comment by rfay** [comment]
Sorry, I fooled myself, switched to PHP8.0 instead of Mysql 8.0 :)

And there's a complication here - The initialized empty database is actually created during the build of the ddev-dbserver image for performance reasons. So nothing that we would have done would solve this, according to the links I've followed. 

Here's a workaround. I don't know if it will work for you:

1. Do the above with a MySQL 5.7 project. As we know, it works.
2. Change the mysql version to 8.0. `ddev config --mysql-version=8.0`
3. `ddev start`

$ ddev exec -s db mysql --version
mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)

rfay@rfay-mbp-2017:~/workspace/d9/.ddev$ echo "show variables like 'lower_case_%';" | ddev mysql
Variable_name	Value
lower_case_file_system	OFF
lower_case_table_names	1

**Comment by Roizan** [comment]
Awesome 👍 

Works like a charm - maybe a cool addition to the docs.

**Comment by rfay** [comment]
Glad it's working for you! It's kind of a round-about path, but glad it works.

**Comment by scrummer** [comment]
@rfay Is there a working solution/workaround for the latest ddev version? Since ddev forces you to completely destroy and re-initialize the database on a version migration, this does not work anymore.
Every time migrating I get the same error as @Roizan earlier:
```
2023-06-19T14:03:56.587625Z 1 [ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('1') and data dictionary ('0').
2023-06-19T14:03:56.587714Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2023-06-19T14:03:56.587725Z 0 [ERROR] [MY-010119] [Server] Aborting
```

Or is there already a better patch/workaround?

Best,
Jan

**Comment by rfay** [comment]
So @scrummer is your problem that you have a mysql 5.7 database that you can't export and then import successfully into mysql 8.0?  I'm lost in this (more than 2-year-old) issue how it relates to you.

**Comment by scrummer** [comment]
### Situation
I have a project with MySQL 8.0 database. When running project-internal migration and/or sync scripts which affect the database the following error occurs (due to wrong `lower_case_table_names` setting):
`SQLSTATE[HY000]: General error: 1826 Duplicate foreign key constraint name [...]`

### Problem
I tried setting the `lower_case_table_names` setting using different ways:
1. I created a `[project]/.ddev/mysql/table-case.cnf`
  i. Did not work due to the fact mentioned by you earlier above
    > The initialized empty database is actually created during the build of the ddev-dbserver image for performance reasons
2. I tried changing the value at runtime (just to run my scripts)
  i. Somehow I was not able to correctly reboot the mysqld service due to several (different) permission issues (neither with mysql nor my own nor the root user)
3. I tried the workaround above, setting the DB version to `5.7` with the custom `Dockerfile` which injects the `lower_case_table_names` setting into the config (which 'should' actually be the same as approach No. 1). Then changing the DB version back to 8.0 again
  i. The initialization of the 5.7-DB worked well. However, when changing the DB version DDEV shows an error, that the DB version changed and you have to manually migrate the DB with either export, delete and import data again or using the `ddev debug ...` command.
  ii. I guess this approach did work once upon a time until the point where ddev introduced this feature, that the DB is completely re-initialized/-created with a version change (I guess that was about 1.19 or 1.20 where that came up).

### Conclusion
Whatever way I try to set `lower_case_table_names`, I either run into the issue, that I need to recreate the DB at runtime or the following error (when booting the MySQL 8.0 server with `lower_case_table_names` set):
```
2023-06-19T14:03:56.587625Z 1 [ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('1') and data dictionary ('0').
2023-06-19T14:03:56.587714Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2023-06-19T14:03:56.587725Z 0 [ERROR] [MY-010119] [Server] Aborting
```


Hope this is information enough - very happy to hear any kind of ideas or approaches.

**Comment by rfay** [comment]
I think you have an application-level problem and that it will haunt your project when it gets to production as well, and you should try to figure out how to solve it. 

Does Pimcore claim to support MySQL 8.0? I know it's time to move, as they're deprecating 5.7 now. Have you considered a PR to Pimcore to make it stop this behavior?

I think you may be able to manually `ddev ssh -s db` and manually issue commands to delete and recreate the `db` database.

Another option is to use a database besides the `db` database, which you create *after* start. As you know, the `db` database is precreated at image build time, which is why you're having trouble (I think). So try using a different target database. Add your .ddev/mysql/*.cnf and then `ddev import-db --target-db=pimcore /path/to/db.sql.gz`
