### ISSUE TITLE
Use port 9003 as default for Xdebug

### ISSUE THREAD

**Issue by andypost** [drud/ddev#2898]
**Run a Diagnostic**

If you're having trouble with ddev,

1. Please use the latest stable version of DDEV-Local before reporting. Upgrading is easy.
2. Please run a quick diagnostic and post the results as a new gist on gist.github.com (or on another pastebin-type site if you prefer). You can download [test_ddev.sh](https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh) and run it per the instructions at the top. That will help so we don't have to ask so many questions... And it it works, it probably means there's something wrong with your project, not ddev.
**Describe the bug**

**To Reproduce**
https://github.com/drud/ddev/blob/master/docs/users/step-debugging.md said that client needs to listen to 9000 port but default has changed in xdebug 3.0 (which is preferred nowadays)

**Expected behavior**
Phpstorm already listening both ports for compatibility reasons now. The docs should explain client_port changes

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Catalina]
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version information (use `ddev version`)
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by rfay** [comment]
Hi @andypost - You didn't fill out the issue... but

ddev's built-in config keeps the port at 9000, because so many people already have that already in their IDE, and because xdebug 3 is not available for all PHP versions. 

xdebug in ddev works out of the box with no configuration on PHPStorm, and only a tiny bit on vscode.

Closing this, happy to continue the conversation here or elsewhere.

**Comment by andypost** [comment]
Thank you! Totally clear

**Comment by rfay** [comment]
Note that recent versions of PHPStorm listen on both 9000 and 9003, which is wonderful. But not vscode or lots of other things. So it will be a while. I do wish we could just jump to 9003, so we wouldn't have the issues with conflicting with php-fpm

**Comment by tyler36** [comment]
I think this issue needs a second look.

- [Xdebug website](https://xdebug.org/docs/all_settings#client_port) states `9003` is the default because many IDE use it and recommends against changing
- PHPStorm use `9003` but also the older `9000`, as reported by rfay
- VSCode, 
  - PHP Debug@1.17.0 by Felix Becker (most popular at 5M downloads) has port `9003` as default and `9000` for XDebug `legacy `
  - PHP Debug@1.14.0 by Robert Lu (78K downloads) uses `9000`; non-standard

Anyone debugging Xdebug is going to come across current version using port `9003` on websites & forums. Xdebug has been out for 9 months now and IDEs have moved forward. I think it's time for DDEV to catch up too.  

This would be a case for default global setting that can be overriden on a per-project basis similar to #3109 . That way, people could make a simple change in a global config to keep all their projects as `9000`. Or add it to the few outlier projects that require it.

**Comment by rfay** [comment]
I would really like to use port 9003, so happy that the Felix Becker PHP Debug is now doing 9003.

**Comment by tyler36** [comment]
It would be nice to update. I have to keep a separate "DDEV Xdebug" option in VScode. Not sure when Felix Becker added the update. 

If it's IDE default that is holding this back, I don't think thats relevant anymore. 

Beside updating the 11+ references on the Xdebug page in DDEV docs, what else is holdingt his back?

**Comment by rfay** [comment]
There will be IDEs in use besides PhpStorm and vscode. But there aren't many that I know of. 

I think in a major release we can just tell people about it and how to work around it. 

It's possible this could make it into v1.18. Oh it would be so nice to have PhpStorm not competing with php-fpm.

**Comment by rfay** [comment]
I do note that the new port 9003 only went into xdebug/vscode-php-debug in June, 2021, https://github.com/xdebug/vscode-php-debug/compare/v1.15.1...v1.16.0

So I'm not really willing to push this into ddev v1.18, but it seems like it might go into v1.19.

IIRC the vscode xdebug extension was unmaintained for some time right? Looks like now it's chugging away.

**Comment by tyler36** [comment]
Sounds fair. Something to look forward to in 1.19!

**Comment by weitzman** [comment]
FWIW, I'd like to the default change as well. IMO is suitable for a minor release.

**Comment by rfay** [comment]
This is in latest v1.19.0 edge releases. I'm sad that it seems vscode does *not* have explicit support for port 9003, and people do have to change their launch.json.
