### ISSUE TITLE
Port 80 conflict suggestions

### ISSUE THREAD

**Issue by ijf8090** [drud/ddev#2919]
I ran into this issue while attending NERDCamp, I worked with Randy to resolve. I had changed the port settings in  config.yaml as recommended but this di not fix the issue. On deeper investigation docker ps -a revealed that other containers were running, one of which was using port 80. Killing that container resolved the issue. I had set docker to start on boot, this may have been a contributing factor.

 I am confused as to why changing the config.yaml file was not enough to resolve this issue.

**Comment by rfay** [comment]
What happened to you was this, if I remember:

* You had several sites running, and they were using ports 80/443
* You had a system crash
* On restart, you tried to change just one site to use a different port set
* However, the other sites were still "paused" (due to the crash)
* A `ddev poweroff` got you set up properly

**Comment by rfay** [comment]
No response, so closing this. Happy to continue the conversation here or elsewhere.
