### ISSUE TITLE
Many private ssh keys, `ddev auth ssh`, and "too many authentication failures"

### ISSUE THREAD

**Issue by richlawson** [drud/ddev#2944]
**Is your feature request related to a problem? Please describe.**
You have to use `ddev auth ssh` to add your SSH keys into the web container for a `ddev pull pantheon` to work with the new provider functionality in 1.17.0.

If you’re like me and have accumulated a lot of private ssh keys in your ~/.ssh directory, you may run into the following error when you pull: too many authentication failures.

The web container attempts to use each of the ssh keys added to authenticate against Pantheon, and if it doesn’t get to the right key within the max number of allowed authentication attempts, you get the error above.

**Describe the solution you'd like**
A way to include a configuration for specifying the correct key. Would it be possible to include the ssh config file during `ddev auth ssh`? Or would it be possible to specify the key location in the provider's yaml file?

**Describe alternatives you've considered**
My workaround was to create a new directory just for ddev keys containing only the keys I wanted to add to the web container and then use this command: `ddev auth ssh -d ~/ddev-ssh-keys`.

**Comment by rfay** [comment]
Hi @richlawson - There are a few workarounds for this. The message you're getting is because the *server* refuses to work with multiple offered keys.

1. Put the keys you actually need in a particular directory and use `ddev auth ssh -d <dir>`
2. Use the actual keys in the container. You can do this by copying your ~/.ssh into ~/.ddev/homeadditions. Then you can adjust the ~/.ddev/homeadditions/.ssh/config to specify particular keys.

Note that there aren't usually good reasons (but lots of historical ones) for having lots of private keys. You can use one private key for everything. But I know that doesn't always work out.

**Comment by rfay** [comment]
There's no way to provide "just the key needed" in the provider config file, because the keys don't physically exist in the - the agent just makes their auth available.

I'm way open to some other future approach on this, but the two solutions here are the only ones I know of at this point.
