### ISSUE TITLE
Make notice of new version available more noticeable - upgrade, update

### ISSUE THREAD

**Issue by chrisfromredfin** [drud/ddev#2959]
**Is your feature request related to a problem? Please describe.**

I always want to be sure I'm on the latest version of DDEV before coming into the Slack channel or filing an issue. However, even though a new version was available, I wasn't notified that there was a new version to download. (In fact, I was - but had missed it.) 

**Describe the solution you'd like**

It seems as though DDEV does make a check to see if there's a new version weekly, and does notify the user when there is; however, it's not as prominent as I'd like it to be. It currently gets lost with a lot of other output of `ddev start` -- I think a colorized version of the warning with some space / other characters around it would call more attention to the fact that there's a new version.

**Describe alternatives you've considered**

- check every time ddev start is run  (requires hitting github on every `ddev start`)
- still check weekly, but make it persistent so every single `ddev start` shows the notification (requires storing some persistent piece of data saying is_out_of_date)
- make the notification more noticeable (easiest, maybe?)

**Comment by chrisfromredfin** [comment]
For anyone wanting to work on this, code is around here:

https://github.com/drud/ddev/blob/1d2cb1d74b9e4378a290240a4c6e6a12805ba4a5/cmd/ddev/cmd/root.go#L37-L98

**Comment by rfay** [comment]
I have this going in https://github.com/drud/ddev/pull/2965 - couldn't find this issue to credit it, and I snuck it in there because I was changing all the color handling. 

How do you like this? Comments welcome.

<img width="886" alt="Cursor_and_rfay_covid19-web___var_www_html_docroot_sites_mepa_and_Slack___ddev-feed___TYPO3" src="https://user-images.githubusercontent.com/112444/130288935-129f0c76-71bf-469a-a550-3dd3c7eaa5bf.png">

**Comment by chrisfromredfin** [comment]
I like it colorized like this, it will call more attention to it without being too in your face.
