### ISSUE TITLE
Sophos considers ddev_windows_installer v1.17.1 a threat or virus in Windows. 

### ISSUE THREAD

**Issue by liang-wap** [drud/ddev#2973]
In windows 10, Sophos will delete ddev as soon as it's downloaded. "choco install -y ddev" will be stopped too. 

"Generic ML PUA detected at \Downloads\ddev_windows_installer.v1.17.1.exe"

**Comment by rfay** [comment]
Thanks for reporting this.

Do you know how to file an issue with sophos? Do they give you any help?

ddev_windows_installer.exe is signed, about as safe as it can get.

**Comment by rfay** [comment]
Looks like sophos may consider nssm a threat, https://www.virustotal.com/gui/file/a606942ccc3968506c513041c82e227e2c10bbb194c59590148d20a87254571d/detection/f-a606942ccc3968506c513041c82e227e2c10bbb194c59590148d20a87254571d-1603666154

**Comment by rfay** [comment]
A lot of times these auto-detection schemes get fixed in a day or so. I wasn't able to find any useful information on the sophos site about how to handle or report false positives, despite the fact that google foudn some good titles. 

@liang-wap what version of Sophos were you using? Home? Free? Was it updated?

**Comment by rfay** [comment]
I was able to recreate the behavior described by @liang-wap using Sophos Home edition.

Possibly a few people have to say "allow and restore" for this to reach their attention? I did this and it allowed me then to install with choco or otherwise:

![image](https://user-images.githubusercontent.com/112444/116648838-445c5b00-a93b-11eb-8eb5-6b99bce10a7c.png)


Sophos does not seem to be a very high-rated virus checker...

**Comment by rfay** [comment]
Interestingly enough, I'm able to `choco install ddev` with today's ddev v1.17.2 with no trouble. 

I did have to uninstall it first, because sophos broke the choco installation procrss, but after that it worked with no complaints from sophos.

**Comment by liang-wap** [comment]
After seeing your comment, I tried to run "choco install ddev" and installed v1.17.2 successfully. 
Interesting...

**Comment by rfay** [comment]
Closing this for now. If Sophos acts up again we'll reopen.

**Comment by rfay** [comment]
Sophos is again alerting on v1.17.5, https://www.virustotal.com/gui/file/77345f6856fc3f310659a1777127aa8c800726bbed53801c419ca34d77b2de45/detection
