### ISSUE TITLE
ddev sequelace not working on mac

### ISSUE THREAD

**Issue by danshumaker** [drud/ddev#2993]
Is there a way to turn on debugging in ddev?  When I run `ddev sequelace` , sequelace comes up with all the right server settings, password, etc, but it is not able to connect.

In contrast,  `ddev mysql` works fine and am able to connect.  So it must be a difference in the ssh or tunnel settings??  I'm not really sure.

Our setup is pretty generic see screenshot
![2021-05-07_18-36-48](https://user-images.githubusercontent.com/358833/117515356-04f9c400-af64-11eb-989d-5a76e47bef3b.png)

Thank you for any help. 

btw, sorry to hear about https://www.ddev.com/notice/ .

**Comment by rfay** [comment]
Hmm, it works for me - I have sequelace 3.3.1 running on an intel mac running Big Sur. It comes up and connects fine. 

It looks in your screenshot like it made a connection to port 51409, but somehow that timed out.

Before going much farther, of course, do a `ddev poweroff` and restart docker, and consider rebooting your computer. 

Then, to debug, 

* Edit the command; it's just a shell script at ~/.ddev/commands/host/sequelace
* Remove the line that says #ddev-generated (otherwise ddev will overwrite your debugging changes)
* Add a `set -x` early in the script so you can see exactly what it does
* Try to reproduce the one execution line as it does. 

If it fails, try to connect to it with `mysql -uroot -proot -h 127.0.0.1 -p <portspecified>` - if you can do that, then everything ab out ddev/docker is working, and something's wrong with sequelace (which seems possible)

You don't say what database you're running on this project... Do you have this problem with every project? Does it work with a dummy project? If you're using mysql 8.0, there are often compatibility problems with it and many mysql clients.

**Comment by rfay** [comment]
But I just tried with Mysql 8.0 and I don't see any trouble.

**Comment by danshumaker** [comment]
Hmm, the database seems to work fine according to Drupal and the web container. I've been using and developing with the site for a week or so.  So the database is "good" in that respect.  And as said `ddev mysql` connects just fine.   so surely it's communication difference between the SequelAce application layer and the the ddev dns server ( I mean router)???
- I just `brew install mysql-client` but it's not in my path after the install.  Will rectify that and post back.

**Comment by danshumaker** [comment]
Ok, did another `ddev restart` , then it chose a different port 57566 , and now `ddev sequelace` connects.  Must have been a bogus port before??

**Comment by rfay** [comment]
You probably had some random thing on your computer competing for that port.
