### ISSUE TITLE
Consolidate ddev-images+ddev image build and switch to GitHub Actions for parallel builds + publishing

### ISSUE THREAD

**Issue by dennisameling** [drud/ddev#3047]
Hope all is well! :) Just found out that GitHub Actions now has built-in support for [Docker buildx + QEMU](https://github.com/marketplace/actions/build-and-push-docker-images). This is great news, because it removes the need for custom scripts like [linux_circle_vm_setup.sh](https://github.com/drud/ddev-images/blob/master/.circleci/linux_circle_vm_setup.sh), therefore reducing complexity in this repo.

Pushing a new multi-platform image is then as easy as: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

We could also build the `amd64` and `arm64` images in parallel on PRs, using a GH Actions matrix. That should significantly bring down the build time, which is currently 1 hour.

The alternative is to have CircleCI build the images natively on `amd64` and `arm64` (now that they have `arm64` support in beta, which I saw you're already using in `drud/ddev` 🎉), but I'm not sure if your CircleCI license allows for simultaneous workflows. Building `arm64` natively should at least speed things up significantly. When pushing both images to Docker Hub, I believe they still need to be built using QEMU on the same host, but that could e.g. be done with the multi-platform approach in GH Actions as mentioned above (or just leaving it at CircleCI).

So I think would mean there's three options for speeding up PR builds:
1. Using a GitHub Actions matrix for simultaneous `amd64` and `arm64` builds from a `amd64` host (I wouldn't be surprised if GH adds native `arm64` support later this year, they already support self-hosted Linux `arm64`)
2. Using native CircleCI machines for both `amd64` and `arm64` builds in parallel, but again I don't know if your CircleCI license allows for simultaneous builds
3. Use GitHub Actions for building the `amd64` image and CircleCI for the `arm64` image natively, that way you still have parallel builds 🤓 

Curious to hear your thoughts on this, happy to help!

**Comment by rfay** [comment]
https://github.com/jesec/rtorrent/blob/master/.github/workflows/publish-rolling.yml is quite simple, and would go very easily into circleci:

* Two parallel builds that push amd64 and arm64 (without qemu, which is always bugging out). Each gets pushed with an arch-specific tag
* Following build does `docker buildx imagetools create -t jesec/rtorrent:master jesec/rtorrent:master-arm64 jesec/rtorrent:master-amd64` to combine the two into a single one
* Following build removes the intermediate arch-tagged tags

This is trivial to implement on CircleCI because it has arm64. 

When moving the php-base build to drud/ddev we can still keep the long php-base build separate process-wise, and use this technique.

The one thing I'm struggling with is how to build multi-arch when we're *not* on CircleCI. That's where the generic qemu technique shines (when it works). So I don't want to lose the ability to build outside CircleCI...

**Comment by rfay** [comment]
Fixed in https://github.com/drud/ddev/pull/3491 ! So much simpler @dennisameling :)
