### ISSUE TITLE
The scheme of DDEV_PRIMARY_URL can't be controlled

### ISSUE THREAD

**Issue by davidotton** [drud/ddev#3091]
My problem is that `ddev drush uli` always returns an http URL. Chasing back, I believe the value of `DRUSH_OPTIONS_URI` is set from `DDEV_PRIMARY_URL`. I can't find any way to control whether `DDEV_PRIMARY_URL` is http/https in `config.yaml`

I suggest adding param(s) to give more control over `DDEV_PRIMARY_URL`.

If this is already possible and I've mislabelled a support request, I apologise. (ddev version v1.17.6, Drush Commandline Tool 10.3.4, Drupal 8.9.16).

**Comment by rfay** [comment]
If `ddev drush uli` returns an http URL it's probably because you don't have https set up? 

What does `ddev list` show you? https or http URL? If it's http, then run `mkcert -install` and then `ddev poweroff && ddev start`

**Comment by davidotton** [comment]
> If `ddev drush uli` returns an http URL it's probably because you don't have https set up?

Thanks for the reply. That's correct. I want to be able to preference https, without installing mkcert, because I can't control whether other devs on the team install it. `ddev list` shows:

```
NAME                 TYPE     LOCATION                                             URL                             STATUS
site-name        drupal8  ~/PhpstormProjects/site-name              http://site-name.ddev.site  running
```

**Comment by rfay** [comment]
Everybody should run `mkcert -install` or they'll be stuck with untrusted https forever. And ddev whines at you all the time! I sure recommend that you get everybody to do that. 

Anyway, $DDEV_PRIMARY_URL in your case is in fact http:// - because you haven't properly set things up. 

If you really, really have to run using http, I imagine you can change DRUSH_OPTIONS_URI to `http://<project>.ddev.site` with web_environment in .ddev/config.yaml.

**Comment by rfay** [comment]
Actually, you may be able to change $DDEV_PRIMARY_URL that way too. But please don't. Please get your people to run `mkcert -install`. It's a one-time command.

**Comment by davidotton** [comment]
Thanks for suggesting a workaround. I'm going to close the issue.
