### ISSUE TITLE
Consequences of changing the name of an external volume which has projects on it?

### ISSUE THREAD

**Issue by begrafx** [drud/ddev#3092]
I have an external drive that, when I set it up, I wasn't thinking I guess; I put a space in the volume name. In general, this hasn't been an issue. In terminal, I just type 

`cd /Volumes/Big` and then I tap the TAB key, and autocomplete puts it out as `cd /Volumes/Big\ Box/` and I go on from there, no problem. However recently, I've come across a couple things that just aren't happy with that space in the volume name. I know HOW to change the volume name, that's easy enough, and off the top of my head, I'm not thinking of anything, but I want to toss this out and ask the group, is there some new issue that I'm not thinking of, that I would be CREATING by changing volume name? I'm unsure, if I do so, is DDEV going to be unhappy if I make such a change? I figure it's far smarter to think this through, and ask beforehand, rather than making a change, and opening an even worse can of worms.

**Comment by rfay** [comment]
Hi @begrafx - There are many volumes associated with ddev. None of them would have a name like "Big Box" and none of them have spaces. The most important one is the one where the database is stored; it's named `<project>_mariadb`. And since the project name can't contain spaces, it's unrelated to what you might be looking for. 

The `docker volume` command does not have a "rename" option. It doesn't look like they have any intention of creating one, see https://github.com/moby/moby/issues/31154

So I don't know what volume you might be re-using, but it doesn't sound like(right now) it has anything to do with ddev.

**Comment by begrafx** [comment]
No, "Big Box" is the name I've currently given one of my external drive volumes. Before doing so, I want to confirm, if I change "Big Box" to "BigBox" or whatever else, without the space, if I am going to create any problems/new issues, that you can think of.

**Comment by rfay** [comment]
Sorry, I completely misunderstood. I thought you were talking about docker volumes. You're talking about an external disk on a macOS system?

If your projects are not on that disk and you haven't tried to move Docker's disk space to that external disk, then this is completely unrelated to ddev.

If your projects are on the external disk you'll want to do a couple of things:

1. You'll want to make ddev "forget" about the project with `ddev stop --unlist`. Then it won't complain about the fact that you've "moved" it.
2. If you're using NFS, you'll want to check /etc/exports to see if anything has changed. If it has, you'll need to `sudo nfsd restart`

Your question is essentially "How do I move a project from one directory to another", as in the FAQ, https://ddev.readthedocs.io/en/stable/users/faq/

**Comment by begrafx** [comment]
Thanks Randy. Your help is greatly appreciated, as always.
