### ISSUE TITLE
PHP version and my-php.ini have no effect

### ISSUE THREAD

**Issue by RalfEisler** [drud/ddev#3105]
=== If you're having trouble with ddev ===

[ddev-test.txt](https://github.com/drud/ddev/files/6837080/ddev-test.txt)

=== Please explain exactly what the problem is. ===

my-php.ini not working.
php --version gets wrong php-version

composer require drush/drush exhausts memory-limit

=== Please describe step-by-step exactly how to recreate the problem you're having. ===

My project setup does not seem to work properly.

For the installation and maintenance and updates I need Drush, which however cannot be installed because of too little RAM.

In the .ddev folder I therefore place .ddev/php/my-php.ini, with the content (which is not taken over after a restart...

[php]
memory_limit = -1;

...results:

php -i | grep "memory_limit" 
memory_limit => 128M => 128M

Then ...

php --version

...results in:

PHP 8.0.8 (cli) (built: Jul 12 2021 11:08:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.8, Copyright (c) Zend Technologies with Zend OPcache v8.0.8, Copyright (c), by Zend Technologies

although...

ddev describes my-project.com

...results:

AME TYPE LOCATION URL STATUS        
haerter-partner.ch drupal8 /Volumes/12TBSeagate/Work/Sites/haerter-partner.ch https://haerter-partner.ch.ddev.site:8443 running

Project information
-------------------
PHP version: 7.4    
NFS mount enabled: false  
Database type: mariadb
MariaDB version: 10.3   

URLs:
----
https://haerter-partner.ch.ddev.site:8443
https://127.0.0.1:52448                  
http://haerter-partner.ch.ddev.site:8080 
http://127.0.0.1:52449                   

MySQL/MariaDB credentials
-------------------------
username: "db", password: "db", default database: "db".

or use root credentials if needed: Username: "root", Password: "root".

Database hostname and port INSIDE the container: db:3306
To connect to the db server inside the container or in the project settings files: 
mysql --host=db --user=db --password=db --database=db
Database hostname and port of HOST: 127.0.0.1:52374
To connect to mysql from your host machine, 
mysql --host=127.0.0.1 --port=52374 --user=db --password=db --database=db

Other services
--------------
MailHog (https): https://my-project.com.ddev.site:8026
MailHog: http://my-project.com.ddev.site:8025 
phpMyAdmin (https): https://my-project.com.ddev.site:8037
phpMyAdmin: http://my-project.com.ddev.site:8036 

DDEV ROUTER STATUS: healthy	
ssh-auth status: healthy 
ralfeisler@my-machine /my-path/my-project.com drush
The drush launcher could not find a local drush in your Drupal site.
Please add Drush to your project using Composer.

-- MacOs Mojave
-- Docker Desktop Version 3.5.2 (3.5.2.18)
-- DDEV-Local version
	DDEV-Local version	v1.17.7                                
	architecture      	amd64                                  
	db                	drud/ddev-dbserver-mariadb-10.3:v1.17.7
	dba               	phpmyadmin:5                           
	ddev-ssh-agent    	drud/ddev-ssh-agent:v1.17.0            
	docker            	20.10.7                                
	docker-compose    	1.29.2                                 
	os                	darwin                                 
	router            	drud/ddev-router:v1.17.6               
	web               	drud/ddev-webserver:v1.17.7 

-- config.yaml 
	name: my-project.com
	type: drupal8
	docroot: docroot
	php_version: "7.4"
	webserver_type: apache-fpm
	router_http_port: "8080"
	router_https_port: "8443"
	xdebug_enabled: false
	additional_hostnames: []
	additional_fqdns: []
	mariadb_version: "10.3"
	mysql_version: ""
	use_dns_when_possible: true
	composer_version: ""
	web_environment: []

-- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

	.ddev/php/my-php.ini:

	[php]
	memory_limit = -1

**Comment by rfay** [comment]
Hi @RalfEisler - Welcome to ddev, and thanks for running the diagnostic script. It helps me to know a lot of things about your environment instead of asking lots and lots of questions.

What's happening here is that you're confusing the php and drush and composer and such on your host computer with the php (and everything else) that ddev provides in the web container. 

The magic of ddev is that it runs a web container with nginx and php inside it, so you don't have to have php or drush or composer on your computer at all. All the problems you reported were about trying to run php and composer on your host machine, not inside ddev.

So the way you would access these things with ddev would be to `ddev ssh` and then run `php --version`. You can shortcut that with `ddev exec php --version` for example. 

And you would use `ddev composer` to run composer (that is a shortcut to run it inside the container, see https://ddev.readthedocs.io/en/stable/users/developer-tools/#ddev-and-composer)

So if you `ddev composer require drush/drush` you'll get drush installed OK I imagine. You were having trouble with your own configuration on your host machine.

**Comment by RalfEisler** [comment]
Hi @rfay -- Many thanks for the jump start. -- `ddev ssh` has helped.
