### ISSUE TITLE
Don't overwrite config_sync_directory in Drupal 8 / 9

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#3114]
**Is your feature request related to a problem? Please describe.**
ddev manages the infrastructure, but it doesn't manage the codebase or site's configuration. As such it has no reason to modify the config_sync_directory definition in Drupal 8 or 9.

**Describe the solution you'd like**
Remove the section of settings.ddev.php that relates to the default sync directory, let it be managed in settings.php as normal.

**Describe alternatives you've considered**
Overwriting the configuration in settings.php is cumbersome as it has to be done *after* the settings.ddev.php file is loaded, which won't be intuitive for beginners.

**Comment by rfay** [comment]
How can ddev know where the config_sync_directory is already set up? How can it know that there is one?

Remember lots of people will set a site up from scratch.

Open to your suggestions.

**Comment by damienmckenna** [comment]
Why does ddev need to know where the config_sync_directory is defined? It doesn't deal with the Drupal site's configuration, it doesn't load the config or export it? Drush handles that, or the Configuration Management UI, neither of which care that they're running on ddev.

default.settings.php says:

    * The default location for this directory is inside a randomly-named
    * directory in the public files path. The setting below allows you to set
    * its location.

So why does ddev need to get involved?

**Comment by rfay** [comment]
Drupal complains if it's not set doesn't it?

**Comment by guiu-rocafort** [comment]
I have a similar problem, but in my case I do want ddev to manage my setting files, the only thing i want different is the config_sync_directory value. 

I believe that it would be nice to be able to define a variable in config.yaml, and then, in case this is defined, use that value for the settings, and don't use the default value. 

I am attaching a small patch that does that.  To use it, you just need to define in the .ddev/config.yaml the environment variable "DRUPAL_CONFIG_DIR".

I am attaching a patch file for now, because i think it is a trivial change, and want to see your comments to  that approach first.

[configurable-settings.txt](https://github.com/drud/ddev/files/6991008/configurable-settings.txt)

**Comment by rfay** [comment]
@damienmckenna ddev never modifies $settings['config_sync_directory'] - it only adds one if it's not set, and it does that because Drupal insists on having one. Here's the snippet of code settings.ddev.php adds:

```php
if (version_compare(DRUPAL::VERSION, "9.0.0", '>=') &&
  empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}
```

I don't know if that solves your question? Happy to continue the conversation here or elsewhere, but closing for now.

**Comment by rfay** [comment]
@guiu-rocafort if you would like to suggest a new approach please open a PR and explain the goal of your PR.

The normal way to override something that has been set in settings.ddev.php is to change it after the include in settings.php. But in the case of config_sync_dir, it can be done anywhere, because ddev's settings.ddev.php won't touch it if it exists. So check it into your settings.php.

**Comment by apotek** [comment]
If, like me, you came to this thread wondering why ddev insists on adding these lines of code into your settings.ddev.file, even on an already configured site:

```
// Set $settings['config_sync_directory'] if not set in settings.php.
if (empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}
```

the solution is here: https://github.com/ddev/ddev/issues/4267#issuecomment-1271549128, viz:
set `disable_settings_management: true` in your config.
