### ISSUE TITLE
Grant Super_Priv to the db user in maria/mysql container

### ISSUE THREAD

**Issue by chrisfromredfin** [drud/ddev#3117]
**Is your feature request related to a problem? Please describe.**
I have a couple sites that use Salesforce module for Drupal, and some that use CiviCRM. Both of these modules/suites make use of triggers in the database. In order for this to work, I had to grant the Super_Priv to the DB user. 

**Describe the solution you'd like**
I generally use Makefiles to sync my sites (rather than custom ddev pull), so in my Makefile I was able to run `UPDATE mysql.user SET Super_Priv='Y' WHERE user='db';` - which I think realized I didn't need to do EVERY time, so I actually moved it to a post-start DDEV hook.

**Describe alternatives you've considered**
The above two approaches have worked. I've tried a number of other grant statements, but they don't seem to work. 

**Additional context**
* https://drupal.slack.com/archives/C5TQRQZRR/p1627161465409200?thread_ts=1627058697.386500&cid=C5TQRQZRR
* https://dba.stackexchange.com/questions/63404/how-to-grant-super-privilege-to-the-user (actually the part in the accepted answer here marked "There is a hack you can try but I normally would not recommend it." is exactly how I solved it).

**Comment by rfay** [comment]
@chrisfromredfin could you please provide a query that will succeed with this but fail without it (for the relevant test)?

**Comment by chrisfromredfin** [comment]
This ought to do it:

```
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`db`@`%`*/ /*!50003 TRIGGER civicrm_activity_before_insert before insert ON civicrm_activity FOR EACH ROW BEGIN
SET NEW.created_date = CURRENT_TIMESTAMP;
 END */;;

```

**Comment by rfay** [comment]
@chrisfromredfin you know that you can use user 'root' password 'root' to do things right? So you could use `ddev mysql -uroot -proot ...` to do what needs to be done in your Makefile (or use `mysql -uroot -proot` inside either web or db container)?

**Comment by chrisfromredfin** [comment]
I am aware of running things as root, though this is a database import which I do want to do as the db user, right?

**Comment by rfay** [comment]
If you use `ddev import-db` it will do it as user 'db', but you can import many ways, including using mysql inside either container, or `ddev mysql -uroot -proot <import.sql`, etc.

**Comment by rfay** [comment]
If you're normally doing your own custom imports anyway @chrisfromredfin you can use `ddev mysql -uroot -proot` or use `mysql -uroot -proot` inside the web or db container. It is not important that you do a db import as the limited 'db' user, in fact, your database seems to be set up such that it absolutely requires importing with root user. 

So if this problem is solved by just using the root user for your imports, I think we should close this issue?

**Comment by chrisfromredfin** [comment]
I guess I don't know enough about DB Triggers to know if that's the case;
but I can definitely say that importing as root doesn't seem to have any
unintended consequences for my/development purposes, so I think this likely
could be closed. :)

--
Christopher J. Wells
Redfin Solutions, LLC
office: 908-4-DRUPAL
fax: 207-292-1414
***@***.***
www.redfinsolutions.com

**Comment by rfay** [comment]
I'm going to go ahead and close this, but happy to revisit it. 

There are two things here:
* Import-time behavior (easy to do with root/root)
* Behavior of the salesforce module - can it do its job. You don't seem to have trouble with that I guess. 

Of course it's also easy to add privileges to the db user. It's a one-time action. You'd use `ddev mysql -uroot -proot` and grant the privilege. That's it. It can also be done as a post-start hook, but since it's a one-time operation, it shouldn't really need to be done on every post-start.

**Comment by rfay** [comment]
Related resource:[DDEV Database Management](https://ddev.com/ddev-local/ddev-local-database-management/)
