### ISSUE TITLE
MySQL 8 server and  "caching_sha2_password.so: cannot open shared object file"

### ISSUE THREAD

**Issue by meredevelopment** [drud/ddev#3146]
Diagnostic: [gist](https://gist.github.com/meredevelopment/e5f67b46292c008f24bdbd46d527cf0b)

**Describe the Problem**

I'm attempting to connect to an externally hosted MySQL 8 DB from within a container. When I try I get `ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory`

I've attempted to switch the `mysql_version` in config.yaml to "8.0" as I believe that supports the newer encryption, but no luck. 

Incidentally, if I switch the DB from Mysql 8 to Mariadb 10.2, delete the DB snapshot and reimport, I still get the same mysql 'version' output here: 

``` 
mac$ ddev ssh
me@ddev-mph-web:/var/www/html$ mysql --version
mysql  Ver 15.1 Distrib 10.3.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

I'm guessing this is the client version and not the server. If I have a look at the output of `ddev logs -s db` I see the version I've set in config. 

Any idea how I can get newer client, or add the plugin? Cheers!

**Comment by rfay** [comment]
There are a few workarounds. 

* If you have the option, change the user on the server (or create one)  to use mysql_native_password: `ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';`, see https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded . Here's what ddev does in the mysql 8.0 container:
    ```bash
if [  "${mysqld_version%%%.*}" = "8.0" ]; then
    mysql -uroot -proot <<EOF
        ALTER USER 'db'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD';
        ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD';
EOF
```
* Use the mysql client in the db container when you're set to `mysql_version: 8.0`: 
```bash
$ ddev ssh -s db
gitpod@simpleproj-db:/home$ mysql --version
mysql  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)
```
* Use a custom Dockerfile to install the mysql 8.0 client in the web container if that's important. Note that this won't work on current ddev v1.18.0-alpha* because mysql does not yet provide Debian Bullseye images. It also may be fragile because of the Oracle/mysql's non-standard way of doing everything. Information on how to use the mysql apt repository is at https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#apt-repo-install-components - Add this .ddev/web-build/Dockerfile
```dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.18-1_all.deb && sudo dpkg -i mysql-apt-config_0.8.18-1_all.deb
COPY mysql.list /etc/apt/sources.list.d
RUN sudo apt-get update 
RUN sudo apt-get remove -y mariadb-client && sudo apt-get install -y mysql-client
```
And add .ddev/web-build/mysql.list: 
```
deb http://repo.mysql.com/apt/debian/ buster mysql-apt-config
deb http://repo.mysql.com/apt/debian/ buster mysql-8.0
deb http://repo.mysql.com/apt/debian/ buster mysql-tools
deb-src http://repo.mysql.com/apt/debian/ buster mysql-8.0
```
With this, you'll get the mysql8 client in the web container.


There are some options for you!

**Comment by meredevelopment** [comment]
Ok thank you for such great detail, and I hadn't thought of using the client in the DB container.

I think for now we'll stick with the older `mysql_native_password` users for Development and then worry about this again when things go live :)
