### ISSUE TITLE
With mutagen-enabled failed to start: "unable to connect to daemon: client/daemon version mismatch (daemon restart recommended)"

### ISSUE THREAD

**Issue by sascha-krug** [drud/ddev#3153]
**Run a Diagnostic and Paste Link Here**

**Describe the Problem**

try to run `ddev config --mutagen-enabled && ddev start`
but failed with error:

> Starting mutagen sync process... This can take some time.
Using mutagen config file /Users/krugs/IdeaProjects/development-drupal-ddev/mutagentest/.ddev/mutagen.yml
Terminated mutagen sync session 'mutagentest'
Failed to start mutagentest: Failed to create mutagen sync session mutagentest. You may be able to resolve this problem with 'ddev stop mutagentest && docker volume rm mutagentest_project_mutagen' (err=Failed to mutagen [sync create /Users/krugs/IdeaProjects/development-drupal-ddev/mutagentest docker://ddev-mutagentest-web/var/www/html --no-global-configuration --name mutagentest --configuration-file=/Users/krugs/IdeaProjects/development-drupal-ddev/mutagentest/.ddev/mutagen.yml] (exit status 1), output=Error: unable to connect to daemon: client/daemon version mismatch (daemon restart recommended)
) 

ddev-project was totaly clean and docker has no containers and volumes.

**Version and configuration information (please complete the following information):**

Details see [test-ddev.sh-Output](https://gist.github.com/sascha-krug/686fbcee2ff0ee4c50398e1a6171d05b)

**Comment by rfay** [comment]
Hi @sascha-krug - Thanks for taking it for a spin! I assume you've been using mutagen (of another version) and it's running. Could you please stop it? `killall mutagen` or `mutagen daemon stop`

> unable to connect to daemon: client/daemon version mismatch (daemon restart recommended)

**Comment by sascha-krug** [comment]
Hi @rfay 
yes I tried these commands as well - but no. Same error message.

**Comment by rfay** [comment]
Thanks, would you please see if mutagen is running? `ps -ef | grep mutagen` ?

Please consider deleting your ~/.mutagen directory, `rm -r ~/.mutagen`

I assume you have another mutagen version installed. Could you please show `mutagen version` ?

**Comment by sascha-krug** [comment]
(Sidenote: I was using cweagans/ddev-mutagen on ddev v.17.* before - but not in this mutagentest-project)

**Comment by rfay** [comment]
You will not be able to run 0.11.8 and also run the 0.12 beta that ddev is using at the same time. 

Don't delete ~/.mutagen while a daemon is running.

Could you please try this without mutagen running at all, on a dummy project, not the same project? Just create a project using one of the quickstarts and see if it works. 

Consider updating your mutagen if you must keep one installed. If you do not need one, please uninstall it (`brew uninstall mutagen` and reboot your computer and then `rm -r ~/.mutagen`. 

If you *do* need mutagen installed otherwise, please use the same version. `brew uninstall mutagen` and `brew install mutagen-io/mutagen/mutagen-beta`

But you will not be able to have 0.11.8 running at the same time as you're trying to use this.

**Comment by rfay** [comment]
I'm happy to do a call with you to try to sort this out. I'd like to understand what's going on.
