### ISSUE TITLE
`ddev describe` and `ddev list` issues to be resolved in v1.18.0-rc2

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3218]
There are several [open issues](https://github.com/drud/ddev/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.18+in%3Atitle+describe+OR+winpty), but in addition to those:
- [x] Supposed debug-only message "tWidth=130 urlPortWidth=52 infoWidth=32" shows for all
- [x] `ddev list` is intolerable with larger paths and urls. Each column has to wrap or something. Or give up on table approach. Maybe the table approach isn't useful.
- [x] `ddev list` problems reported by @tyler36 in https://github.com/drud/ddev/pull/2965#issuecomment-909836351
- [ ]

**Comment by tyler36** [comment]
## ddev version v1.18.0-rc1-9-gac148660

### Windows Powershell 5.1.19041.1151

- There's a known bug with Windows Powershell & external programs displaying UTF8 with some discussion on slackoverflow [here](https://stackoverflow.com/questions/49476326/displaying-unicode-in-powershell) and [here](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096). This is componded when using asian font systems (like mine).
- These people need to add the following to their Powershell profile

  - Get profile file path
  ```
  # Display powershell profile path
  echo $profile
  ```

  - Explicitly use UTF8 for *all* encodingg
  ```powershell
   [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
   ```

### Powershell Core 7.1.4
- The bug still exists ... but the solution is the same as above.
- You can see the before / after in the screenshot below where the windows size has not been altered.
![DDEV-explicit-utf8](https://user-images.githubusercontent.com/7234392/132146983-4d390e1c-f883-4823-a82b-71b8bd2aa4b3.jpg)


You should be able to check off the my issue then since it *my issue* and not DDEV's 😄

**Comment by rfay** [comment]
Thanks so much!

**Comment by tyler36** [comment]
No problems ... apologies if you spent time chasing down my problem. 

Thankfully, when DDEV conquerors the world, we'll have a solution for those non-English systems now. 😉

**Comment by rfay** [comment]
But @tyler36 you're actually moving on to WSL2, true? What terminal are you using for that?

**Comment by tyler36** [comment]
I'm using Ubuntu via Window Terminal as much as possible. But I sometimes spin up a DDEV server on windows because Cypress E2E doesnt like to run in WSL2 (it often crashes)

I checked the latest version in Ubuntu (via WT) but there was no problem.

I don't use git-bash but when I gave it a spin, i got the following:
```
$ ./ddev list
bash: ./ddev: cannot execute binary file: Exec format error
```

**Comment by rfay** [comment]
git-bash uses the Windows binary you were using earlier for testing. And it would be ddev.exe.

**Comment by tyler36** [comment]
Thanks for the clarifications.

## minntty 3.5.0 (x86_64-pc-msys) [Windows 19042]

```
$ "C:\Program Files\DDEV\ddev.exe" --version
ddev version v1.18.0-rc1-9-gac148660
```

- Native Git-bash window looks OK
![ddev-gitbash-native](https://user-images.githubusercontent.com/7234392/132155333-1fc01374-5367-4cdd-a441-e994a60457d6.jpg)

- Git-bash through WT
![ddev-gitbash-wt](https://user-images.githubusercontent.com/7234392/132155361-2e0c44ed-8e8e-442f-be5e-297ad5ac8322.jpg)


The above "solution" doesn't work becuase it Powershell specific.

**Comment by tyler36** [comment]
OK ... think I've got it

The solution for git-bash through WT is to add the following line to your git-bash profile: `~/.bash_profile`

```
# Explicitly set UTF-8 encoding
chcp.com 65001
```

[Long answer in Japanese](https://www.it-mure.jp.net/ja/windows/gitbash%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9Funicode%EF%BC%88utf8%EF%BC%89/1066875239/ )

So ... thats should cover Windows Powershell, PowerShell Core, Git-bash; all in native & Windows Terminal

**Comment by rfay** [comment]
Could you please create a Stack Overflow with your acquired knowledge on these things? Just create a question, tag with "ddev", and "PowerShell" and then click the checkbox to "answer your own question".

Thanks! Otherwise we'll never find it again. Seems too obscure to me to put directly into docs, maybe I'm wrong. But "ddev on PS on Windows Japanese UTF-8" seems like a a dark corner at this time in the world's history.

**Comment by rfay** [comment]
Ooops, I see you didn't get the answer in there and you're new. Did they prevent you from answering your own question in https://stackoverflow.com/questions/69081249/ddev-on-ps-on-windows-japanese-utf-8 ? 

If you want, write it up in markdown and I'll paste it in there, but I wish they'd let you do it.

**Comment by tyler36** [comment]
I added the question, but the answer write-up took some time.

Stack Overflow Q/A is [here](https://stackoverflow.com/questions/69081249/ddev-on-ps-on-windows-japanese-utf-8/69081340#69081340).

**Comment by rfay** [comment]
I was afraid they'd locked you out because you were new. Thanks for the great work on that.
