### ISSUE TITLE
mkcert - can't get secure connection NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by MisterH001** [drud/ddev#3229]
I have tried everything to get this to work. I am using WSL 2 on Windows 10.
I have run mkcert -install which completes successfully and reports:

> Created a new local CA 
> The local CA is now installed in the system trust store!

I have restarted ddev to apply the changes but all browsers I try still show a certificate error. (Chrome, Brave, Edge).
I have reinstalled and removed local CAs like so:

> mkcert -uninstall
> rm -rf "$(mkcert -CAROOT)"

Then reinstalled (not as sudo).
If I check ownership by using:

> ls -l "$(mkcert -CAROOT)"

the certs are correctly assigned to my user.
But I still get the cert errors in all browsers.

Am I doing something wrong?
Many thanks

**Comment by rfay** [comment]
Hi @MisterH001  - Please follow the instructions exactly on https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2, go through step-by-step.

WSL2 is complicated because people typically use the browser on the WINDOWS side, but the webserver is running in docker on the WSL2 side. There are really 3 different entities going there. The instructions try to help you 

1. Create the CA on the Windows side
2. Install it in the windows-side browser (probably only Chrome works out of the box on WIndows)
2. Expose it on the WSL2 side by sharing the CAROOT environment variable into WSL2
3. Have ddev/ddev-router use the CAROOT environment variable to use the windows-side CA.

**Comment by MisterH001** [comment]
Many thanks Randy.
I didn't realise that out of the box mkcert would only work if viewing directly from the ddev environment.
I have now got this working by generating my own SSL (using this: https://www.selfsignedcertificate.com/) and then adding the crt and key to .ddev/custom_certs dir, then adding the cert in windows as a trusted root certificate.
This process works now.
Thanks again for your help and all your time on this awesome project :)

**Comment by rfay** [comment]
I'm glad you've got it going. Of course it works with mkcert as per the instructions. But installing your own cert is the same thing.

Glad to know you're using the custom certs option - not sure many people have used that.
