### ISSUE TITLE
Generate `.ddev/.gitignore` earlier in the process of `ddev start`

### ISSUE THREAD

**Issue by shaal** [drud/ddev#3239]
**Is your feature request related to a problem? Please describe.**

When running ddev with the wrong setup, ddev will halt in the middle, and all the files ddev generated under `.ddev/` directory, will be listed as files that have changed in `git status`.

**Describe the solution you'd like**

By generating `.ddev/.gitignore` as soon as the `.ddev/` directory is created, `git status` will remain clean, even when running ddev with the wrong setup that will get it halt in the middle of the process.

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
This is a good idea. No reason it can't be done on `ddev config`

**Comment by rfay** [comment]
@shaal ddev already creates .ddev/.gitignore during `ddev config`, and also updates it during `ddev start`. Can you please come up with a recreation scenario for the problem you're having?  `ddev config` is as early as it could possibly be.

I'll bet you're talking about a situation where you check out a project with the config already done, and because ddev has never done anything, it doesn't have the .ddev/.gitignore created. How would you suggest to do it before `ddev start` in this case?

**Comment by shaal** [comment]
Yes, my scenario is when there's already a config file for ddev.

I suggest that when `ddev start` runs, before any new file is created, it will check if `.ddev/.gitignore` exist already, if not - it will create it.

That way, if `ddev start` fails, it won't surprise the user with so many changed files.

**Comment by rfay** [comment]
But `ddev start` already has this behavior... If you have run `ddev start` it creates the .gitignore.

**Comment by shaal** [comment]
In my experience, when having config.yaml in the repo, and running `ddev start`, there are 100 files (in `.ddev/` directory) that `git status` would report.

**Comment by shaal** [comment]
Here's how you can replicate this -

Open DrupalPod in gitpod workspace.
In terminal, run:
* `git clean -fdx` (will remove everything that scripts created, which mean ddev won't be able to start)
* `ddev start`
* `git status`

You'll notice that there is no `.ddev/.gitignore` file.
That is why I suggested this change. Creating the `.ddev/.gitignore` file at the beginning of `ddev start` would mean that even when the process of starting ddev fails, the user won't be surprised by so many changed files, that the user doesn't really need to worry about anyway.

**Comment by rfay** [comment]
`rm .ddev/.gitignore && ddev start` sure creates the .ddev/.gitignore for me. Could you recreate your setup with a fresh site?

Have you perhaps `settings_management_disabled: true`? Or set project type php?

**Comment by shaal** [comment]
I created a minimal repo to to reproduce the issue:
https://github.com/shaal/test--ddev-start-no-gitignore 

Open in Gitpod to see the problem -
https://gitpod.io/#https://github.com/shaal/test--ddev-start-no-gitignore

**Comment by rfay** [comment]
I checked out your repo and did a `ddev start` and it immediately created all the things including .ddev/.gitignore, and `git status` was clean.

I tried your gitpod, which fails because of port availability, and I can get your result. And of course after `ddev config --http-port=8080 --https-port=8443` it works fine and creates the .ddev/.gitconfig

So perhaps your issue was trying to say "Generate the gitignore before any possible error can occur and abort the `ddev start`"? 

Can you talk a little bit about why we should anticipate failures, and why we should care whether git is clean when doing a failed start?

**Comment by rfay** [comment]
I think the best way to fix this issue is to 

1. Change the .gitignore to a static file, included in the .ddev creation if that's possible. It may not be possible because the logic checks to see if things are #ddev-ignored.
2. Move the gitignore creation into PopulateExamplesCommandsHomeadditions(), (and rename it). It would be good to refactor this function so it does all the .ddev creation possible. There might be some other things. The one problem here is that PopulateExamplesCommandsHomeadditions() actually doesn't do anything if ddev is run outside a project directory.

**Comment by rfay** [comment]
This was worked on in https://github.com/drud/ddev/pull/3257 - For some reason the commit that would have moved that stuff to early in start was reverted back, https://github.com/drud/ddev/pull/3257/commits
