### ISSUE TITLE
Solidify external communication channels

### ISSUE THREAD

**Issue by cyberswat** [drud/ddev#324]
## What happened (or feature request):
It would be helpful if there was a mechanism for end users to communicate more directly with other community members to get help with problems and collaborate on ideas.  We would like to be as broad as possible and not exclude people by focusing to narrowly on a specific community, but that may be difficult to do.  One suggestion we have had is to create a slack room in broader community teams.  This works well with the Drupal slack teams https://www.drupal.org/slack, but less well with the WordPress slack teams https://make.wordpress.org/chat.  Initial testing allowed us to create a #ddev room in Drupal's slack, but not in WordPress.

There are a few questions we should address before pushing this too much farther than it has already gone.
- Do we want to use Slack as a medium for open chat-like communication?
- Are rooms in larger communities appropriate or should we try to have our own?
- How do we message and communicate that these avenues for communication exist.
- How responsive should we expect our internal team to be in these rooms?

**Comment by rickmanelius** [comment]
Right now we have the following ways:

* GitHub issue queue (accessible to anyone with a GitHub Account)
* Twitter (accessible to anyone with a Twitter Account)
* Slack: Drupal #ddev (accessible to anyone that registers)
* Slack: TYPO3 #ddev (accessible to anyone that registers)
* Stackoverflow (although we do not actively monitor).

At this point, this seems like it's working. We probably will need to evaluate in the future because joining one Slack room per community will eventually become untenable and it might exclude parts of the community that won't use Slack. However, we always have GitHub as the ultimate source of truth.
