### ISSUE TITLE
Make WSL2 setup for Windows easier

### ISSUE THREAD

**Issue by dennisameling** [drud/ddev#3277]
**Is your feature request related to a problem? Please describe.**

I'm currently working with one of Mautic's contributors to get WSL2 + Homebrew + DDEV set up on their machine. It made me realize that the process could be automated more.

**Describe the solution you'd like**

What I'd love to have is a script that helps Windows users get DDEV set up for them by simply following some instructions.

Something like `ddev setup windows-wsl2` (from an admin command prompt) which will then do the following:
- Check if the user is running Windows 10 2004 or later (older versions are out of support and harder to set up)
- Check if Chocolatey is installed. If not, [run its installation script](https://chocolatey.org/install#individual)
- Check if WSL2 is installed. If not, run `wsl --install` --> this will install Ubuntu 20.04 as well
  - Note: this requires a reboot, so we might have to store the DDEV installation state somewhere to continue where we left off.
- Check if Docker Desktop is installed. If not, run `choco install docker-desktop`
- Install Homebrew in WSL2 with `wsl --exec ..... (steps from Homebrew website)`
- Install DDEV in WSL2 with `wsl --exec "brew install drud/ddev/ddev"`
- Manage /etc/hosts on the Windows side when necessary (additional_fqdns, no internet, etc) (#3818)

Please let me know how that sounds to you. I'm happy to make the script. It would likely be in PowerShell, but I don't want to bother you with another maintenance burden if PS is something you normally never work with. Could probably make it in Go, but that's new to me so will take some time to dive into. That'd make it a lot easier for you to maintain though, I assume.

**Describe alternatives you've considered**

Simply following the steps at https://ddev.readthedocs.io/en/stable/#installation-or-upgrade-windows-wsl2 manually 😊 

**Additional context**

N/A

**Comment by rfay** [comment]
Definitely agree, of course. It also might be possible to do it with a Windows-side installer?

**Comment by tyler36** [comment]
Unfortunately, they are tying some of the new features like WSLg to Win11 only. This feature wont affect DDEV but might indicate an embrace-extend-extingish plan for WSL moving forward. Still, it's another install option.

I think a choco install should be the preferred "happy-path" for the script though.

**Comment by rfay** [comment]
Resource: https://github.com/kaisalmen/wsltooling

**Comment by rfay** [comment]
One option here is to maintain a preconfigured WSL2 distro for ddev. Then with just a little work on the host side everything would be set up.

**Comment by nico-loeber** [comment]
I disagree on the idea of a preconfigured WSL2 distribution for ddev. At least this wouldn't fit my setup.
I use a Ubuntu WSL distribution as my primary environment for development. I run ddev, node and other programs in there. Also my SSH keys and config are located there. 
A pre configured DDEV Distribution wouldn't have access to any installed software, enviroment variables, keys or anything else from your primary environment. Also performance will suffer if you run multiple distributions in the background.

I also think the setup of ddev should be simplified and I am already working on some ideas on how to do so but this isn't easy because the ddev installation process (via installation.sh script) already bundles a lot of stuff. Some require elevated rights some not, some are also neccessary for updating ddev, some only for the initial setup.
This complexity makes it very hard to streamline the process in my opinion.
The setup of WSL (A windows feature for developers) should definitly not be part of any ddev installation script as it is very specific to windows and has nothing to do with ddev itself.
I totally agree that the setup within WSL should be as simple as possible but with the installation script it already should be.

- Install WSL (Nothing ddev has to care about. Use the windows store, the wsl --install command (Ubuntu only), or take the manual way to install a custom dirstribution)
- Provide docker (By Docker Desktop on host, or docker inside wsl, also independed to ddev)
- Run the install script

And you should be done.

Also installing choco is not required for ddev nor docker desktop, its just ONE way to install docker desktop. You can also just download the installer. 
I like choco much, but I am not a fan of installing it in an automated script just to download ONE dependency. It is your decission weather you manage your Software via choco automatically or if you prefer to keep them up to date on your own.

Currently I am working on DDEV Integration Plugin for PHPStorm and WebStorm. On my roadmap is an automatic initial installation as well as update of ddev on all OSs including WSL by just clicking the "Yes, please install it" button in the IDE.
The feature is not ready yet because I have some trouble with the elevated rights necessary for the mkcert setup but this might be an alternative for the setup within WSL too. Only for PHPStorm users though.

We should try to reduce complexity wherever possible and this includes the segregation of concerns. WSL Setup and Windows package management should not be mixed with the ddev setup in my opinion.

**Comment by rfay** [comment]
Thanks for the great feedback. 

I'm thinking that Docker Desktop should not be part of the future of WSL2, just use docker inside the WSL2 distro.

**Comment by webseppel** [comment]
I feel like the installation process is a little complex for Windows users especially with all the different install options like install ddev on traditional Windows or inside WSL2, oder docker with Docker Desktop or inside WSL2. I think this could be described more clearly in the docs: When is this installation method recommended?

Also I think having to chose all the options in the ddev Windows installer @dennisameling mentioned would work great. Also you could have the option to install a wsl2 distro yourself and use that in the installer or install a new one preconfigured by the installer.

**Comment by rfay** [comment]
This is fixed in several PRs that go into v1.21.4, including full scripts for both Docker Desktop and docker-ce installations. I'd love to have a GUI installer, but that will wait.
