### ISSUE TITLE
mutagen status is not in sync with mutagen monitor

### ISSUE THREAD

**Issue by froemken** [drud/ddev#3280]
**Describe the bug**

Command `ddev mutagen status` is not in sync with `ddev mutagen monitor`

**To Reproduce**

Start a project, open terminal and start command `ddev mutagen monitor`. After a second or two monitor will stop reporting anything as there is nothing more to do. Now start a second shell, open the same directory/project and execute command `ddev mutagen status`. You will see that executing this command will start some reports in monitoring shell. Status catches a random line of monitor report and echo it as status.

**Expected behavior**

If monitors last report is `Status: Watching for changes` and I execute status command in a second shell I expect `Watching for changes` instead of `scanning for files` or whatever.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: MacBook Air M1 with macOS Big Sur
- Docker Desktop version if on macOS or Windows: 3.6.0
- ddev version information: v1.18.0
- Do you have any custom configuration (nginx, php, mysql): no
- config.yaml contents for the misbehaving project (the part before the comments)

```
name: typo3104
type: typo3
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: true
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2"
web_environment: []
```

Nice greetings

Stefan

**Comment by rfay** [comment]
Thanks for looking closely!

ddev uses the `mutagen sync list` command to determine when it's safe to continue on during `ddev start`. https://github.com/drud/ddev/blob/920d65e24eca16491d77dfde93a468f1fe987743/pkg/ddevapp/mutagen.go#L223-L256

`ddev mutagen monitor`, however, is  a wrapper on `mutagen sync monitor`, which doesn't have exactly the same behavior.

So if that's a bug (it would be hard to convince me) then it's a bug in mutagen, but I think it's just two different ways of looking at things.

Kudos to you though for looking carefully and working to understand the whole process. I hope others are careful like you, because I think mutagen needs to be understood thoroughly for real success, as discussed in https://ddev.readthedocs.io/en/stable/users/performance/#caveats-about-mutagen-integration

**Comment by rfay** [comment]
No response, but happy to continue the conversation here or elsewhere. Please do continue it if you think this is important. Closing for now.
