### ISSUE TITLE
Differences between arm64 and amd64 npm packages can cause different npm behavior on M1 and amd64 computers

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#3288]
I have a DDEV project that involves a custom DockerFile that installs a specific version of npm. 

Our team has 2 developers, both on Mac OS X, both using DDEV 1.18.0, one with an M1 Mac and one with a non-M1 Mac.

As part of our local deployment process, `npm install` is run in a couple of different apps for the project. It was failing on the M1, but not on the non-M1 Mac.

We tracked the issue down to (we think) different web container images, both tagged with 1.18.0.

On the non-M1: 

`drud/ddev-webserver                v1.18.0                    1e45807db7e2   7 days ago       1.09GB`

On the M1: 

`drud/ddev-webserver                v1.18.0                           a38acc515b19   7 days ago      1.05GB`

It seems that the M1's image has a change in it that doesn't include some packages (python2, make) that npm is depending on. We were able to work around the problem by adding `webimage_extra_packages: [build-essential]` to our .ddev/config.yaml, but not after a bunch of time sleuthing.

We thought for awhile that this was an M1 issue, but after seeing the different Image Ids on the web server images, we think the issue is unrelated to the M1 and instead was caused by a change to the web server image - are we on the right track?

We found #3271 which seems similar...

-mike

**Comment by rfay** [comment]
No, sorry, not on the right track :) The images are different, but built from the same source. v1.18.0 (and all images for the last 18 months) are [multi-architecture images](https://www.docker.com/blog/multi-platform-docker-builds/), meaning they're tagged the same, but everything in them is different architecture. So they have different hashes. 

python2 is not included in anything based on Debian 11 Bullseye, so if you're looking for it you'll  have trouble finding it. It's completely obsolete.

If you can be specific about the problem you're having the the results you're seeing, I can chase, but it looks to me like the problem is different npm packages upstream for arm64 vs amd64. There are many packages not built for arm64. So probably when you add build-essential to your image, you allow npm to build whatever you're having trouble with from source, as opposed to getting it as a prebuilt package. 

#3271 was definitely caused by a difference between ddev v1.18.0 (ddev-webserver based on Debian 11 Bullseye) and ddev v1.17.7 (ddev-webserver based on Debian 10 Buster) but not related to your issue I don't think... but thank you so much for looking for it!

**Comment by ultimike** [comment]
@rfay Ah - okay - differences from arm64 vs. amd64.

thanks,  
-mike

**Comment by rfay** [comment]
Yay, let me know if you need any help.
