### ISSUE TITLE
ddev should say "docker isn't running" instead of "<shell command> not found" if docker isn't running

### ISSUE THREAD

**Issue by chrisfromredfin** [drud/ddev#3336]
**Is your feature request related to a problem? Please describe.**
As a developer, I get confused when ddev tells me "Error: unknown command 'drush' for 'ddev' / Run 'ddev --help' for usage."

I've found this happens when Docker Desktop isn't running.

**Describe the solution you'd like**
I'd rather see an error message like "Docker isn't running."

**Describe alternatives you've considered**
DDEV could also automatically prompt me to start Docker and do it for me. ;)

**Comment by JPustkuchen** [comment]
Hi @chrisfromredfin, just ran into a similar problem here: https://github.com/webksde/ddev-vscode-devcontainer-drupal9-template/issues/76

For me the problem was, that ddev said
> Error: unknown command "<custom command>" for "ddev"

and I was looking for reasons in the .ddev folder from our project, but instead the reason was, that I missed to start Docker Desktop.

It would be nice, if ddev could check if the environment is okay, e.g. docker is running properly. As otherwise also custom commands from the .ddev directory aren't properly detected.

**Comment by mikebarkas** [comment]
I created a list of commands that can run without Docker and compares it to what command the user provided.

This new function `commandRequiresDocker() `is implemented in root init to catch before custom commands are added.
