### ISSUE TITLE
DDEV databases are stored in docker volumes, not in the project directory

### ISSUE THREAD

**Issue by Vacilando** [drud/ddev#3338]
One of our local Drupal 9 projects is broken after importing an old database. We cannot import the correct database from production because the project has not been released yet.

We do however have a backup of the project folder, with everything in it, from a few days before. 
The idea would be to start ddev in the old folder, export db dump, and then import it in the current project folder.

Steps we tried:

1. We renamed the broken project folder to from "project" to "projectBROKEN".
2. We retrieved the backup and named the folder "project".
3. We did ddev start in the backup folder and it started. However, when looking at db log in Drupal it's clear that it's still the current database, not the older database.

What are we doing wrong? How can we get a db dump from a backup of a ddev project folder?

**Comment by Vacilando** [comment]
@rfay, what's the suggested way to backup database when using a hook?

I tried
```
hooks:
  post-start:
    - exec: "ddev export-db --file=../backups/TIMESTAMP_PROJECT_db.sql.gz"
```

But it results in error 
> bash: ddev: command not found

Did not find an example in https://ddev.readthedocs.io/en/stable/users/extending-commands/ - hence my question.

**Comment by rfay** [comment]
You would use `- exec-host: ddev export-db --file=../backups/TIMESTAMP_PROJECT_db.sql.gz"` - because `exec` is for things inside the container. 

But please don't put random things like this in closed issues. Support options are at https://ddev.readthedocs.io/en/latest/#support-and-user-contributed-documentation - lots of options there. I'm listening in all of them.
