### ISSUE TITLE
How should I install core-dev version of drupal? (docs?)

### ISSUE THREAD

**Issue by bradbulger** [drud/ddev#3356]
I believe that at least as of Drupal 9 the basic core installation in composer is missing development functionality like phpunit. I only vaguely understand this, but I gather that now for development options, you should use drupal/core-dev rather than drupal/core?

Given that probably a majority of people using ddev and Drupal are doing development, it might make sense to either make that the default, or make it some kind of easy obvious choice.

**Comment by rfay** [comment]
This really doesn't have to do with ddev, but using a reasonable composer flag is a nice thing. I'm open to an additional quickstart in the docs, but as you see there's nothing about ddev in the Drupal 9 quickstart, https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart - it's all about just doing what Drupal needs.

**Comment by rfay** [comment]
You'll want to read https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-adding-drupalcore-dev which explains how to do this.

When using ddev you'll normally use `ddev composer` instead of just `composer`. You can also `ddev ssh` and just execute the commands in the Drupal manual as is. 

If you're talking about how to do actual core development, most people do a [git clone](https://www.drupal.org/project/drupal/git-instructions) and then a `composer install`. So for that approach you would use the [Drupal 9 git clone example](https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-git-clone-example) and go from there. 

Of course, how people set up their project is tailored to their own needs - whether they're doing sitebuilding or module development or whatever else. And ddev doesn't tell you what to do with these things, it just provides the tools for you.

Since the basic recommended technique for Drupal is [drupal/recommended-project,](https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-drupalrecommended-project) that's what we put in the [Drupal 9 Quickstart](https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart) and I think it's probably the right choice.

I hope you already know that DDEV is not a Drupal tool, it's a general-purpose development setup with many CMSs explicitly supported and loads of things you can do with it. But it can't tell everybody what to do with everything they have to do with their CMS.

Closing this for now, happy to continue the conversation here or elsewhere.

**Comment by rfay** [comment]
Some related links, 

* https://drupal.slack.com/archives/C5TQRQZRR/p1636338925316600
* https://www.jeffgeerling.com/blog/2020/install-drupal-coder-and-php-codesniffer-your-drupal-project-lint-php-code

> composer require --dev drupal/core-dev which includes drupal/coder and phpunit/phpunit etc
You can add this package for auto configuration dealerdirect/phpcodesniffer-composer-installer

**Comment by bradbulger** [comment]
The composer templates documentation is probably the sort of thing I had in mind, it's not something I'd seen before. It seems like this is more of a docs-for-Drupal-developers issue than ddev per se. Thanks for the very helpful response!
