### ISSUE TITLE
[docs] Add mention on how to show dot files on Mac to phpstorm config section

### ISSUE THREAD

**Issue by arafalov** [drud/ddev#3406]
In section 3.5 of https://ddev.readthedocs.io/en/stable/users/topics/phpstorm/ , the instructions ask to pick a file in a dot directory (.ddev). However, PHPStorm Mac interface does not seem to allow to just type it in and dot files are hidden by default in file browser window.

I was able to find key combination that seems to make them visible (Command+Shift+Dot), but it took a while, as usually I work with those files and directories from the command line.

It may be worth mentioning something about it, in the instruction.

Also, maybe the nested lists could be letters instead of - also - numbers (3.e, instead of 3.5) to make it clearer where the long sub-steps end.

I am not sure if Windows would have a similar issue.

**Comment by arafalov** [comment]
This on on - ancient? - MacOS Mojave (10.14.4). I don't have a more recent MacOS to test whether the issue is still there. Likely, it would be.

**Comment by rfay** [comment]
macOS has had this key sequence to show dotfiles since the beginning of time (and has hidden dotfiles since the beginning of time)

Windows does not do this.

Not sure if we should be telling people basic finder knowledge, but I know that if you hit this we should give a hint.

The nested list seems to be "just what mkdocs does" - I don't like it either. Would be interested in a way to get numbers.

BTW, in finder preferences, you can choose to always show hidden files. I guess I always have mine set up that way.

PR would be welcome.

**Comment by rfay** [comment]
A PR is welcome, just click the pencil icon in the upper right of the docs page, thanks!
