### ISSUE TITLE
Add a URL field to config, make the router optional

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#342]
## What happened (or feature request):
Feature request, touching on a few related concerns. #321 is the motivation for this request.

Currently, all ddev sites get a url at <sitename>.ddev.local. We provide a way to run on a port alternate from 80, but it is not very intuitive. We also assume that users will want a domain like the one we provide, while there are valid use cases for throwing a site on localhost at an available port.

## What you expected to happen:
I think we should introduce a URL field to the config.yaml to be used to address these concerns. The field would allow users to define the URL the site is served from in the following ways, achieving the following result for each way:

- Set to "localhost". The router is not used for the site, and instead we output the published port of the web container as the site URL. e.g. after ddev start: "Your application can be reached at http://localhost:4379
- Set to "localhost:8089". The router is not used for the site, and port 8089 is used to expose the site, provided it is available.
- Set to "[sitename].ddev.local:8089". The router is used for the site, port 8089 is used to expose the site, provided it is available. e.g. after ddev start: "Your application can be reached at http://[sitename].ddev.local:8089"
- At this point we may as well allow the URL to be defined how the user wants, unless there's a reason not to that I'm not seeing. e.g. user can have there site at http://sitename.banana.dev or whatever.

This would entail changes to the prompts in "ddev config" to add a URL prompt, and list the possible options for the user. I think we should still provide [sitename].ddev.local as the default value.

I suspect this approach would also entail changing configurations in the docker-compose.yml. We will need to come to a decision on if we are going to control / maintain this file, or allow users to configure it.

## Related source links or issues:
#321
#323

**Comment by rickmanelius** [comment]
Hi @tannerjfco. I see your point in making this very flexible. Question: does it make sense to add this to the `ddev config` step? It seems to me that providing a default and then a link to customizations within the config.yml would be the most useful for those that care enough to make this modification.

**Comment by tannerjfco** [comment]
We wouldn't necessarily need to add it to ddev config prompts if we didn't want to, and linking to documentation of the various configuration options would be more approachable than trying to summarize the options on a prompt.

**Comment by beeradb** [comment]
I feel like these changes should probably be discussed and considered in isolation, as I feel like they can be implemented independently, and I don't think there's a huge driver to combine them.

<dl>
<dt>Hostname configurability</dt>
<dd>I think there's value in this feature. I do feel that it should probably not be surfaced in `ddev config` and just be a documented key in the yaml config if we were to do it. My biggest concern here would just be that without additional legwork we can't stop users from doing silly things, like trying to use the same hostname on every site. We also lose some guarantee that a committed config which has a hostname would be portable to another developers machine. I think the risk there is small but just pointing out that it does exist.</dd>

<dt>per-site optional usage of router</dt>
<dd>I have some concerns about this, at least right now. I think this potentially creates a lot of testing and support overhead if we allow so many configurations. So much so, that I'm fairly sure if this feature landed how people had their router configured would likely turn into a standard question for most support requests. I haven't looked at the port configurability work yet since I was out of town last week, but my strong preference would be that if it's not very intuitive that we rally around that feature and provide the right messaging and context to help make it more intuitive. 

I believe this feature would also have a high likelihood of creating portability issues between developer machines, as there is no guarantee an arbitrarily chosen port (such as 8089) would be available on another developers machine. We also have the same issues here as we do for hostnames, which is that we'd need to do a lot of legwork to ensure sites didn't conflict with each other (i.e. someone using port 8888 on all their sites).

All that being said, I wouldn't be dead set against this if it was driven by feedback and a clear need being demonstrated by users, but I do feel like we should be cautious and not go down this road unless we really need to.
</dd>
</dl>

**Comment by rickmanelius** [comment]
Flagging w/"needs decision" because there is an open discussion of how much do we open up for the end-user and is this truly valuable or does it create more issues than it solves.

Counter proposal might be to detect when a user it trying to use a custom port and prompt/push for a more consistent approach. Just spit balling at the moment...

**Comment by tannerjfco** [comment]
These changes can certainly be considered independently, but the primary motivation I had in combining them was to provide an intuitive way for the user to define what URL they access their site from.

Hostname configurability concerns: I agree with not exposing the config prompts, and treating as optional config in the yaml. It wouldn't be hard to validate the hostname when config is read, and similarly it wouldn't be too difficult to check that the hostname isn't in use by another ddev site, if we wanted to do so. The risk for reduced portability and invalid configuration is indeed higher, but I think acceptable when being treated as an optional configuration.

per-site optional usage of router concerns: We can try to explain HTTP_EXPOSE better, but I don't have a lot of confidence a better explanation will clarify. That's certainly not to say the url key idea is the only way to solve it though. Re: overhead, my thinking for this scenario is that if a localhost url is defined, then we simply skip router start/stop. If the router was being used for a site, and if a site was started that didn't use it, I don't think it would be problematic to still have the router configure for the site that isn't using it. The router could configure like the site was using it, but we output the localhost url to the user and they interact with the site that way.

My larger concern re: configuration on this would be in terms of how we handle changing the port configurations for the site's compose. If we decide to manage the main compose file as in #343, we could potentially write the main compose to our whim. If not, we could use additional compose files to override the configurations of the main compose, but additional files for this concern could be confusing to the user.

**Comment by rfay** [comment]
Related and possibly sort-of-duplicate: [#376: "ddev describe" should report information about the routed and unrouted web ports ](https://github.com/drud/ddev/issues/376)

**Comment by rickmanelius** [comment]
I'm moving this v1.1.0 because I don't see this a release blocker for v1.0.0 and this will warrant additional discussion at an architecture/end-user level.

**Comment by rickmanelius** [comment]
I feel like this needs a scheduled conversation to unblock and determine the true priority. Also, the related/linked issues might determine a different solution/path forward on this.

**Comment by rickmanelius** [comment]
Relating to a recently filed issue regarding multiple domain support https://github.com/drud/ddev/issues/620

**Comment by rfay** [comment]
In https://github.com/drud/ddev/issues/796, currently scheduled, we're going to show the ephemeral port as one of the url options in ddev describe I think this does enough of the requested functionality.  Also, in the intervening time since this was filed we've added additional hostname support and will probably add TLD changing and arbitrary hostnames as well. Closing.
