### ISSUE TITLE
Add daemon support and http/s proxying for Node JS

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#3456]
**Is your feature request related to a problem? Please describe.**
As a front-end dev that's used DDEV for Drupal development, DDEV is _fantastic_ for the standard, monolithic PHP CMS, but takes some work to get things really well customized and set up for any node projects. This work might be "simple" in terms of Docker config or server setup, but as someone that doesn't have much experience in the devops/sysadmin world, this is frequently unfamiliar and sometimes feels unattainable without a step-by-step recipe.

With the rise of decoupled/headless CMSes, it would be nice to have better support of node surfaced to the ddev config file so average users can setup and maintain this type of project with a simple local development environment. In my mind, the primary things I would need:

1. Be able to pick a node version per #2651.
2. Be able to specify a npm/yarn command (and the relevant location for that command). Ideally this would be able to run as a background process, returning control of the CLI to me. I've tried running a node server via a hook before and since the process doesn't complete until I kill the server, the ddev start command never finishes
3. Be able to proxy a ddev domain or subdomain to the port that the command starts.

**Describe the solution you'd like**
I'd like to be able to run `ddev start` and have it do the following:
- Use the correct version of node
- Spin up my Drupal/Wordpress/TYPO3/Magento/PHP backend
- Spin up my gatsby/next.js/other node app frontend
- Complete the ddev start command, and let me continue to use the same terminal window
- Serve both the drupal backend and my JS frontend at `.ddev.site` urls

**Additional context**
If ddev starts to venture into supporting decoupled JS frontends, I wonder if there's interest/value in supporting JS backends like Strapi or Keystone CMSes

**Comment by rfay** [comment]
nodejs has to run in a particular directory, true? How would that be specified and what's a good example?

**Comment by rfay** [comment]
Would you be willing to provide an example project (just a dummy simple project) that could be used for testing this? You can specify manual steps required.

**Comment by andy-blum** [comment]
Typically yes. My personal site is running a [Drupal 9 backend ](https://github.com/andy-blum/portfolio-drupal) and a [Gatsby frontend](https://github.com/andy-blum/portfolio-gatsby).

On my local machine, these two respositories are stored together in `~/Sites/andy-blum.com/`, so I would imagine that would be the new home for the `.ddev` directory

```
Sites/
|-- andy-blum.com/
|   |-- .ddev/
|   |-- drupal/
|   |-- gatsby/
|-- example.com/
```

I assume you can do the Drupal one on your own. The Gatsby side of things would need a couple steps:
1) Clone the repo.
2) Update the `baseUrl` value in `gatsby-config.js` to point to your DDEV site's URL
3) `nvm use && npm install && npm start`

That will _probably_ fail because gatsby will try to pull in nodes that don't exist in your DDEV version. If you leave the `baseURL` value alone though, the live drupal cors.config should allow you to pull in everything form it's jsonapi

**Comment by rfay** [comment]
Thanks! Your personal andy-blum.com site isn't perhaps open-source on github or somewhere is it?

**Comment by andy-blum** [comment]
The links in my previous comment should take you the drupal/gatsby repos

**Comment by rfay** [comment]
https://github.com/drud/ddev/pull/3612 allows changing nodejs version to 12, 14, 16, 17, still defaults to 16. Is that going to be adequate? Would love some testing on this, although I think if you're happy with that selection it's probably good enough. That PR doesn't attempt to do any of the more ambitious things listed here.

**Comment by scotthooker** [comment]
https://nodejs.org/metrics/ - that selection is plenty good enough IMO 👍

**Comment by rfay** [comment]
In v1.19 you can set nodejs version to any supported version, and `ddev nvm` now provides every other version.

For v1.20, we need to be able to do numbers 2 and 3 of the OP: 

2. Be able to specify a npm/yarn command (and the relevant location for that command). Ideally this would be able to run as a background process, returning control of the CLI to me. I've tried running a node server via a hook before and since the process doesn't complete until I kill the server, the ddev start command never finishes
3. Be able to proxy a ddev domain or subdomain to the port that the command starts.

Some discussions to take place.. 

* What kinds of things do we want to start? What are some examples?
* How should we configure them?
* Do they require specific environment?

Adding them to ddev-router's HTTPS_EXPOSE is not very hard.

**Comment by hchonov** [comment]
Based on the comment from @pixlkat I've opened a PR that adds basic support for running a Node.js app with DDEV. I've tested this successfully with a NextJS application.

See https://github.com/drud/ddev/pull/4006

**Comment by mandrasch** [comment]
Hey, nice to see work on that, thanks to all the people involved here! 👏 

Randy asked me to add some brief thoughts because we chatted a bit [on Discord](https://discord.com/channels/664580571770388500/997785642056568952/998357709864837241).

Generally I guess there are two main approaches regarding scope? 
a) nodejs bundlers, such as webpack and vite, which only run dev servers, but won't be used as live server in production
b) 'real' nodejs servers which also run on production to serve requests (just like a PHP server would), in frameworks this is called SSR (See e.g.https://kit.svelte.dev/docs/appendix)

Here would be a quick list of things I would consider relevant for a NodeJS implementation in DDEV:

1. What is the scope for this NodeJS project type?
2. Can DDEV users easily see if the local (dev) node server is running?  (status)
3. Can DDEV users easily check for error messages in CLI output of (dev) node server?
4. Is the node (dev) server `exit on error` case handled, e.g. when users change to a wrong configuration and the local dev server terminates? (vite for example reloads config automatically for example and can terminate at anytime)
5. Can DDEV users easily stop the local dev server if they want to install packages or run other commands such as `npm run production`, `vite preview`, etc.?
6. Can DDEV users choose freely between npm, yarn (or pnpm or whatever comes next)?
7. Some frameworks such as Angular have their own CLI as global package (https://angular.io/cli), is this possible to use?
8. Is `Server Side Rendering (SSR)` supported for most frameworks (NextJS, NuxtJS, Gatsby, SvelteKit, Astro, Remix, Eleventy, etc. etc.)?
9. What is the recommended approach for 'mixed PHP / NodeJS use cases'? Is it easy to decide for users how they should create new projects? As PHP or NodeJS? (E.g. Laravel PHP used a combination with LaravelMix (Webpack) bundling, now via https://github.com/laravel/vite-plugin with `@vite`-tag. Laravels Inertia can be used with PHP + NodeJS SSR https://inertiajs.com/server-side-rendering)
10.  Open question: With what NodeJS software should this new feature be tested? What are the major ones, such as `express` server, etc.?

Keep up the good work, cheers!

**Comment by hchonov** [comment]
> What is the scope for this NodeJS project type?

With my PR I am covering the use case of a NextJS decoupled app that lives in its own repository and retrieves the data from the backend via APIs. I think that we can start with one use case and go further adding support for other use cases if you agree. If needed we can introduce the type nextjs instead of node in order to make it more clear that we currently only support nextjs apps, but since probably the way of starting applications might be pretty similar I am not sure if it worth it to make the separation?

> Can DDEV users easily see if the local (dev) node server is running? (status)

Not sure how this is possible for the webserver, but if you point me to it I will adjust it also for the node app :).

> Can DDEV users easily check for error messages in CLI output of (dev) node server?

Since I've just added support for supervisor the logs are mixed together with the one of the webserver and can be observed the same way as for the webserver through `ddev logs -s web`.

> Is the node (dev) server exit on error case handled, e.g. when users change to a wrong configuration and the local dev server terminates? (vite for example reloads config automatically and can terminate at anytime)

This is handled by the supervisor the same way as for the webserver and it uses the same configuration.

> Can DDEV users easily stop the local dev server if they want to install packages or run other commands such as npm run production, vite preview, etc.?

Same as with the webserver again, here you would need to do ddev restart unless the app breaks during the changes and the supervisor restarts it itself. But for changing the command you would have to do that in the config.yml file that requires a ddev restart.

> Can DDEV users choose freely between npm, yarn (or pnpm or whatever comes next)?

See the configuration below for config.yml. ddev does not manage the installation as it does not do it for PHP projects either.

> Some frameworks such as Angular have their own CLI as global package (https://angular.io/cli), is this possible to use?

You define the command that supervisor has to run in config.yml, so this should be possible.

> Is Server Side Rendering (SSR) supported for most frameworks (NextJS, NuxtJS, Gatsby, SvelteKit, Astro, Remix, Eleventy, Angular Universal, etc. etc.)?

I am not sure how to answer this. Isn't this how you configure your application? Do not see a reason that it should not be supported.

> What is the recommended approach for mixed PHP / NodeJS use cases? Is it easy to decide for users how they should create new projects? As PHP or NodeJS? (E.g. Laravel PHP used a combination with LaravelMix (Webpack) bundling, now via https://github.com/laravel/vite-plugin with @vite-tag. Laravels Inertia can be used with PHP + NodeJS SSR https://inertiajs.com/server-side-rendering)

Right now with my PR I am adding support only for monolithic node repositories. A mixed env would require much more complex setup and I would prefer to be discussed in a separate issue and here to focus only on node applications.

> Open question: Additionally I guess it depends heavily on how the project repositories are structured? Decoupled or some people might want to use Monorepos?

Already answered this covers only monorepos :).

> Open question: With what NodeJS software should this new feature be tested? What are the major ones, such as express server, Strapi and Directus CMS, etc. etc.?

I am using NextJS with express and starting it with the configuration below, where I am defining the port on which to start through an environment variable that later access in my app.

------

Here is the configuration that is needed with the current PR version to start a NextJS app with `express`:
```

name: my-node-app
type: node
webserver_type: nginx-fpm
omit_containers: ['db', 'dba']
nodejs_version: "16"
web_environment:
  - NODE_ENV=development
  - PORT=3000
node_cmd: node server.js --prefix /var/www/html
```

**Comment by rfay** [comment]
Great to have your thinking @hchonov - this comment wasn't really aimed at your or your PR, but rather the problem in general, and it's lovely to have you interacting about the situation you have!

**Comment by hchonov** [comment]
One more way of starting the node app without using the supervisor service is using the `forever` package, in that case one needs only an adapted nginx config that acts as a reverse proxy as described in https://github.com/drud/ddev/issues/3456#issuecomment-1168935571

Then you can use a setup like this and manage the node app using the forever command from within the web container:
```
name: my-node-app
type: php
webserver_type: nginx-fpm
omit_containers: ['db', 'dba']
nodejs_version: "16"
disable_settings_management: true
web_environment:
  - NODE_ENV=development
  - PORT=3000
hooks:
  post-start:
    - exec: npm install forever -g
    - exec: mkdir -p /var/log/node/
    - exec: forever -l /var/log/node/forever.log -o /var/log/node/out.log -e /var/log/node/error.log start server.js --workingDir=/var/www/html
```
