### ISSUE TITLE
Add "build-essential" application to web images for WingSuit support

### ISSUE THREAD

**Issue by lhridley** [drud/ddev#3461]
**Is your feature request related to a problem? Please describe.**

The WingSuit Kickstarter project for Drupal 8+ leverages Storybook to house components that integrate with a custom theme using UI Patterns.  Included in the Storybook portion of WingSuit are some scripts that are used to generate components as well as create the static Styleguide and Drupal integration components.

**Describe the solution you'd like**

For Storybook startup scripting to complete initializing the Storybook application, "build-essential" is an additional web image package that has to be added.  While this can be added in the config.yaml file, that file is project specific, and the package needs to be added for every project using Storybook.

**Describe alternatives you've considered**

Please consider adding "build-essential" to the list of packages included in the DDEV web image.

**Comment by rfay** [comment]
Hi @lhridley - Thanks for the idea. Unfortunately, if everybody added everything they wanted to the web image it would just be unwieldy. I just tested, and adding build-essential makes the ddev-webserver image 20% bigger, going from 1.08GB to 1.26GB. Since people can easily add it to fix their own issues with `webimage_extra_packages: ["build-essential"]` and since most people don't need it, I think it's better to leave things where they are.

Happy to continue the conversation here or elsewhere, but closing this for now.

**Comment by rfay** [comment]
Just checking on something you might not know - When you use `webimage_extra_packages: ["build-essential"]` it only has to install that the **first time you run ddev start**, it doesn't do it every time. It gets built into your project's custom web image.
