### ISSUE TITLE
Copy ~/.ssh/config to ddev when using ddev auth ssh

### ISSUE THREAD

**Issue by mieserfettsack** [drud/ddev#3492]
**Is your feature request related to a problem? Please describe.**
I use ssh and rsync inside ddev commands to retrive some data during the creation of local environment. I do not want to write connection data to repository. I would like to use hostnames from ssh config inside ddev commands in web container.

**Describe the solution you'd like**
ddev auth ssh should copy ~/.ssh/config to ddev container.

**Comment by rfay** [comment]
Unfortunately, most people's .ssh/config don't work inside the web container, because they point to specific keys, and the keys aren't copied inside there. 

However, you can easily put a .ssh/config into ~/.ddev/homeadditions/.ssh and it will work great. Just modify it for what you need and you'll always have it on every project. This is actually one of the examples in https://ddev.readthedocs.io/en/latest/users/extend/in-container-configuration/

**Comment by mieserfettsack** [comment]
Okay, I understand that just copying ssh config file could cause problems. You can close the feature request.

Just in case someone else found this and has the same question. I use these lines before running my ddev build scripts.

```
mkdir -p .ddev/homeadditions/.ssh
printf "UserKnownHostsFile=/home/.ssh-agent/known_hosts\nStrictHostKeyChecking=no\n" > .ddev/homeadditions/.ssh/config
cat ~/.ssh/config.d/ddev_staging >> .ddev/homeadditions/.ssh/config
```
Now I can use one of my ssh config files inside ddev container. It is important to prepent the those to lines to the ssh config.

**Comment by rfay** [comment]
For most people it's easier to put it into ~/.ddev/homeadditions (.ddev/homeadditions in the home directory) instead of the project .ddev/homeadditions - that way you only have to have it one place. 

Thanks!
