### ISSUE TITLE
.ssh/config file gets not updated

### ISSUE THREAD

**Issue by mieserfettsack** [drud/ddev#3494]
**Describe the bug**
.ssh/config inside the container gets not updated after ddev start.

**To Reproduce**

- I used a ssh config file within the ddev project folder inside .ddev/homeaddtions/.ssh/config previously.
- ddev poweroff
- I added a ssh config file to ~/.ddev/homeaddtions/.ssh/config
- I deleted the homeaddtions inside the project folder
- ddev start
- .ddev/homeaddtions/.ssh/config is created correctly with the content from ~/.ddev/homeaddtions/.ssh/config
- ddev ssh
- cat /home/MYUSERNAME/.ssh/config
- It is the old version.
- I can repeat this but inside the container the ssh/config is always the old one.
- I even deleted the file inside the container but after ddev restart it is still the old one

**Expected behavior**
.ssh/config file inside the container should be updated during ddev start.

**Version and configuration information (please complete the following information):**

DDEV-Local version      v1.17.7                                
architecture            amd64                                  
db                      drud/ddev-dbserver-mariadb-10.3:v1.17.7
dba                     phpmyadmin:5                           
ddev-ssh-agent          drud/ddev-ssh-agent:v1.17.0            
docker                  20.10.8                                
docker-compose          1.29.2                                 
os                      linux                                  
router                  drud/ddev-router:v1.17.6               
web                     drud/ddev-webserver:v1.17.7

**Comment by rfay** [comment]
First, please update to ddev v1.18.2, the current version. But it won't have anything to do with this. 

The default (in container) ~/.ssh/config is:
```
# Share known_hosts across all users of the ssh-agent
UserKnownHostsFile=/home/.ssh-agent/known_hosts
# In the container host key checking can be a problem with non-interactive composer, etc.
# Turn it off. When we upgrade to openssh 7.6 we can use the "accept-new" option instead of "no"
StrictHostKeyChecking=no
```

If you're seeing that in there, I'm not surprised.  But that's all that can be there between restarts, because it starts out with nothing there.

I don't actually understand your sequence. If I understand you did this:

1. You did `ddev poweroff`
2. You added a global ssh config, ~/.ddev/homeadditions/.ssh/config
3. You then deleted your project .ddev/homeadditions/.ssh/config in your project *before* `ddev start`
4. ddev start
5. You found the wrong /home/<you>/.ssh/config inside the container

Maybe you can start over with this. 

Please check to make sure you *actually* deleted the project `.ddev/homeadditions/.ssh` - Could you please show me `ls -alR .ddev/homeadditions` in your project directory?

Now when you recreate, put "PROJECT CONFIG" as the content of the project config file and "GLOBAL CONFIG" as the content of the global config file.

I think that will help you sort it out.

**Comment by mieserfettsack** [comment]
I deleted the file from my project folder: ls -alR .ddev/homeadditions/
```
.ddev/homeadditions/:
insgesamt 16
drwxr-xr-x  2 mdy mdy 4096  3. Jan 21:49 .
drwxr-xr-x 17 mdy mdy 4096  3. Jan 21:41 ..
-rwxr-xr-x  1 mdy mdy  166  3. Jan 21:41 bash_aliases.example
-rwxr-xr-x  1 mdy mdy  275  3. Jan 21:41 README.txt
```
 I am not seeing the default ssh/config file. I am seeing the last version of it before I moved my config to ~/.ddev. I changed the content inside ~/.ddev and this new lines are not beeing shown inside the container. But correctly created inside project after ddev start.
 
 I do not understand this line: `Now when you recreate, put "PROJECT CONFIG" as the content of the project config file and "GLOBAL CONFIG" as the content of the global config file.`

**Comment by rfay** [comment]
I was saying for a debugging strategy, instead of having the real contents inside both your global and project .ssh/config files, put "PROJECT CONFIG" and "GLOBAL CONFIG" in them. Then go through this process. 

The default /home/<you>/.ssh/config file I was talking about is the default inside the web container if you have nothing anywhere in any homeadditions. Why don't you start by getting to that point. 

1. Remove all your .ssh homeadditions from everywhere. `ddev restart` and you should see the default I showed you.
2. Now add the project .ddev/homeadditions/.ssh/config with contents "PROJECT CONFIG" and `ddev restart`. You should see that now inside the web container.
3. Now add a global ~/.ddev/homeadditions/.ssh/config with contents "GLOBAL CONFIG" and `ddev restart`. You should still see the project one inside the web container.
4. Now remove the project .ddev/homeadditions/.ssh/config and `ddev restart`. You should now see the global one.
5. Now you can put the real contents you want in the global config.

**Comment by mieserfettsack** [comment]
I updated to the current version of ddev. Now it works like a charm. 

Before I updated I tried this:

- create a new project
- ddev start
- ssh/config inside container is same as in ~/.ddev/
- ddev stop
- update ssh/config file inside ~/.ddev/
- ddev start
- It is still the old version

**Comment by mieserfettsack** [comment]
I do not know if it is worth to do some more investigations or just close it because it seems to be fixed in the current version.

**Comment by rfay** [comment]
Yeah, it hasn't ever changed, I don't think you'd be able to recreate with the old. But if it's working for you I'll close this.
