### ISSUE TITLE
Provide an 'other' apptype or make apptype optional

### ISSUE THREAD

**Issue by tannerjfco** [drud/ddev#359]
## What happened (or feature request):
We have aimed ddev at Drupal and WordPress developers to start, but we can probably run a bunch of other php applications with the stack we've put together. The question was asked at a recent meetup whether ddev can run other applications.

## What you expected to happen:
We should ensure people that are curious to try another php application on ddev are not blocked by our considerations for drupal/wordpress/tbd future supported apps. I think adding an 'other' apptype or similarly named option, or making the apptype value optional, would allow users to attempt running other applications without encountering roadblocks related to apptype.

Not knowing about the app would prevent config writing and import-files from being useful, but I can't think of any other functionality off-hand it would impact.

## Related source links or issues:

**Comment by rickmanelius** [comment]
We've added a generic "php" apptype since [v0.11.0](https://github.com/drud/ddev/releases/tag/v0.11.0) and we now suggest versus auto answer. I think this captures the spirit of this request. Eventually, we'll probably have an even more generic "generic" app type to support the broader, non-php community... but that will likely require a different issue.
