### ISSUE TITLE
ddev project has a 403 HTTP Forbidden error

### ISSUE THREAD

**Issue by Aandreba** [drud/ddev#3643]
## Run a Diagnostic and Paste Link Here
[Here](https://gist.github.com/Aandreba/63705c5430d3d9eab2e36318a31ad6ac)

## Describe the bug
I'm trying to initialize a new empty drupal9 ddev, but running ```ddev start``` yields a page that returns an 403 HTTP Forbidden error

## To Reproduce
For me, it's just running ```ddev start```

## Expected behavior
Running ```ddev start``` and it returning an address where I can start configuring a Drupal 9 website

## Screenshots
<img width="1440" alt="Captura de pantalla 2022-03-01 a las 10 07 02" src="https://user-images.githubusercontent.com/4247991/156139015-910bfc37-8f80-44b4-8d5f-9b3c987a3cff.png">

## Version and configuration information (please complete the following information)
- M1 MacBook Air with macOS Big Sur (version 11.0.1)
- Docker Dektop (version 4.1.1)
- Ddev (v1.18.2)

**Comment by rfay** [comment]
Hi @Aandreba, welcome and thanks for doing the diagnostic! (The diagnostic was completely successful, so it's not likely there's anything wrong with ddev.)

This happens often enough that it's actually in the FAQ. I imagine your docroot isn't set to the directory where your index.php is, and it has to be. Because the docroot is pointing to something else, there's nothing there and so nginx gives you a 403.

See https://ddev.readthedocs.io/en/latest/users/faq/ -
> Why do I get a 403 or 404 on my project after ddev launch?
The most likely reason for this is that the docroot is misconfigured, or there's no index.php or index.html file in the docroot. Take a look at your .ddev/config.yaml and see what is there for the docroot. It should be a relative path to where your index.php is.


Please take a look. Another thing you can do is go step-by-step through the [Drupal 9 Quickstart](https://ddev.readthedocs.io/en/latest/users/cli-usage/#drupal-9-quickstart) (it will work) and compare what you did to the quickstart.

There are more suggestions on the [Troubleshooting page](https://ddev.readthedocs.io/en/latest/users/troubleshooting/) but I imagine it's your docroot that's the issue.

**Comment by rfay** [comment]
No response, so I'll close this, but happy to continue the conversation here or elsewhere. I hope setting the docroot sorted this out for you.

**Comment by sandip-meshh** [comment]
Hi @rfay I'm facing the same issue with Laravel. I followed the instructions to set up the Laravel demo with composer. I'm not sure what the docroot should be set to? The documentation does not mention anything about what defaults are used: https://ddev.readthedocs.io/en/latest/users/configuration/config/#docroot

Thanks in advance for your help!

**Comment by stasadev** [comment]
Hi @sandip-meshh,

Please create a new issue (bug report) with all the details (exact steps to reproduce and output for `ddev debug test`).

We need to know more about *your* setup, you may have a different issue.

**Comment by sandip-meshh** [comment]
@stasadev Done: https://github.com/ddev/ddev/issues/5849

**Comment by AndriiOkhremchuk** [comment]
ddev composer create drupal/recommended-project ?
