### ISSUE TITLE
Windows:`ddev composer create "typo3/cms-base-distribution:^11`  chgrp "/var/www/html/." failed: Operation not permitted

### ISSUE THREAD

**Issue by randomresult** [drud/ddev#3712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ddev composer create "typo3/cms-base-distribution:^11" runs into an error like: 

Creating a "typo3/cms-base-distribution" project at "/tmp/FDAieN"
Info from https://repo.packagist.org: #StandWithUkraine
Installing typo3/cms-base-distribution (v11.5.1)
Created project in /tmp/FDAieN
Moving installation to composer root
rsync: [generator] chgrp "/var/www/html/." failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
Failed to create project: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-t3v11 docker-compose -f C:\Users\testbot\workspace\t3v11\.ddev\.ddev-docker-compose-full.yaml exec -w /var/www/html -T web bash -c set -eu && ( rsync -a "/tmp/FDAieN/" "/var/www/html/")', action='[exec -w /var/www/html -T web bash -c set -eu && ( rsync -a "/tmp/FDAieN/" "/var/www/html/")]', err='exit status 23', stdout='', stderr='rsync: [generator] chgrp "/var/www/html/." failed: Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]'

### Expected Behavior

Should install typo3

**Comment by rfay** [comment]
Thanks for reporting this! I can recreate it with Docker Desktop 4.6.0 and ddev v1.19.0

**Comment by rfay** [comment]
Sadly, this would have been caught by TestComposerCmd, but it's disabled on Windows because of odd behavior. https://github.com/drud/ddev/blob/d1ac88d29d6b34f1cc70129514085ddbe379fb99/cmd/ddev/cmd/composer_test.go#L68-L84

It's probably worth trying to change that test to use `--no-install` and see if it can run predictably in these other environments. The docs quickstarts now use --no-install because it's simpler and more likely to succeed.
