### ISSUE TITLE
Add ddev to the Raspberry pi apt repos

### ISSUE THREAD

**Issue by 1Spinne** [drud/ddev#3774]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe

You have to use the install script on arm devices since Homebrew is only available on Intel.

### Describe the solution you'd like

Add ddev to the Raspberry Pi repos so you can install with `sudo apt install ddev`

**Comment by rfay** [comment]
Related:
* https://github.com/drud/ddev/issues/1678

Since you just need it in the Debian/Ubuntu repos, I don't think this is specific to Raspberry Pi is it? Or at least on my Pi I run Ubuntu, so it wouldn't be relevant that it's raspberry pi.

I'm going to close this in favor of #1678, which could possibly get some attention in this release cycle, not sure. It would be nice though!

Happy to continue the conversation here or elsewhere, and love that you're using pi, and would love to hear your experiences.
