### ISSUE TITLE
Allow disabling ddev-router port bindings

### ISSUE THREAD

**Issue by Cyborg572** [drud/ddev#3797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have multiple services running on my computer, and my own reverse proxy already running on port 80 and 443.

I can tell the reverse proxy to route `*.ddev.site` to the `ddev-router` container, but I can't get the router to start because 80 and 443 are already in use.

Attempting to get the `ddev-router` to not bind on port 80 and 443 also re-configures the internal routing, and changes the reported URLs of the projects, so none of the links produced by the CLI work correctly.

### Describe the solution you'd like

I'd like to be able to disable `ddev-router`'s  port bindings, without disabling all the routing logic. Something like `bind_no_interfaces` instead of `bind_all_interfaces`.

Alternatively, I'd like a way to say "This is the URL to display for this project, regardless of what the rest of the config would imply"

I'm trying to get to the point where the output from ddev is something like:

```
Successfully started my-project
Project can be reached at https://my-project.ddev.site
```

and variables like `DDEV_PRIMARY_URL` and `DDEV_HOST_HTTPS_PORT` to match that, without binding `ddev-runner` to any ports on the docker host.

### Describe alternatives you've considered

I've tried disabling the `ddev-router` container with `omit_containers`, but this disables the routing entirely, and sets the url for the project to be something like `https://localhost:9372`. I tried setting `additional_fqdns`, but this seems to have no effect with the router disabled.

I've tried changing the `router_http_port` and `router_https_port` settings on the project, but this seems to stop the project's web container from listening on port 80/443, and adds the new port to the url (`https://my-project.ddev.site:8080`), which doesn't work, since the reverse proxy is routing the domain based on 80 and 443 working.

I've tried the `.router-compose.yml` overrides suggested in https://github.com/drud/ddev/issues/1941#issuecomment-1112074364, but that only adds additional ports/ips, and does not prevent the existing port 80/443 binding from happening.

**Comment by rfay** [comment]
And of course you used the first line of approach I hope, `ddev config --router-http-port=8080 --router-https-port=8443` right? As in the troubleshooting instructions, https://ddev.readthedocs.io/en/latest/users/troubleshooting/#webserver-ports-are-already-occupied-by-another-webserver ?

**Comment by Cyborg572** [comment]
Thanks for following up so quickly.

I did try that (via config.yaml, those flags don't seem to exist for the config command - the guide you linked sets them in the file as well). While it did stop the router from binding to port 80 and 443 on the host, it also changed which ports were exposed by the router container, and added the ports to `DDEV_PRIMARY_URL` and the url reported from `ddev start`.

I'm not trying to work around a port conflict, that's easy enough to do, and there's plenty of options for it. I'm finding ddev to be very flexible. It's getting me to about 90% of where I want to be.

I guess at the core of the issue, what I really need to be able to do is tell ddev that it doesn't have the full picture of my network setup, and that it needs to trust the URLs I'm providing as being correct.

If I could comment out the `ports` section of `~/.ddev/.router-compose.yaml` and have that persist, without changing anything else,  then I would have exactly what I'm looking for. The way docker compose does yaml overrides doesn't allow for that, so was hoping it would be possible to add an option to just not write the ports there in first place.

**Comment by rfay** [comment]
If you want to fiddle with router-compose stuff you do it with a `router-compose.*.yaml`, not by editing the .router-compose.yaml. .router-compose.yaml gets overwritten on every start. 

I guess I still don't understand what you're trying to do or why. 

If I typoed the config command, you'll easily find the correct things to change in .ddev/config.yaml and you can experiment with them.

Maybe you can start over saying what it is you really want to accomplish. Maybe if we talk about what you want to accomplish we can get farther.

**Comment by Cyborg572** [comment]
I was fiddling with `router-compose.*.yml` files, but they only allowing adding to the port bindings, not removing them.

I mentioned removing the lines from `.router-compose.yaml` as an example of what I'm trying to accomplish. Which is to have ddev do exactly what it's doing right now, but without actually binding to any ports on the host.

These are my goals, in priority order:
1. within the containers, `DDEV_PRIMARY_URL` is `https://my-project.ddev.site`, and the other related variables also indicate that the site is running at that url, on port 80 and 443
2. the `ddev-router` container does not try to bind to port 80 or port 443 on the host.
  - ideally, it does not bind to any host ports
  - less ideally, it binds to alternative ports, without compromising the first goal
  - even less ideally, but still workable, `ddev-router` doesn't run at all, without compromising the first goal
3. when I run `ddev start` it reports `Project can be reached at https://my-project.ddev.site` (note the lack of port numbers)

I can guarantee that traffic to `*.ddev.site:80` and `*.ddev.site:443` will be routed to the ddev-router (or the individual web containers, if I have to), I'm just trying to get ddev to report the correct URLs to everything running in the containers.

**Comment by rfay** [comment]
So it sounds like you just want ddev to have global configuration to change the ports it uses? As in

* https://github.com/drud/ddev/issues/3240
Which is slated for the next major release?

I'm sure you know that there are portainer add-ons for ddev, and that phpmyadmin is built in.

**Comment by Cyborg572** [comment]
I don't think that would solve my issue, unless it works entirely differently than the per-project setting does.

As I understand it, setting `router_https_port` to `8443` (globally, or at the project level) would do the following:

- bind `dev-router` to 8443 on the host:  I'd rather not have anything bound to the host, but I can work around that.
- Make the `dev-router` container expose port 8443 instead of 443: Again, not ideal, but I can configure the other proxy to expect that
- set `DDEV_PRIMARY_URL` to `https://my-project.ddev.site:8443` inside the web container: This is the problem, since the correct URL should still actually be `https://my-project.ddev.site`, due to the additional routing layer ddev does not control.

I'm sure I could probably reconfigure my entire machine to run everything through ddev, but I think I'd be running into other limitations pretty quickly.

I can work with ddev as-is, via workarounds and mentally adding/removing ports when I go between systems, and passing explicit URL arguments when needed. I just though disabling the port binding entirely, while maintaining the internal routing, would be a nice quality-of-life feature for running on existing docker setups.

**Comment by rfay** [comment]
I have to confess that I'm not too enthusiastic about adding features to DDEV to support one developer's workflow and how they have their machine set up. 

It seems like you're saying you want to use your own reverse proxy for everything... and you want DDEV to know about that and work in that context. 

DDEV's current ddev-router is a descendant of the same nginx-proxy you're using, I believe. But probably in the next major version it will be replaced by the more capable traefik. 

* https://github.com/drud/ddev/issues/3458

**Comment by rfay** [comment]
I'm going to close this for now, but I'm happy to continue the conversation here or elsewhere. I suspect that when traefik becomes the router, you may want to use it instead of your existing router, and with its exceptional configuration techniques it could probably handle everything you do. However, that would also impact your current workflow.

**Comment by TwoD** [comment]
I found this looking for a solution to the exact same issue, which essentially is that router_http_port and router_https_port not only change which ports traefik binds to, but also what the actual web container binds to.

The first part is great when you have a reverse proxy in front of ddev and other things that need tl be on 80 or 443, but it's useless if the interbal container ports are also changed because the apps think they are accessible on ports the router ignores.

Meaning; I can no longer run any of my tests using the external domain foo.ddev.site (without explicit ports) inside the containers because they are no longer accessible over port 80 (or 443).
I can't change the tests or app to explicitly use a different port because that would break the tests (and the app itself) for everyone else not using a reverse proxy.

Why would ddev ever need to change the container ports when all we need to do is change traefik's ports to avoid any conflicts or use a reverse proxy?

**Comment by rfay** [comment]
I don't seem to understand what you're asking for @TwoD . Inside the ddev-webserver only port 80 is used, and it's never changed. Inside the dbserver on mysql/mariadb only port 3306 is used and it's never changed. 

`foo.ddev.site` will always resolved to 127.0.0.1, because it's being looked up in DNS on the internet, and a wildcard of `*.ddev.site` resolves to 127.0.0.1 (the ipv4 version of `localhost`). 

If you need help, please come over to Discord to chat, https://discord.gg/hCZFfAMc5k, or consider opening a new issue with a clear explanation of your quest.

**Comment by TwoD** [comment]
@rfay , sorry, I see it got a bit unclear. Probably  because I rewrote that halfway through and mixed up where I was and what I was talking about. I could have sworn the webserver port changed as well but looks like it doesn't.

`foo.ddev.site` does not resolve to `127.0.0.1` inside the container, it resolves to one of the container's interface ips (ex `192.168.144.11` ) - assuming `foo` is the actual name of the app. You are however correct that `*.ddev.site` resolves to `127.0.0.1` if I try any other subdomain than `foo`.
`curl http://foo.ddev.site` no longer works inside the container, `curl http://foo.ddev.site:[router_port]` does. After reading your comment I rechecked `curl http://127.0.0.1:80` and that works, so you are correct the webserver listen port does not change.

There are no `/etc/hosts` entries for `foo.ddev.site` inside or outside the containers, and `/etc/resolv.conf` looks like this:
 ```
search company.domain.se
nameserver 127.0.0.11
options ndots:0
```
The hosts line in `/etc/nsswitch.conf` inside the container has `hosts:          files dns`.
Outside the container `foo.ddev.net` does resolve to `127.0.0.1`.

The next issue then becomes that the app in the container sees `foo.ddev.site:[router_port]` as its "public" name, when I've set a router port. That must stay as `foo.ddev.site:80`, which should resolve to `127.0.0.1`, so that any links it generates back to itself stay correct regardless if they are uapsed inside or outside the container, but now they only work from the outside due to the aforementioned resolver issue.

I'll see if I can hop on the Discord later today or tomorrow if that doesn't clear things up.

**Comment by TwoD** [comment]
Thanks for the clarifications. :)

I think I get your point, but when you have set a non-standard TLS port, the application itself would be seeing `https://projectname.ddev.site:[router_port]` based on the incoming request, which does not work.
I'm not using TLS at the moment so in my examples it's plain HTTP, but the same issue applies to both.

The problems start with the message you get when you start ddev after setting the router ports: `Project can be reached at http://foo.ddev.site:8002 http://127.0.0.1:32832`.
That is simply wrong because the app is only be reachable on `http://foo.ddev.site:80`.
`curl http://foo.ddev.site:8002` returns 404 both outside and inside the containers while `http://foo.ddev.site:80` still works everywhere. (`curl http://127.0.0.1:32832` of course only works from outside the container but I don't care about that one.)

In my case the outer proxy is just a transparent multiplexer based on the incoming domain names, as I also need `curl https://my_other_thing.local` to work over 443, and I want both those apps to think they are still on `https://[the_app_domain]:443`, but it could also be the one handling TLS termination in the future, and then I really don't want to ever route directly to the ddev router. Either always go directly to the web container or to the default router port.

I'm not familiar enough with ddev yet to know if what ip `<projectname>.ddev.site` resolves to is customizable, but if it is I think that would solve my issues. I already found how to override all the environment variables which included the router port.

**Comment by tripodcreative** [comment]
There is a problem with the documentation to fix this problem. 

As per https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/#web-server-ports-already-occupied

Method #2 suggests:

ddev config --router-http-port="" --router-https-port=""
ddev config global --router-http-port=8080 --router-https-port=8443
ddev start

These commands throw an error. 

 ddev config global --router-http-port=8080 --router-https-port=8443
Error: unknown flag: --router-http-port
Usage:
  ddev config global [flags]

So it seems --router-http-port no longer is a valid flag.

**Comment by rfay** [comment]
Hi @tripodcreative - You don't have a recent DDEV version. You can find out what version you have with `ddev --version`. The current stable version is v1.22.7.
