### ISSUE TITLE
DDEV v1.20.0: Yarn couldn't find a configuration settings named "cache-folder"

### ISSUE THREAD

**Issue by mikaykun** [drud/ddev#4088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Web Container does not start. This is due to the error message thrown by Yarn.

```
+ yarn config set cache-folder /mnt/ddev-global-cache/yarn/newsportal-web
Usage Error: Couldn't find a configuration settings named "cache-folder"
```

In the project itself Yarn v3.2.2 is installed. There the configuration name is "cacheFolder" (see https://yarnpkg.com/configuration/yarnrc#cacheFolder)

### Expected Behavior

Checking the Yarn version and setting the cache accordingly.

**Comment by rfay** [comment]
Thanks so much fo the clear report. 

I got to study this problem yesterday in a workshop I was teaching, and the problem is indeed an incompatibility with yarn3 being site-installed, since it has this breaking change. The ddev-webserver has yarn 1 in it, and the command is correct for yarn1, but fails with yarn 3, and when yarn 3 is site-installed, yarn1 runs yarn3 and then gets this result. 

I confess that I didn't even know there was a yarn 3, or that it would be site-installed and have a dramatic breaking change like this. 

From studying it yesterday I understand how to mitigate the problem and will do a PR shortly to do that and we'll have a new release in a couple of days. But I would prefer to understand how to reproduce this in a simple project first. Would it be possible for you to make a trivail project that demonstrates it and push it up to a repo?

**Comment by rfay** [comment]
I guess it's quite a mess and quite a surprise, https://yarnpkg.com/getting-started/migration#why-should-you-migrate

Amazing that they wouldn't move the default installation technique along, but whatever.

**Comment by rfay** [comment]
I'm able to recreate with the process in https://yarnpkg.com/getting-started/migration#why-should-you-migrate
