### ISSUE TITLE
project-tld causing cert issue (no other working than ddev.site)

### ISSUE THREAD

**Issue by helsner** [drud/ddev#4091]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

only a segment of it, but in general it runs trough
https://gist.github.com/helsner/88ad1552ebed383e68eae139fa0af902

### Current Behavior

I get NET::ERR_CERT_AUTHORITY_INVALID in all browsers.
This is sometimes not immediately the case, but after some seconds.
I'm working with TYPO3 so i can access the BE, login, then open the FE and get the issue.
With the next click in the BE the whole page breaks

I defined my TLD within a Makefile:
`ddev config --project-name ${project-name} \ 	--project-tld ${project-tld} \ ...`

The issue occured to me on Thursday/Friday after upgrading to the latest MacOS Monterey update
After having the issue i upgraded docker and ddev as well with no change in the behavior.

### Expected Behavior

Other TLD should work as well. 

### Anything else?

I saw another issue #2533 which did not bring a solution for me.
trying different stuff like poweroff etc. did not work.
The issue occured with all of my projects by now.

I think this is will be hard to reproduce as i feel that this is a pretty random, i'm sorry :/

**Comment by rfay** [comment]
The most common reason you'd have trouble is not having done a `ddev poweroff` and a `mkcert -install`. I don't know how to get this kind of thing otherwise. 

I don't think I'll be able to help much unless you can come up with a bit of a recreation scenario, or at least provide specifics about what you're using for project_tld, etc. 

Remember that if you're using a project_tld that is "real", (you're using an actual tld that is live on the internet) you can absolutely confuse the dickens out of your browser.  Try not to do that.

**Comment by helsner** [comment]
Both `ddev poweroff` and `mkcert -install` were done with no change to the issue.
And yes, i thought this will be a hard one. Nonetheless i will keep this issue in mind and report in case i got a solution/more precise set of info for you.
That last hint with the actual domains is a good one to keep in mind as well.
Many thanks!
