### ISSUE TITLE
additional_hostnames could not be overwritten in config.local.yaml anymore

### ISSUE THREAD

**Issue by mkalkbrenner** [drud/ddev#4099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the upgrade to ddev 1.20 additional_hostnames could not be overwritten in config.local.yaml anymore.
The router just respects  additional_hostnames in config.yaml

### Expected Behavior

if present in config.local.yaml , additional_hostnames have to be taken from that file

**Comment by rfay** [comment]
I don't think that's true. But you can only *add* additional_hostnames in `config.*.yaml`. This is discussed in 

* https://github.com/drud/ddev/issues/4079

**Comment by rfay** [comment]
Right - based on https://github.com/drud/ddev/issues/4079 you cannot do `additional_hostnames: []` at this time, but you should be able to *add*. So now the behavior is merging, which people have asked for for ages.

For now, I think the best technique would be to *add* hostnames in `config.*.yaml` rather than start out with ones you don't want.

**Comment by mkalkbrenner** [comment]
> For now, I think the best technique would be to add hostnames in config.*.yaml rather than start out with ones you don't want.

I understand that from a technical point of view.
Unfortunately our ddev projects are also used by non-developers to produce content on their local machines. Therefore we share a working setup via git. And a developer could do its overrides locally.
For sure we can deal with the situation in 1.20.*, but it means that you always have modified config files and you need to take care not to commit them.

I described our use-case at https://github.com/drud/ddev/issues/4100#issuecomment-1209535609

**Comment by rfay** [comment]
Adding additional_hostnames absolutely works, I just tested. It uses the merge technique. You can *add* additional hostnames. But I think this issue is all about overwriting. 

Closing this one in favor of https://github.com/drud/ddev/issues/4079

It does seem like 
* https://github.com/drud/ddev/issues/4100
has a great suggestion.

**Comment by rfay** [comment]
Just a note about
> For sure we can deal with the situation in 1.20.*, but it means that you always have modified config files and you need to take care not to commit them.

`config.*.yaml` are gitignored by default, but can be committed. I imagine you know that but it wasn't clear to me from your statement.

**Comment by rfay** [comment]
I'd love it if you could all review and test the PR for this, https://github.com/drud/ddev/pull/4118#issuecomment-1214230090
