### ISSUE TITLE
configuration option/variable "cache" in .npmrc is messing with eg. local nvm

### ISSUE THREAD

**Issue by koernchen02** [drud/ddev#4119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure which version introduced the following behaviour, but for me it's present in eg. arch linux and mac os 12.5  (m1).

**ddev**: v1.20.0

When executing `ddev restart` in my `ggdb` project the value

`cache = "/mnt/ddev-global-cache/npm/ggdb-web" `

is added to my (local) $HOME/.npmrc, which I assume is probably mounted/shared somewhere, where ddev writes to it.

But `cache` beeing "global" completely messes with my locally installed nvm.
if I use eg. `nvm use 16` or `nvm use default` locally, npm, npx etc. are in an unusable state, whereas everything works, when I delete the "cache-line" from the .npmrc. 

I'm very sorry, if this is my own fault and I somehow "accidentally" added this value to my .npmrc by myself via a ddev-config option.
But since it's so specific, I'm almost 100% sure I did not do that manually and purposely on both my laptops and OSes .

### Expected Behavior

ddev only reading my local .npmrc or use "ddev-project-namespaced" config values when writing values to it.
For example using something like `cache-ddev-ggdb-web`  or `ddev:cache:ggdb-web` if it is at all needed...

```js
; "user" config from $HOME/.npmrc
//cache = "/mnt/ddev-global-cache/npm/ggdb-web" 
ddev:cache:ggdb-web = "/mnt/ddev-global-cache/npm/ggdb-web" 
```

**Comment by rfay** [comment]
Hi @koernchen02 - You have symlinked your host-side .npmrc into the homeadditions, either ~/.ddev/homeadditions or project .ddev/homeadditions. DDEV doesn't do anything to any .npmrc except the one inside the container. It doesn't even know that your host-side .npmrc exists, and doesn't read it.

To fix the problem, remove ~/.ddev/homeadditions/.npmrc. You may then want to *copy* it in there

DDEV on startup in v1.20.0 does a `npm config set cache /mnt/ddev-global-cache/npm/${HOSTNAME}` *inside the web container* but that affects your host-side .npmrc because you have linked it in there.

**Comment by koernchen02** [comment]
Thanks for your concise feedback.  That solved all my problems.
I misunderstood how to provide .npmrc values and shared my local .npmrc in a bad way:

I had it mounted as a "volume" via a custom docker-compose.mounts.yaml but the result was exactly what you assumed.

In future I will use the homeadditions (copy) approach and now I'm aware that the in-container npm might interact with the file!

Thanks again for your time and effort and first of all for ddev in general!
I tried so many different approaches before using ddev and none matches the portability and flexibilty of it.

**Comment by rfay** [comment]
Glad it's working for you!
