### ISSUE TITLE
Subdomain, Local DNS support: Don't require hosts file manipulation

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#416]
Summarizing the acceptance criteria in this thread:

* [ ] Replace naming convention to *.ddev.site.
* [x] *.ddev.site records pointing to 127.0.0.1.
* [ ] Test and fallback to /etc/host when unable to lookup public DNS records.

**Comment by Schnitzel** [comment]
Here some links how we do it at amazee.io:
Basically we create a dnsmasq container that listens on port 53 on the host that just returns `127.0.0.1` for any request with the domain `*.docker.amazee.io`:
https://github.com/amazeeio/cachalot/blob/master/cli/amazeeio_cachalot/dnsmasq.rb

OS X has resolv.conf settings per domain, so we just set one for docker.amazee.io that then defines a nameserver to be 127.0.0.0:53:
https://github.com/amazeeio/cachalot/blob/master/cli/amazeeio_cachalot/resolver.rb

Linux has no nameservers per domain, so we just add ourselves to the /etc/resolv.conf, our nameserver will not return any requests other than `docker.amazee.io` so the system will just use the next nameserver in line, which is the one defined via DHCP
https://github.com/amazeeio/pygmy/blob/master/lib/pygmy/resolv.rb#L46

on the haproxy side, we have not a full matching to the incoming domain, but match also subdomains:
https://github.com/amazeeio/docker-haproxy/blob/master/haproxy.tmpl#L40

so far this works very well, sometimes it's a bit tricky on Linux as other systems also change the /etc/resolv.conf but restarting pygmy and with that checking the resolv.conf contents usually fixes that.

**Comment by rfay** [comment]
The problem with dnsmasq and all similar solutions is that it requires intervention with the workstation of the user, and in fact reconfigures their system. Most users don't appreciate things that do that, and there are almost always unanticipated consequences, and support issues we don't want or need.

I strongly recommend that we move to a legitimate domain name (like local.drud.com ?) and use wildcard DNS there.  That would make it so that any user connected to the internet would immediately have a working DNS lookup and no hosts file manipulation would be required. This approach is outlined in https://github.com/drud/ddev/issues/175. When users did not have DNS (traveling or otherwise disconnected) the traditional hosts file manipulation could be done.

**Comment by Schnitzel** [comment]
> I strongly recommend that we move to a legitimate resolvable domain name (like local.drud.com ?) and use wildcard DNS there.
and how do you know the IP that should be resolved to? Just assume that it is localhost always?

**Comment by rfay** [comment]
Yes, it would resolve to 127.0.0.1, so in the example, *.local.drud.com would resolve to 127.0.0.1

**Comment by Schnitzel** [comment]
then I would suggest to use nip.io and not invent something new :)

**Comment by Schnitzel** [comment]
the only problem: what if the docker host is not running on localhost?

**Comment by rfay** [comment]
I love the idea of nip.io (and never ever knew about it, thanks!), but 
* it's complex for people, it has great wildcard mapping, but you have to understand what an IP address is to use it. 
* It's under somebody else's control and maintenance, so could go away in a moment (or malfunction) and we'd have absolutely no recourse.

As far as docker host not running on localhost: We only support (currently) docker-for-mac and docker-for-windows, which are innately on the same machine. Linux could conceivably bite us, but we really don't have any plans to do anything more exotic than a local docker server. (I did originally test older docker versions for Windows, and was able to make them work, but we didn't ever see a need to support docker-machine and friends.)

**Comment by Schnitzel** [comment]
> but you have to understand what an IP address is to use it.

why? we assume it's `127.0.0.1` anyway always?

> It's under somebody else's control and maintenance, so could go away in a moment (or malfunction) and we'd have absolutely no recourse.

correct, but do you feel ready to create a DNS infrastructure that can handle `*.local.drud.com`, what do you do if other people decide to use that? Running DNS is not thaaat easy.

the best would probably be https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06 but this will take a bit.

**Comment by rfay** [comment]
* zip.io only returns 127.0.0.1 if you use *.127.0.0.1.zip.io, as I read it. That means people need to use a long hostname, and it has funny numbers in it. 
* I was just talking about creating a wildcard record on our DNS for drud.com (or another domain). Not setting any infrastructure up.

**Comment by rfay** [comment]
Responding to "let localhost be localhost", thanks for that link. AFAICT, that's about the localhost names (localhost, .localhost, etc).  We're not using those anywhere or in any way, just the reserved address 127.0.0.1.  Maybe I misunderstood your intent with that.

**Comment by Schnitzel** [comment]
> I was just talking about creating a wildcard record on our DNS for drud.com (or another domain). 

I think a wildcard itself will not be enough, you would need an `ORIGIN` directive so `foo.bar.local.drud.com` will also be resolved.

> Not setting any infrastructure up.

Just saying, having thousand of users all over the world using `.local.drud.com` will put a tiny bit load on your DNS servers :), that's for example the problem with `xip.io` which struggled over time quite hard with too many requests and with that made people very sad because suddenly their local development environment did not work anymore.

**Comment by rickmanelius** [comment]
Along with https://github.com/drud/ddev/issues/415, I think we may need to get on a call with all 3 of us because this doesn't feel like we're in sync and this might just be a quicker item to resolve with additional clarity.

**Comment by Schnitzel** [comment]
@rickmanelius see doodle.com/schnitzel and send me a meeting request, I'm in Austin (central time) currently.

**Comment by rickmanelius** [comment]
We met and now have a clear and agreed upon path to actionability. Summarizing:

* The default behavior will be a valid, wildcard domain (i.e. *.ddev.site, which we just purchased) that is powered by a scalable nameserver (i.e. Route 53) that effectively points back to 127.0.0.1.
* The fallback behavior (when access to the internet is disabled or prohibited) will be a prompting the end-user for the permission to modify /etc/hosts.

**Comment by rickmanelius** [comment]
We're now using the official Drupal 8 release here https://github.com/drud/ddev/pull/503. We probably want to start doing the same for WordPress and Drupal 7.

**Comment by rickmanelius** [comment]
An additional need for this:

* [ ] Properly configure *.ddev.site with the appropriate records on Route 53.

**Comment by rickmanelius** [comment]
Updated issue summary and acceptance criteria.

**Comment by rickmanelius** [comment]
As discussed at stand-up today. @tannerjfco feel free to reach out to @cyberswat if you don't already have access to the credentials for the domain registrar and also feel free to use the nameservers that are provided if there isn't a stated max cap of lookups/month.

**Comment by rickmanelius** [comment]
Confirmed that the DNS records are set up. See https://www.ultratools.com/tools/dnsLookupResult and test for ddev.site.

**Comment by tannerjfco** [comment]
> The fallback behavior (when access to the internet is disabled or prohibited) will be a prompting the end-user for the permission to modify /etc/hosts.

Giving this a bit of thought, I don't think this will be sufficient fallback behavior. Catching this on start would only allow a newly started site to work offline. We would then have that hosts entry persisting unless we did further checks for connectivity and removed if found. Sites already running would not get a hosts entry unless the user took action, either adding to hosts or re-running start.

What I think we should do instead is provide an explicit offline mode. The behavior I'm thinking of would be:
- `ddev offline enable` sets a file for determining offline mode, and prompts to add domains of any running sites to hosts
- any `ddev start` commands would perform the necessary hosts file modifications as is done currently
- `ddev offline disable` prompts to clean up all ddev.site urls from hosts file, and removes the file for determining offline mode.

I think this makes for a better way to handle offline, as the user can explicitly tell ddev when it shouldn't bother with a connection, and when they're back in the clear. It also has the added benefit of keeping the hosts-file approach available for those that prefer it over the remote DNS.

**Comment by rfay** [comment]
I think this is a valuable line of thinking. 

I don't think we need to remove hosts file entries, might as well leave them there. 

How about `ddev offline enable` just auditing the hosts file for missing entries of running sites and adding, and setting a toggle that says `ddev start` should create entries?

**Comment by rfay** [comment]
There was a significant conversation in slack, with @beeradb expressing significant concerns with this. It [started](https://drud.slack.com/archives/C45DF87JT/p1509739204000092) with Brad's concern and went on for a [longer conversation](https://drud.slack.com/archives/C45DF87JT/p1509745333000184)

> Anyway, did not mean to ignore the replies to my previous comment for so long. Perhaps supporting both methods would be acceptable. I’m not sure. I still feel like that is missing a step though. Right now we’re opening PRs to significantly change existing behavior in ddev, and if a *problem statement* for what is wrong with the existing behavior exists, I haven’t seen it. I get that there seems to be some momentum for changing this due to outside forces, but it’s a bit of a point of frustration for me that despite repeatedly asking, no one has made the case for what exactly the problems with the existing system are, and how the state of things will be improved by moving to the system we apparently are moving to.

>First of all, sorry for letting my frustration be shown there. I shouldn’t have. Secondly, on the actual issue…

>What I do understand is that it doesn’t work well on windows. 

> 1. Are those problems insurmountable? Both goodhosts (what we’re using) and other similar packages for golang claim windows support. 

> 2. As a followup, does it make sense to change this behavior across the board, when it’s working fine on other platforms? The online/offline command seems a bit weird to me. If it’s just not possible to make windows work, it would seem like maybe we should leave the behavior as-is but *also* add the DNS related lookup as a fallback, and then just document that working offline on windows will require host file manipulation?

> and 3. have we considered implications here for upgrade paths? Particularly in wordpress where I believe we write a settings file with the URL?

@rickmanelius I think it's important for you to know about these reservations and didn't want you to miss this conversation.

I personally am pretty sure that name resolution via DNS is still better for most average users, and have always been uncomfortable with making major changes to the user's system (/etc/hosts), especially changes that require admin privs. But Brad's reservations should be explored a bit more, and as he points out, a clearer problem statement should be made in the OP here.

**Comment by rickmanelius** [comment]
Hey @rfay. Thanks for capturing/memorializing this. I'll have to digest/respond Monday or Tuesday when I'm back in the office.

**Comment by rickmanelius** [comment]
Hi @Schnitzel. One question that appeared in my earlier notes and that I wanted to make sure we captured from both a motivation as well as testing perspective was situations where a user was connected to a VPN. While I realize this may be a naive question, I'm curious how a public DNS record at *.ddev.site pointing back to 127.0.0.1 would support that use case. Any information you can provide would be helpful.

**Comment by beeradb** [comment]
### Issue background and internal discussions

As @rfay pointed out, I did have some significant concerns about this feature as currently proposed. We discussed these concerns internally today, and I'll attempt to summarize that conversation here.

First, let's start with motivations for making a change to this components.

1. The current hosts file modification does not work on Windows. We aren't currently aware of a method for privilege escalation that reliably works on Windows. There was full consensus that first class Windows support is a significant priority, and this needs to be resolved. Regardless of whether we move to external DNS or not, we're still talking about keeping the hosts file modification we currently have in place to support "offline" mode. As such, we've opened #511 to look into options for supporting this method on windows.
2. The desire to support alternative workflows. This includes avoiding local modifications such as /etc/hosts & supporting multiple domains.


My biggest concern with the changes described here, is that for the 95% of our user base that is on OSX or Linux the change would make things less reliable. So much so that we're discussing adding additional commands (`ddev offline enable` & `ddev offline enable`) to work around the instability. We’re turning a mostly offline tool into a completely online tool. At present, the only time you ever need connectivity in ddev is to download containers. This tends is done the very first time you start a ddev site and then never again (unless we update ddev or you change container versions, a relatively rare event). I feel this change would negatively effect people who regularly work away from home on planes, at conferences, on public transit, or even coffee shops. All of those are places where network connectivity can be sporadic or non-existent. Although fixing Windows and adding support for alternative workflows is a great goal, I feel strongly that we should not do so at the expense of the majority of users for which the current hosts modification works without issue.


That's a long-winded explanation of our thought process here, but I think it's important to capture to understand where our discussions have been on this issue and provide some background on the suggested fix.


### Suggested Fix

- Leave the default behavior alone. This behavior has been stable for the majority of our userbase, and although there are some valid concerns about privilege escalation, the one-time prompt for hosts file modification is worth the extra stability of not requiring a network connection.

- Add a user-configurable "hostname" field to site configuration. For the sake of simplicity, this won't be exposed in the interactive config prompts but will be available as a key in config.yaml. This field will be a complete hostname including TLD and should allow for multiple values to support domain access or other use-cases that might require multiple hostnames.

- We add a user-configurable "modifyhosts" field to site configuration which defaults to true. This won't be exposed in the interactive config prompts. If set to false, when starting a ddev site we will not attempt to modify the systems hosts file.

The combination of bullet points #2 and #3 will allow power users or people with alternative workflows to use alternative domains (such as *.docker.amazee.io, or *.127.0.0.1.xip.io) while maintaining the simplicity and stability of the current hosts file method for the majority of our users.

**Comment by tannerjfco** [comment]
> Leave the default behavior alone.

I can live with this, but I'm not excited for the default behavior to still be something awkward for Windows users. I also have to wonder if we're overplaying the offline concern. Personally, I've had little to no success working fully offline. There's always something to look up, download, etc that simply makes it difficult to work offline. ddev should definitely be able to work without a network connection, but is it so critical that it be the default behavior?

> Add a user-configurable "hostname" field to site configuration.

I think this is a great idea. I actually think we should prompt for it though. Prompting, we can suggest the default sitename.ddev.local, and establish early an expectation for the user what the site URL will be. There are probably cases where you want a hostname totally different from the checkout name or configured site name, so it'd be great for that too. If we don't prompt for hostname, we have to document the configuration value somewhere and people have to discover it in docs in order to use it. I don't think that's really a simpler path than prompting, at least for this case.

> We add a user-configurable "modifyhosts" field to site configuration which defaults to true.

I'm on board with the idea, but I'm not sure on the execution. It seems likely to me that a user's preference on this is going to be pretty consistent, which makes me think this should be a global configuration. Perhaps a flag is another option to consider, or perhaps both - a global config that can be set and then overridden as needed by flag. It just seems weird to expect this to be configured per-site in shareable configuration.

**Comment by rfay** [comment]
@rickmanelius This is important and we've dropped it and lost the PR because it got old. We need to get it prioritized again.

**Comment by cweagans** [comment]
Related: https://github.com/drud/ddev/issues/565

**Comment by rfay** [comment]
One thing not to forget is that @cweagans pointed out (somewhere) that it's not totally legit to have a non-routable IP address in a DNS lookup, so some systems will refuse to resolve.

**Comment by rickmanelius** [comment]
All the more reason the default to local while requiring users to consciously opt for public. This will also reduce support requests for these edge cases.

**Comment by rfay** [comment]
@rickmanelius I'd disagree with your assertion "default to local while requiring users to consciously opt for public"; I'm pretty sure we can work around that problem successfully.

**Comment by rickmanelius** [comment]
@rfay. On the last comment, I may not have all the information or I may not be interpreting it correctly (only human and certainly willing to admit mistakes!). Either way, I’m confident we will make headway when we connect on Monday and we can unblock this while addressing work arounds/options.

**Comment by rickmanelius** [comment]
Thanks, again, for everyone's patience on this one. We've had a few additional conversations to discuss the pros and cons of the different approaches we can take. Ultimately, I think it's important that we address the use cases brought about by this request because it keeps coming up. Practically, a public wildcard DNS entry is a much more elegant solution than adding an arbitrary number of entries on the fly to /etc/host.

Important to note, nothing about what we are discussing permanently locks us in. Therefore, I would like to take a pragmatic approach in enabling this feature without over architecting this until we see what feedback we get.

Finally, I fully appreciate the need to still make offline mode (with an entry in /etc/host) a workable solution. There are situations where defaulting to public DNS can result in frustration if internet access drops without an /etc/host entry. To that end, we need to properly detect and add host entries when a connection times out. Note that once an entry has been added, the ability to toggle via a flag is irrelevant unless we had an easy way to remove it. And the constant read/writes with sudo prompts would be obnoxious.

To that end, let's default to a public DNS entry for *.ddev.site as we had in our prvious PR. However, let's modify the behavior to not require a project or global configuration toggle. Instead, let's perform a timeboxed DNS lookup (say 5 seconds)? If that doesn't resolve, then we trigger a sudo request for an /etc/host modification. We can perform that check at `ddev start`.

We'll get the AC on this issue updated and then we'll consider this actionable. Thanks!

**Comment by beathorst** [comment]
is there any workaround for now? because for us it is necessary to have this feature.

**Comment by rfay** [comment]
@beathorst to help us prioritize, can you please say why it is necessary for you to have the DNS vs /etc/hosts feature?  For most people it's just an annoyance that it requires /etc/hosts to be manipulated.

**Comment by beathorst** [comment]
@rfay thanx for your fast answer.
well it is necessary because for us it is a showstopper to use ddev for the hole company.
I would like to use it and get ride of our vagrant boxes but we have a lot of TYPO3 projects with lots of sites in one installation. Every site needs its own (sub)domain. Otherwise it is only possible to reach one of the sites inside the typo3 installation

**Comment by beathorst** [comment]
sorry you are right it is #620 what helps me

**Comment by rfay** [comment]
I suspect we're going to never do this. We're all used to the /etc/hosts manipulation, and people like it working offline. The only think we really have to do is provide a tool that will make it easier for Windows users.

**Comment by Schnitzel** [comment]
> We're all used to the /etc/hosts manipulation

and to handle subdomains we tell people to just create the subdomains in config.yml?

**Comment by rfay** [comment]
You can already do subdomains easily (they're simulated subdomains, but work fine). See the docs about [additional_hostnames](https://ddev.readthedocs.io/en/latest/users/extend/additional-hostnames/) which gives exactly this example (subdomains for multiple languages).  You can go to any level in the dotted hostnames there; they're certainly not DNS subdomains, but they behave the same from a name resolution perspective.

**Comment by Schnitzel** [comment]
So I think there is now a bit confusion, there is

@rfay saying:
> I suspect we're going to never do this.

and @rickmanelius saying:
> To that end, let's default to a public DNS entry for *.ddev.site as we had in our prvious PR. 

Can we get some clarity on this?

From my side, I'm fine with not having a publich DNS and relying on `/etc/hosts` if:
- it is completely transparent to the developer and they don't need to enter their sudo password all the time
- ddev allows that`/etc/hosts` can still be managed by other tools like GasMask on OSX side-by-side what ddev does
- we allow for subdomains to work as well (was already confirmed by https://github.com/drud/ddev/issues/416#issuecomment-381697466)

**Comment by rfay** [comment]
@wizonesolutions points out this article on not using .local - https://miketelahun.wordpress.com/2012/09/16/stop-using-local-as-the-top-level-domain-for-your-lan/

**Comment by SqyD** [comment]
May I suggest an alternative approach, which I used for the [drupaltrainingday](http://drupaltrainingday.nl/) event (in dutch, sorry):
* Serve a [proxy auto configuration file](https://en.wikipedia.org/wiki/Proxy_auto-config) from the ddev router
* Populate it [like this](https://github.com/dtd-tech/dtd-main/blob/master/docroot/dtd.pac.php) so it configures the browser to use the ddev router ip and port for all ddev managed domains.
* Provide per browser instruction on how to configure this (3 steps max). (permanent)
* OR: start a Chrome/Chromium browser with the --proxy-pac-url commandline option (one time)

This will avoid hostfile mods, doesn't require any elevated permissions and would allow the use of _any_ domain without adding any services or overhead.

**Comment by rickmanelius** [comment]
While we didn't quite get to a public DNS lookup first before modifying /etc/hosts, we do have FQDN support, which allows both the change of naming convention as well as the ability to use public DNS records that point back. To that end, I'm suggesting we close this thread. Conversations regarding switching the [default TLD pattern was discussed here](https://github.com/drud/ddev/issues/868) and can be re-opened. The desire to default to public DNS with /etc/hosts as a fallback is still on the table, but I'm wondering if the FQDN support already makes enough inroads towards this.

**Comment by rickmanelius** [comment]
Actually, in re-reading my notes I think I vote to keep this open because we still want to address the change from *.ddev.local to *.ddev.site, which would be a prerequisite to switching out the default behavior if we proceed.

**Comment by rfay** [comment]
From https://letsencrypt.org/docs/certificates-for-localhost/ 

> You might be tempted to work around these limitations by setting up a domain name in the global DNS that happens to resolve to 127.0.0.1 (for instance, localhost.example.com), getting a certificate for that domain name, shipping that certificate and corresponding private key with your native app, and telling your web app to communicate with https://localhost.example.com:8000/ instead of http://127.0.0.1:8000/. Don’t do this. It will put your users at risk, and your certificate may get revoked.

**Comment by rfay** [comment]
Now that we have mkcert for trusted local https, it's not important to have a "real" certificate. That means we have plenty of flexibility here. 

A simple option is to 
* Make the ddev domain configurable (use ddev.site instead of ddev.local, allow transition on this)
* CNAME *.ddev.site to a name like "ddev.hostsfile".
* ddev.hostsfile is in local /etc/hosts, placed there by ddev, pointing to 127.0.0.1 (or correct IP on docker toolbox)
* Look up name before acting on the /etc/hosts. If it resolves, go with it.
