### ISSUE TITLE
Provide link to issue queues on container start

### ISSUE THREAD

**Issue by beeradb** [drud/ddev#417]
## What happened (or feature request):
I was using the bitnami wordpress container for some research, and noticed on startup it has some fantastic messaging that I recommend we adopt. Here's an example of the text that prints when it starts up:

```
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com
```

## What you expected to happen:
I suggest we adopt this approach when starting our nginx-php-fpm container. Adding a link to the ddev issue queues on start. 

The more welcoming we can be to issues and feedback the more likely we are to get good feedback.

**Comment by rickmanelius** [comment]
+1 from me because I always like leaving trails for end-users. I think we skip the email for now unless/until we have an approach for addressing support requests via email. We could probably direct to our room in Drupal and/or WordPress Slack accounts. Somewhat related would be https://github.com/drud/aws-infra/issues/15.

**Comment by rfay** [comment]
One difference between our situation and just starting a single container: We capture all output as logs... It's not displayed and really can't be because we're starting many at once. We *could* put up a wall of text with this info on `ddev start`, but that's a bit different from having a container do it.

**Comment by rickmanelius** [comment]
Revisiting, I kinda like this and I think if we attached this to ddev start it would still provide the value we're looking to achieve. Seems like next steps would be:

* [ ] Update verbiage to be ddev specific.
* [ ] Locate specific area within the `ddev start` process to state.
* [ ] Decision on where this may fail. Would we care to have this on ddev restart? Do we have to consider ordering of pre/post hooks and verbiage that might directly precede/append to this?

**Comment by rickmanelius** [comment]
Added me to help surface verbiage/location.

**Comment by rfay** [comment]
I don't actually understand where this output would go in the ddev interaction flow. We already say way too much when doing `ddev start`, and most of it is docker-ese not comprehensible by a normal user.

**Comment by rickmanelius** [comment]
@rfay How about the first time ddev is installed/run? Since we're already doing a version/update check, maybe that is a decent time to introduce ourselves. This isn't an urgent task, so I don't want to commit too much brain power here. But this seems like it would be something nice to have if it's not overly complicated.

**Comment by rfay** [comment]
I think that might work ok. Also, we could improve what goes into `brew info ddev` I think.

**Comment by rickmanelius** [comment]
@rfay I'm cool with that approach too. It wouldn't necessarily help people not using macOS, but I also think that information could exist in both locations. And again, I'm not trying to obsess over this one. If we can do it tastefully and in a manner that would help provide guidance to a new user, I think it's a nice win.

**Comment by rfay** [comment]
This is quite stale, I don't think we're going to do it, and think it would end up being disruptive to the user.
