### ISSUE TITLE
Mutagen sync issues when running more than one DDEV site at the same time

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#4240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

That I can cleanly run two DDEV instances with `ddev config global --mutagen-enabled` without Mutagen sync issues

### Actual Behavior

Mutagen reports errors when I start a second DDEV site when one is already running.

### Anything else?

I will attempt to provide more details and get this to fail again soon.

**Comment by rfay** [comment]
Hi @davereid-pfg - thanks. But everybody is running multiple projects with mutagen. So please do add the link to the gist and give specific instructions.

Also it would be kind if you would test with current HEAD, because there are several mutagen changes there. `brew unlink ddev && brew install --HEAD --fetch-head ddev`

**Comment by rfay** [comment]
Closing this for now. When you come back with info, we can reopen.

Also note that there is significant work in current HEAD on mutagen, including a new version. Would love to have you try it out. `brew unlink ddev && brew install --HEAD --fetch-head ddev`.
