### ISSUE TITLE
Framework example module

### ISSUE THREAD

**Issue by Firesphere** [drud/ddev#4407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I would like to add more frameworks (e.g. Slim4, Silverstripe) to have DDEV support.

However, I can't find a skeleton module, that would help me to easily get started on creating a new Framework plugin.

### Describe your solution

Provide a basic skeleton module, which would contain all the necessary files and file structure, with placeholder names.

**Comment by rfay** [comment]
Hi @Firesphere - Most frameworks don't need an explicitly supported CMS type, and for some it's not even useful. CMS types like Drupal and Craft CMS and several others have explicit CMS types defined so that DDEV can automatically create settings files and optionally provide customized nginx configurations. 

I assume explicit support for the frameworks you mention is what you're asking for. There are in fact docs on how to add explicit support for new project types at https://ddev.readthedocs.io/en/latest/developers/project-types/ but like I say, it doesn't make a lot of sense. For example, for Symfony, there are so many differences of implementation that people just use the `php` (generic) project type and go forward. They're quite happy. 

Let me know if this is the info you were after.

**Comment by Firesphere** [comment]
Hi @rfay ,

Especially in the case of Silverstripe, there is probably use for an explicit support (e.g. it's composer plugins, it's `sake` command, etc.).

For Slim, indeed probably nothing specific needed.

I'll have a look at the project types things and see if I can come up with something :) (assuming I can find the time :P )
