### ISSUE TITLE
ddev adds a domain to /etc/hosts although it is resolvable on OSX (should be fixed with golang v1.20)

### ISSUE THREAD

**Issue by helhum** [drud/ddev#4443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

OS Information: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83
DDEV version:  ITEM             VALUE                                   
 DDEV version     v1.21.3                                 
 architecture     arm64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.3 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.3             
 docker           20.10.20                                
 docker-compose   v2.10.2                                 
 docker-platform  docker-desktop                          
 mutagen          0.16.0                                  
 os               darwin                                  
 router           drud/ddev-router:v1.21.3                
 web              drud/ddev-webserver:v1.21.3             

### Expected Behavior

I have set `project_tld: helhum.test` and have a dnsmasq server running on localhost with `/etc/resolver/test` instructed to use dnsmasq and also resolve to 127.0.0.1

This works, which I can verify with `ping foo-whatever.helhum.test` correctly resolving to localhost.

When I now do `ddev start`, I would expect, that ddev does not add the project tlds, that can perfectly be resolved by Mac OS to be added to the `/etc/hosts` file.

### Actual Behavior

ddev show the warning: `The hostname <project>.helhum.test is not currently resolvable, trying to add it to the hosts file ` and adds the entry to `/etc/host`

### Steps To Reproduce

1. Setup local domain resolving by configuring a [etc/resolver](https://medium.com/@phaneendrakrishnareddy/using-dnsmasq-for-local-development-on-os-x-7f17f78c7198)
2. Add a `project_tld: ` according to above configuration
3. `ddev start`

### Anything else?

Seems like [Go 1.20 changed DNS resolving](https://danp.net/posts/macos-dns-change-in-go-1-20/) on OSX when using go net lib, which would seemingly address and fix my request.

Not sure though if it is easily possible to make use of that for ddev. In any case, thanks for looking into this in case you have time. Not a super urgent thing, but found it interesting enough to take the time an share my findings.

**Comment by rfay** [comment]
It would be interesting to compile a tiny test golang app and see if it can resolve your domain.

**Comment by rfay** [comment]
But DDEV uses this all the time, same technique, for *.ddev.site... 

Could you please show `ddev debug configyaml`? Is it possible you have `use_dns_when_possible: false` ?

**Comment by helhum** [comment]
> Could you please show `ddev debug configyaml`? 

```
name: <projectname> 
type: php 
docroot: .Build/public 
php_version: 8.1 
webserver_type: apache-fpm 
webimage: drud/ddev-webserver:v1.21.3 
router_http_port: 8081 
router_https_port: 4431 
additional_hostnames: [] 
additional_fqdns: [] 
database: {mariadb 10.3} 
omit_containers: [dba ddev-ssh-agent] 
mailhog_port: 8025 
mailhog_https_port: 8026 
phpmyadmin_port: 8036 
phpmyadmin_https_port: 8037 
project_tld: helhum.test 
use_dns_when_possible: true 
timezone: Europe/Berlin 
composer_root: .Build 
composer_version: 2 
web_environment: [] 
nodejs_version: 16 
default_container_timeout: 120 
```

> Is it possible you have `use_dns_when_possible: false` ?

nope. I've seen that in the code, that this option is required to be on. I also have internet connection established, when doing the ddev start.
DDEV is still unnecessarily writing the domain to /etc/host

(I know this is an edge case, so I'm fine this being not prioritized. My edge case would even require to make a resolve, when internet connection is not available, since my local DNS server is always running...)

> But DDEV uses this all the time, same technique, for *.ddev.site...

*.ddev.site is a publicly resolvable domain, which is resolved through the default DNS server, while *.test on my system is resolved by a different DNS server on my localhost, configured through /etc/resolver/...

The difference is described in the link I posted above: https://danp.net/posts/macos-dns-change-in-go-1-20/

**Comment by rfay** [comment]
Sounda like you've done all the work and already nailed it completely! Thanks!

I guess the problem should be solved when go 1.20 gets released (and first DDEV release using it), which is just a couple of months away.

**Comment by helhum** [comment]
> Sounda like you've done all the work and already nailed it completely! Thanks!

Sure!

> I guess the problem should be solved when go 1.20 gets released (and first DDEV release using it), which is just a couple of months away.

Thanks for that info and good to know, that you're going to switch to a new go version anyway once it is released. Since I don't know the go ecosystem, I just wanted to share my findings and maybe trigger a todo for DDEV, in case this switch to a new go version would require some extra planning.

Since this issue is minor anyway and will go away with go 1.20, I'm fine with closing this here. It's up to you.

Thanks again as always @rfay !

**Comment by rfay** [comment]
1.20 is out, reopening for inclusion in DDEV v1.21.5

**Comment by rfay** [comment]
It would be great if you could test this when go 1.20 makes it into homebrew (or download and install, https://go.dev/dl/

`brew install --HEAD --fetch-head ddev`

**Comment by helhum** [comment]
> It would be great if you could test this @helhum when go 1.20 makes it into homebrew 

Will do @rfay 

Just tell me here once I can test it (I have no capacity right now to install the go dev env and test with that)

**Comment by rfay** [comment]
They're having more trouble than usual sorting out homebrew go 1.20, but we'll get it into this into DDEV v1.22.0 if we don't make it in v1.21.5.

**Comment by rfay** [comment]
* https://github.com/Homebrew/homebrew-core/pull/122082

**Comment by rfay** [comment]
@helhum please try https://github.com/drud/ddev/pull/4639 - testing instructions there.

**Comment by rfay** [comment]
And you may want to try #4641 if that doesn't give immediate results.

**Comment by helhum** [comment]
@rfay finally got around testing this. It works like a charm! Thanks a bunch!

**Comment by helhum** [comment]
Tested with the binary from #4639

**Comment by helhum** [comment]
Ah, once I needed docker-compose, the binary from #4641 helped. Now tested both and can confirm, that it still works like a charm!

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Nobody but you has ever reported or (apparently) studied this, so you're the expert, unfortunately. 

We currently build with go v1.22.4

I think the best thing to do would be to get a careful technique together to study which DDEV version the problem appears in, you can get builds of each from https://github.com/ddev/ddev/releases

If you find a clear breaking point, then it may work to try building DDEV (it's easy) using a set of golang versions to see if you can detect whether that's the issue.  

Or maybe if you can develop a simple technique to do name resolution and try to figure out whether this is even related to ddev or go... A trivial test go program appears to be listed in the original discussions above. Using that you should be able to find out exactly what the problem is. 

If I were you I wouldn't probably use `.test`, or I'd at least experiment with something that isn't as ambiguous in implementation. Is it possible that Apple has done something to you?

**Comment by helhum** [comment]
> Nobody but you has ever reported or (apparently) studied this, so you're the expert, unfortunately.

Makes sense. I don't appreciate it but makes sense. 🤪
Just kidding. I'll try to find something. 

> If you find a clear breaking point, then it may work to try building DDEV (it's easy) using a set of golang versions to see if you can detect whether that's the issue.

Okay. 

> A trivial test go program appears to be listed in the original discussions above. Using that you should be able to find out exactly what the problem is.

will have a look. 

> If I were you I wouldn't probably use `.test`, or I'd at least experiment with something that isn't as ambiguous in implementation. 

In what regard do you think it is ambiguous? I use it for what it is designed for imho:

https://en.m.wikipedia.org/wiki/.test

> Is it possible that Apple has done something to you?

Yeah. Could be. Name resolution is working though. 

And honestly, I personally don't want ddev to ever modify my hosts file. World it be feasible to have an option to never do it, like for settings management, which can be disabled as well?

**Comment by rfay** [comment]
> I personally don't want ddev to ever modify my hosts file

Sure, with `export DDEV_NONINTERACTIVE=true` it won't edit your hosts file (or ask for other confirmation).  That's what we use for our tests. And of course, if your browser is able to look up the DNS or whatever, everything is fine. DDEV only adds the hostname for the *browser's* purposes, not for its own. I don't think it ever cares about name resolution itself.

**Comment by helhum** [comment]
you made my day! thanks once again @rfay!

**Comment by gaambo** [comment]
Sorry, for adding to this old/closed issue, but just wanted to add that I'm running into the same issue. 
I've got a DNS in my network (on a NAS) that return 127.0.0.1 for *.dev.local. It works when pinging in shell, and it works in the browser, but ddev tries to add the hostname to /etc/hosts every time. I tried adding a custom resolver in macOS (by putting `nameserver 192.168.178.14` into `/etc/resolver/dev.local`). 

I'm using ddev 1.24.6 and macOS 15.5. 

Running the following in go (v1.24.4) also works and correctly return 127.0.0.1/that the IP was found: 
```go
package main

import (
	"context"
	"fmt"
	"net"
	"strings"

	"github.com/ddev/ddev/pkg/netutil"
)

func main() {
	name := "mysite.dev.local"
	// l1 is a host on my tailnet
	addrs, err := net.LookupHost(name)
	if err != nil {
		panic(err)
	}
	fmt.Println(addrs)

	// If they have provided "*.<name>" then look up the suffix
	checkName := strings.TrimPrefix(name, "*.")
	hostIPs, err := net.DefaultResolver.LookupIP(context.Background(), "ip4", checkName)

	// If we had successful lookup and the IP address looked up is local
	// then we don't have to add it to the /etc/hosts.
	if err == nil && len(hostIPs) > 0 && netutil.HasLocalIP(hostIPs) {
		fmt.Println("Local IP found for", checkName)
	}
}

```

My global_config.yml is 
```yml
fail_on_hook_fail: false
instrumentation_opt_in: false
internet_detection_timeout_ms: 3000
last_started_version: v1.24.6
letsencrypt_email: ""
mkcert_caroot: /Users/gaambo/Library/Application Support/mkcert
no_bind_mounts: false
omit_containers: []
performance_mode: mutagen
project_tld: dev.local
router_bind_all_interfaces: false
router_http_port: "80"
router_https_port: "443"
mailpit_http_port: "8025"
mailpit_https_port: "8026"
simple_formatting: false
table_style: default
traefik_monitor_port: "10999"
use_hardened_images: false
use_letsencrypt: false
wsl2_no_windows_hosts_mgt: false
web_environment: []
xdebug_ide_location: ""
```

I haven't tested with different ddev versions yet, since changing versions via homebrew seems not that easy.

**Comment by stasadev** [comment]
Hi @gaambo,

As you can see in the source code, it's wrapped in a condition:

https://github.com/ddev/ddev/blob/fbc85dc65171027537f664792d6309b69ce31492/pkg/ddevapp/hostname_mgt.go#L91-L104

1. your app's `.ddev/config.yaml` should have `use_dns_when_possible: true`
2.  `globalconfig.IsInternetActive()` performs a lookup for `test.ddev.site` - check if it resolves to `127.0.0.1`

**Comment by gaambo** [comment]
> * your app's `.ddev/config.yaml` should have `use_dns_when_possible: true`
> 
> * `globalconfig.IsInternetActive()` performs a lookup for `test.ddev.site` - check if it resolves to `127.0.0.1`

Thank you @stasadev. 

I added `use_dns_when_possible: true` to my project and global config during testing, but didn't include it in my comment. I tested again with this, but it still wants to add to the hosts file. 

But the IsInternetActive check is interesting, because pinging `test.ddev.site` returns `ping: cannot resolve test.ddev.site: Unknown host` in my shell and also the go script above errors out. I need to look into that, must be a DNS configuration problem on my side.

**Comment by stasadev** [comment]
> I added `use_dns_when_possible: true` to my project and global config during testing, but didn't include it in my comment. I tested again with this, but it still wants to add to the hosts file.

It's project only configuration, and it's `true` by default, unless you have `use_dns_when_possible: false`.

> `globalconfig.IsInternetActive()` performs a lookup for `test.ddev.site`

@rfay, do you think we need this check here?

**Comment by rfay** [comment]
I don't think your comments are relevant to this issue @gaambo so please open a new issue when you understand it more completely. This issue was about golang name resolution a couple of years ago.

@stasadev thanks for your suggestion in the [other PR](https://github.com/ddev/ddev/pull/7392#discussion_r2161441623), I'm sure it is valid.

@gaambo please note that `*.local` is not probably something that you should be using for this purpose. It's a special-use domain name, see https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml#local - It's mostly reserved for mDNS/Bonjour. So that can affect name resolution in general.

**Comment by gaambo** [comment]
Yes, you were right. I wrongly assumed since it's also on macOS that it would be the same problem.
For completeness' sake: My problem was, that FritzBox DNS rebinding protection prevented a lookup of test.ddev.site and therefore the isInternetActive check returned false. 

Thank you for your help and sorry for offtopic posting.

**Comment by rfay** [comment]
For context, docs on DNS rebinding and Fritzbox routers: https://ddev.readthedocs.io/en/stable/users/usage/networking/#restrictive-dns-servers-especially-fritzbox-routers

**Comment by helhum** [comment]
> My problem was, that FritzBox DNS rebinding protection prevented a lookup of test.ddev.site and therefore the isInternetActive check returned false.

Ah, this is likely, why this popped up for me as well some time ago. Since I control my own DNS server on my local machine and never want ddev to modify any system file, I set the following env var:

```
DDEV_NONINTERACTIVE=true
```

By doing so, I never need to worry about internet connection and always get the behaviour I want from ddev (thanks @rfay for the tip given on discord)
