### ISSUE TITLE
 No space left on device error when using the docker colima context.

### ISSUE THREAD

**Issue by droath** [drud/ddev#4453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Run `ddev start` without an error getting thrown when using the docker `colima` context.

### Actual Behavior

The following error is thrown when pulling the latest `drud/ddev-webserver` image:

```
failed to register layer: Error processing tar file(exit status 1): write /usr/share/perl/5.32.1/IO/Socket/IP.pm: no space left on device
failed to RunSimpleContainer to inspect database version/type: failed to pull image drud/ddev-webserver:v1.21.3: exit status 1, output= 
```

<img width="1400" alt="CleanShot 2022-12-12 at 15 54 43@2x" src="https://user-images.githubusercontent.com/371104/207172601-a478f1a5-8663-41b3-8804-3459d047f7cc.png">

### Steps To Reproduce

1. Install the package versions based on below version specifications. 
2. Then run `colima start`
3. Next run `ddev start`

> I think the `lima` package might be the culprit as that was the most recent change, but that's just a hunch.

## DDev

ddev version v1.21.3

## Docker

Docker version 20.10.21

## Colima

colima version 0.4.6
git commit: 10377f3a20c2b0f7196ad5944264b69f048a3d40

runtime: docker
arch: x86_64
client: v20.10.21
server: v20.10.14

## Lima

limactl version 0.14.0

## Qemu

qemu version 7.1.0

**Comment by rfay** [comment]
Hi @droath - You have to allocate adequate space for your colima disk, and it has to be done at the beginning. The recommended setup from https://ddev.readthedocs.io/en/latest/users/install/docker-installation/#macos is to start with 100GB, `colima start --cpu 4 --memory 6 --disk 100 --dns=1.1.1.1`

Unfortunately there is no way to resize a colima disk, you have to start over. 

You can certainly delete all your existing images with `ddev poweroff && docker rm -f $(docker ps -aq) && docker rmi -f $(docker images)` and that may make some space for you.

Otherwise, you'll need to `colima delete` and then recreate. But before you do that do snapshots of all your projects, `ddev snapshot --all`

**Comment by droath** [comment]
Thanks @rfay!

I don't know what happened, somehow all my docker container/volume data was deleted. The reason I was getting that error was due to the default colima template being used, which had disk set at 0. I was able to recreate the colima instance using your recommendation. I was able to restore the site from a previous database backup. Thanks for your help!

**Comment by rfay** [comment]
I'm glad it's working for you. The default colima disk is 60GB. 

```
# Size of the disk in GiB to be allocated to the virtual machine.
# NOTE: changing this has no effect after the virtual machine has been created.
# Default: 60
disk: 60
```
