### ISSUE TITLE
Support Percona DB

### ISSUE THREAD

**Issue by claudiu-cristea** [drud/ddev#4508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Our organisation CI/CD runs Percona and we can't determine the type of database from our code. Running on MariaDB or MySQL should be enough for 99.9% of the cases, however... it would be great if the local environments are more close to what's running in pipelines and in production.

### Describe your solution

Support also Percona along with MariaDB & MySQL

**Comment by rfay** [comment]
Percona is MySQL, I think it will always work for you as such.

However, Percona never publishes arm64 versions of their packages (https://www.percona.com/downloads/percona-distribution-mysql-ps/LATEST/), and they don't do arm64 docker images (https://hub.docker.com/r/percona/percona-server/tags), so nobody on mac M1 or arm64 linux could use them; impossible to support. 

I jump through [amazing things](https://ddev.readthedocs.io/en/latest/developers/release-management/#maintaining-ddev-dbserver-mysql-57-80-arm64-images) with MySQL for the same reason, and won't be adding another problem like that. 

So I recommend using the parallel MySQL, it will likely get you a full 99.9%, maybe more. I'm pretty sure they try to track MySQL 8.0 completely.

Happy to continue the conversation, and if Percona ever comes out with arm64 support I might reconsider, but since you're the first ever to ask after many years.... mysql and mariadb seem to be doing fine for everybody.

**Comment by claudiu-cristea** [comment]
Fair enough. Thank you

**Comment by MakerTim** [comment]
Hey Rfay

It seems they are exploring arm64 support.
https://hub.docker.com/r/percona/percona-server/tags?page=1&name=mul
![image](https://github.com/ddev/ddev/assets/1375359/21c6cb00-ba24-4116-a8df-fbab0b059184)

**Comment by rfay** [comment]
Great! Still not seeing arm64 packages at https://www.percona.com/downloads, I wonder how they're building the images.

**Comment by KeldorDE** [comment]
Currently, the Percona Server version is only available in the Percona Lab Registry, you can find it here https://github.com/Percona-Lab/percona-server-arm

No stable version has been released yet.

**Comment by rfay** [comment]
Thanks! they're certainly not all-in on arm64, but they do have a full set of "multi" images now.

Could you please restate why Percona is more appropriate for local dev than mysql:8.0?  Reading the docs it seems very unlikely that you'd find a difference in local development. It doesn't seem very likely that you'd find a difference in production either, since it's mostly a repackaging? Remember that supporting an additional database type is not just a development effort, it's a permanent commitment to maintenance.

**Comment by KeldorDE** [comment]
That's a good point. I became aware of this issue because I could not import my Percona dump into DDEV with MariaDB due to a syntax error. Apparently the MySQL dialect of MariaDB is not compatible with Percona.

I have now switched my DDEV project to MySQL 8.1 and so far the import runs without any problems. So I agree with your argumentation why it doesn't make sense to integrate Percona into DDEV.
