### ISSUE TITLE
import-db claims to fail (but doesn't) when settings.php managed by user

### ISSUE THREAD

**Issue by rfay** [drud/ddev#451]
## What happened (or feature request):

I have a D7 site, [fredthrall.com](https://github.com/rfay/fredthrall.com/tree/site/sites/default), where the settings.php is managed by git, and has an include for settings.local.php. As a test, I added a correct settings.local.php pointing to db/db/db/db and tested it. Then I did an import-db and saw this failure. 

```
$ ddev import-db --src=.tarballs/fredthrall.sql.gz
Failed to import database for fredthrall.com: failed to write configuration file for fredthrall.com: settings files already exist and are being manged by the user
```

But the database was in fact correctly imported. There are a few problems here:

- [ ] The error message is not correct. It should just say the settings files exist and are managed by user.
- [ ] We can hope that nothing is being *manged* by the user (spelling in error message)

Overall we need a better solution to the case where the user has a checked-in settings.php.

## Related source links or issues:

**Comment by rickmanelius** [comment]
Leaving as incubate while we decide on our approach to address this.

**Comment by rfay** [comment]
This is confusing to the user and inappropriate information, and becomes more important with backdrop and typo3, where it's more likely to happen (they manage their own settings files, we add on the equiv of settings.local.php)

**Comment by rickmanelius** [comment]
Noted. It sounds like a workable path forward would be to not simply error out but to message something akin to the following:

* DDEV attempted to add the appropriate database connection information to INSERT APPTYPE config file located INSERT CONFIG LOCATION, but one already exists. Therefore, you will need to manually confirm the following DB configurations: username => db, password => db, host => db, database => db"
* Still, the related issue #517 (which also notes many, many other related issues) may need to be addressed first because this could ultimately change the behavior. Flagging with "needs decision" in the hopes that we can get that resolved/unblocked and then see if this issue still holds true.

**Comment by rickmanelius** [comment]
This has resurfaced as a result of #692. See the following Twitter communication 
https://twitter.com/rachel_norfolk/status/979632809873731584 by @rachellawson.

**Comment by rfay** [comment]
Just an FYI that it no longer fails at all, it just emits a warning:

```
$ ddev import-db --src=.tarballs/randyfay.sql.gz
Unable to create settings file: Failed to get Drupal 7 settings file path: settings files already exist and are being managed by the user
Successfully imported database for randyfay
```
The same warning happens at `ddev config` time. 

We could certainly soften and enhance the language so that people know it's their responsibility to manage settings. But import-db absolutely works in this situation, as does `ddev config`. 

Other users have suggested that we use a file other than settings.php and  settings.local.php as our go-to way to import ddev-specific settings, and it's a mighty reasonable suggestion. The downside is that it forces users to be aware of ddev and to add an include to their main settings file, which is not obvious and one more step for them.

**Comment by rfay** [comment]
This is adequately resolved by changing to a warning.
