### ISSUE TITLE
Always -y on drush commands causes unexpected behavior when using drush in container

### ISSUE THREAD

**Issue by rfay** [drud/ddev#455]
## What happened (or feature request):

We added the default "-y" to drush via a global [drush settings file](https://github.com/drud/docker.nginx-php-fpm-local/blob/master/files/etc/drush/drushrc.php) in the nginx container. The primary reason was that otherwise `ddev exec <anything>`  can hang if drush asks for input, and we didn't figure out a way around that.

However, there are drush commands that you definitely want to see the output from before you do anything. For example, `drush upc`, `drush sql-drop`, etc. You absolutely want to see what's about to happen before it happens. Most of these (like `drush upc`) would normally be executed interactively ssh-ed into the container rather than via drush exec.

IMO we should either:
* Figure out how to handle interactive commands with drush exec or
* Make the -y happen only when drush is being run via `ddev exec`

**Comment by rickmanelius** [comment]
Would this be a simple matter of including a regex when using ddev exec to match for drush and confirm a -y is present and (if not) add it?

**Comment by rfay** [comment]
Another super-simple approach (suggested I think by @beeradb ) would be for ddev exec to set an environment variable and for us to set the -y when that's present. This has bit me a few times, even in the demo today - I expect to get to confirm a drush command (but accept that I can't inside exec).

**Comment by rickmanelius** [comment]
At a surface level, I'm onboard with an environment variable because that exposes to the end-user that this is occurring. My only caveat to this is that a user disabling this would experience some issues with drush not working if the command being run needed an interactive prompt. This could also be problematic if people stuff drush commands in their pre/post hooks and then try to share this config among team members but they have discrepancies on their environment variables.

The regex example to append a -y outside the container might be the best way to normalize this for consistency as well as prevent a user from getting stuck with an interactive prompt. We'd still probably want to warn or send a notice to the end-user telling them that we're doing this in case.
