### ISSUE TITLE
Craftcms project type assumes and writes .env variables on every startup

### ISSUE THREAD

**Issue by mikesnoeren** [drud/ddev#4552]
### Expected Behavior

I would expect the project type craft to not assume things for my project and definitely not fill up my `.env` file with variables that are not being used.

### Actual Behavior

Whenever I start a craftcms project, the variables below get added to my .env file automatically.
```.env
MAILHOG_SMTP_HOSTNAME=127.0.0.1
MAILHOG_SMTP_PORT=1025
PRIMARY_SITE_URL=http://website.ddev.site/
```

The PRIMARY_SITE_URL variable is unused in most (if not all) of our projects, we can't assume people use that, so we shouldn't set it.

We don't setup our sites to use mailhog with those variables either, we do it a different way. 
Unless it auto sets up mailhog for only the ddev environment somehow, it is ok. But then again, should we assume everyone uses mailhog?

**Comment by rfay** [comment]
If you want to disable this behavior, you use `settings_management_disabled: true`. It sounds like that's what you want?

**Comment by rfay** [comment]
Hmm, I don't think these are "opinionated" for Craft 4 are they?

**Comment by lindseydiloreto** [comment]
I think the inclusion of Mailhog especially is opinionated. The system decided for me that I should be using Mailhog, I never opted into that and don't plan on using Mailhog.

Craft 4 was where it began to "magically" see variables in the `.env` file, without first having to pass those values through a PHP config file (as was the standard in Craft 3). I can definitely see a (very limited) use of autopopulating the `.env` variables on behalf of Craft, but as we can see here, it's a pretty slippery slope.

In my personal opinion, **only the DB values should be automatically set**. While I appreciate the Mailhog and Primary Site URL contributions, they can be easily added later if necessary.

I would recommend the following:
1. Only pre-set `.env` values that begin with the `CRAFT_DB_` prefix. This ensures that only the database connection is affected, and all other settings are ignored.
2. If a particular variable is evaluated to be _the same as its default value_, please skip it and don't write it to the `.env` file. For example, the default database driver is already set to `mysql`, it doesn't need to be redundantly stored as `CRAFT_DB_DRIVER="mysql"`.

^ By following those two relatively straightforward guidelines, we can ensure that DDEV is able to properly connect to Craft, without interfering too much in the `.env` file otherwise.

Thanks again for all of your hard work on the `craftcms` project type and DDEV in general! ❤️

**Comment by lindseydiloreto** [comment]
Related conversation on Discord:

> https://discord.com/channels/664580571770388500/1065008302745976893/1065008302745976893

**Comment by rfay** [comment]
Mailhog has been supported on all project types for years and prevents unwanted accidental emails from going out, in addition to allowing easy debugging of mail features. 

It's *so* easy to turn these things off. `disable_settings_management: true` or use the completely unopinionated `php` project type.

**Comment by lindseydiloreto** [comment]
It's great that Mailhog is available to all project types, but the other project types don't inject that into the `.env` file (AFAIK).

I was mainly just leaving my two cents on this thread for historical record, since it seemed relevant to the parallel conversation we had on Discord. 

> `disable_settings_management: true`

That's what I've done for this particular Craft 3 project. Still weighing whether to revert back to the `php` project type. I really do like having the `ddev craft` command available, but it's technically a "nice to have".

**Comment by rfay** [comment]
The other project types inject mailhog settings into the equivalent settings setup. So for Drupal, settings.ddev.php. Also controlled by `disable_settings_management`. 

If you like the `php` project type more (don't think it should matter) you can just copy the global ~/.ddev/commands/web/craft into your project's .ddev/commands/web and edit it slightly so it doesn't exclude php project type. Or just remove the #ddev-generated from ~/.ddev/commands/web/craft and take it over that way and remove the 
```
if [ "${DDEV_PROJECT_TYPE}" != "craftcms" ]; then
    echo "The craft command is only available in the craftcms project type. You can update this in your project's config file, followed by restarting the DDEV project."
```

**Comment by rfay** [comment]
DDEV doesn't try to do everything everybody could ever want, because it can't. But it tries to leave space for people to do whatever they want on their team and their project.

**Comment by lindseydiloreto** [comment]
Those are great tips for using the `ddev craft` command in the `php` project type, thanks @rfay!

**Comment by bossanova808** [comment]
Can I add to this discussion - I think `disable_settings_management ` should definitely default to `false` for _existing_ projects.  This broke my ddev / craft 4 project when I came back to it after some time away, and in a way I couldn't immediately understand from this error:

```
Failed to start craft-dev: template: templateStringToFile:/home/jeremy/ddev-projects/c4-dev/.env:7: function "siteUrl" not defined
```

And I think `PRIMARY_SITE_URL` should be added only if the existing & typical `CRAFT_SITE_URL` is not already present - otherwise it's just doubling up right?

Personally am not fussed about Mailhog, other than to note that Craft has a config setting for a similar thing already:
https://docs.craftcms.com/v3/config/config-settings.html#testtoemailaddress

```
        'testToEmailAddress' => (\craft\helpers\App::env('SEND_ALL_EMAILS_TO')) ?? null,
```

So in Craft's case, Mailhog is likely to be irrelevant to most.

**Comment by rfay** [comment]
Settings management has been the default in DDEV for more than 6 years now. The problem here is that there is no differentiation between Craft 3 and Craft 4, and perhaps there should be. DDEV's craft setup right now is oriented at Craft 4.

**Comment by bossanova808** [comment]
Everything I wrote above is about a Craft 4 project, just for info.  Nothing to do with Craft 3 - I've only moved to using ddev with Craft 4.

**Comment by rfay** [comment]
@bossanova808 If you have a specific bug related to the .env variables added by DDEV in a Craft 4 project, could you please open a new issues with the specifics? I haven't heard of trouble with Craft 4.

**Comment by lindseydiloreto** [comment]
FWIW, I believe the OP started this thread with a Craft 4 site (I am inferring based on contextual clues). Similarly, my comments were largely about Craft 4, outside of this one historical footnote:

> _Craft 4 was where it began to "magically" see variables in the .env file, without first having to pass those values through a PHP config file (as was the standard in Craft 3)._

... and a remark that I used `disable_settings_management: true` to resolve the issue on a Craft 3 project.

Sorry for any confusion, I do believe this thread is already about Craft 4.
