### ISSUE TITLE
META: Composer issues

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#475]
This continues to surface as something that needs to be addressed, particularly with pain points around Drupal release of 8.4.

So many links to draw from and conversations to consolidate here. Also services like https://composy.io/ to review/check out.

**Comment by rickmanelius** [comment]
This looks like a useful issue to watch https://www.drupal.org/node/2912410

**Comment by tannerjfco** [comment]
After spending some time with Drupal 8.4 and composer, I believe these are the notable issues to look at in relation to ddev:

- Composer complains about running as root, since our web container runs as such. It still runs successfully, it just complains every time. We've discussed updating the container to run non-root, specifically in relation to #126, but we haven't made this a task yet. Updating to run non-root would resolve a similar issue for wp-cli that we're working around.
- `composer create-project` won't run in a non-empty directory. This means a user can't config and start from a new directory, as our .ddev folder exists. The other problem (assuming one worked around the first) is that a user would need to update .ddev/config.yaml after composer completed so as to update the docroot (it would need to be blank to start up for the create-project command, then it would need to be updated to the correct docroot after)

The first problem has an actionable course for resolution. The second one, not as much. Probably the best we can do is some documentation for getting around this. I see a couple possible workarounds we could document:

- We can test and document a way to use [the composer image](https://hub.docker.com/r/library/composer/) to run the create-project if the user doesn't want or can't have composer installed locally.
- We can require that composer is installed locally for this command.

These issues aside, I'm not sure there's a lot else we can do to improve composer support in the context of ddev.

**Comment by rfay** [comment]
In my experimentation with composer, I have a strong preference for doing stuff on the host and not in the container, which mitigates all of this. I'd be interested to see which way people end up doing it.

**Comment by helhum** [comment]
> In my experimentation with composer, I have a strong preference for doing stuff on the host and not in the container

Which only works if you actually have PHP and composer installed on your host, which isn't necessarily the case if you decide on a virtualized development environment, where one of the major advantages is not to have anything installed on your host system.

**Comment by rfay** [comment]
Closing in favor of https://github.com/drud/ddev/issues/1131, which is a complete composer-in-container proposal.
