### ISSUE TITLE
Manually stand-up a Typo3 site

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#500]
## What happened (or feature request):

* Feature request

## What you expected to happen:

While ddev contains support and business logic for WordPress and Drupal 7/8, we've had questions from our partners at OSP (notably @horncologne) about the level of effort required to stand up a Typo3 site. This was briefly touched on in the [CMS/hosting provider meta issue](https://github.com/drud/ddev/issues/469).

Given that we technically support non-Drupal/WordPress php-based apps, I propose the following acceptance criteria:

* Download, configure, and `ddev start` a base Typo3 codebase.
* Research and determine how Typo3 handles database config and file storage.
* Create a manual set of instructions for getting to the Typo3 install screen.
* Review the current ddev codebase and determine a rough (+/- 2 day) LOE to provide app detection, database config file support, and any other logic that we already provide for WordPress/Drupal.

## Related source links or issues:

* https://typo3.org/

**Comment by rickmanelius** [comment]
Just for the heck of it, I ran a VERY quick test to see if I could figure this out on my own. Here are the initial results.

* App type checking. During the `ddev config` step we note support for Drupal7, Drupal8, and WordPress. We probably need a generic PHP type. I got around this by just specifying Drupal7 and I was able to proceed with a `ddev start` and get to the install screen.
* install.php. Typo3 has two different install.php's. The top level one is correct.
* Install Requirement: There is the need to generate a "FIRST_INSTALL" file at the top level webroot in order to proceed on an installation. Presumably this is to ensure the person has access to the server to proceed.
* The first time loading /install.php resulted in a 500 error. The next load resulted in a report (see attachment). This report indicated some requirements that our current nginx container lacks and will need to be addressed. Note that this might be solved by updating our base container to PHP 7.1.X.

I'll pick this up another time, but this was a helpful first pass.
<img width="1202" alt="typo3-install-error-500-2017-10-09" src="https://user-images.githubusercontent.com/913096/31355893-40b625b8-acf9-11e7-8f9a-6693485c9935.png">

**Comment by rickmanelius** [comment]
We had a productive call with @wmdbMattes. I need to update the notes and pull into GitHub, but I wanted to at least leave a trail to our internal notes so that this isn't a blocker for the next steps of us standing up a site manually and getting a sense of the LOE to add support.
https://docs.google.com/document/d/1Czk-KPHDXQrdITkYC49OZlUDMHbMTb0XN4weSS9GZ5E/edit#

**Comment by rfay** [comment]
Upgrades to the web and db container were required for typo3; they both improve Drupal usage, so that's good.
https://github.com/drud/docker.nginx-php-fpm-local/pull/41
https://github.com/drud/docker.mysql-local/pull/28

After getting things "close" I still had a major problem with typo3 where it would reload the db config page no matter what I did (and without any error) - see https://screencast-o-matic.com/watch/cbX6ry22Ja .  @wmdbMattes and @lolli42 were beyond helpful in Slack and we tried various things to resolve it. 

I put together https://github.com/rfay/typo3git/tree/8.7.8 (see readme) to slam-dunk demonstrate the problem. But @wmdbMattes had no trouble with that. This morning I tried on a MBP 2015 and I also had no trouble. Then I reset my Macbook Air 2013 docker install to factory and no longer can reproduce the problem myself.

So I don't know if this insidious problem is one we'll see periodically, or if it was just a betrayal by docker.

**Comment by rfay** [comment]
This is definitely done, I've put one together several times. I've seen the problem above demonstrated on my 2013 machine and also on another typo3 contributor's 2011 machine, but on no other machine, so it's unclear if it's a typo3 bug related to machine age, a docker bug related to machine speed, or something else. But it's not hard to get an install done on newer machines that I've tried. 

The special containers are no longer special - they've been committed and are in upstream/master.

**Comment by rickmanelius** [comment]
This is a set of related needs for Backdrop that we'll probably also to address for TYPO3 once we're ready to provide official support https://github.com/drud/ddev/issues/515#issuecomment-349085305.
