### ISSUE TITLE
Proposal: Package ddev in a manner that is turnkey for Drupalcon Code Sprints

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#501]
## What happened (or feature request):

Feature Request

## What you expected to happen:

As per a conversation with @horncologne, those leading code sprints are currently evaluating the possibility of a Docker based stack for sprint camps at Camps/Cons. This is a use case envisioned a while ago and we are highly motivated to make it happen.

## Reference

* Internal collaboration document to bake into a proposal.
https://docs.google.com/document/d/1slnml-Y_XRPEcmmd6XNK21xp01g1NR8AFnSkIy3DZ9A/edit

## Participants

* @rickmanelius
* @rfay 
* @cweagans 
* @cweagans 
* @horncologne

## Acceptance Criteria

* [x] Brainstorm and document ideas on how to address this in a small/medium/large bucketing (@cweagans and @rfay)
* [ ] Split out a new issue to address the most basic (small) use case of providing docker images in the tarball (@rickmanelius)
* [ ] Consolidate efforts across all fronts, including @BrianGilbert and @HornCologne.
* [ ] Generate a proposal that addresses the medium/large LOE versions (@rickmanelius, @cweagans, and @rfay )
* [ ] Circulate to code sprint leads at Drupalcon/Drupal camps to gauge their interest and solicit feedback (@rickmanelius)
* [ ] Convert this from a proposal to a deliverable with specific actions, acceptance criteria, deadlines, etc.

**Comment by rickmanelius** [comment]
Current notes from a meeting w/@rfay and Brian Gilbert
https://docs.google.com/document/d/1OJucfCMiToVf05tZaUzlsM5BPD61A0eZKwcR9RDcxWs/edit#

**Comment by rickmanelius** [comment]
Next actions:

* [ ] Reach out to Brian for confirmation of notes.
* [ ] Break out research acceptance criteria

**Comment by rickmanelius** [comment]
@cweagans Just drawing your attention to this.

**Comment by rickmanelius** [comment]
Trying to consolidate this because this is spanning 5 different individuals on the team that are all going to be a part of this process. @cweagans and @rfay had some great ideation on what an implementation strategy would look like (whether we were actively there or not). We also have @CRReigan looking to help coordinate outreach with the various camp organizers. Additionally, we have our partners at OSP starting to generate some materials that could prove to be of value.

To that end, I'm going to attach a blank doc that will serve as an easier means of collaborating until we can get a more consolidated plan of attack, which would then be brought into the issue queue.

IMHO, this proposal should focus on the what/how/why/who question and then we can get a consolidated punchlist and LOE. Therefore, I consider this ticket now "actionable" from the perspective of getting to a proposal and then we can either split out a new issue or update/extend this issue as a meta issue to track implementation.

**Comment by rickmanelius** [comment]
Updated issue summary with AC, reference material, and moving into our board.

**Comment by cweagans** [comment]
I think it would be cool to do the following:

* Build a box that houses:
    * A handful of Raspberry Pis
    * A gigabit switch
    * A wireless router
    * Power for everything
    * Maybe if we want to get fancy, we can put a small monitor on it that shows a Grafana dashboard
* Run Kubernetes on the rPis, and put _our hosting platform_ on top of it
* On the hosting platform, run the following:
    * An HTTP server that can provide downloads of Docker for Mac and Docker for Windows, as well as the latest `ddev` binaries + some branded docs for how to install everything
    * An apt/yum repository that mirrors Docker packages
    * A docker registry set up to be a [mirror](https://docs.docker.com/registry/recipes/mirror/)

If we don't want to bother with using our hosting platform just yet, we could probably just as easily use a single box that might be a bit more beefy (I've got a micro atx case I can donate to the cause, or there are a ton of boxes designed to run pfsense on ebay).

I know @rfay said something about sprints using Resilio Sync, but that's a commercial offering, and I'd rather lean toward open source solutions so that we can support them long term. Distributing the files via bittorrent on the local network is a neat idea, but it takes away potential touch points with people that are sprinting (i.e. if they have to use their web browser to go to a page we're hosting on the local network, then we can brand all the pages in a nice way).

I'd also be willing to make a nice wooden box for all of this stuff that'll stand out in the sprint room, but that's probably a secondary effort.

**Comment by rfay** [comment]
The intent here for the long term for for Drupal sprints to be able to use this packaging on their own, all over the world. So the first part is to make it easy from a packaging/software perspective. And it has to be manageable by people who aren't familiar with special hardware, etc. In other words, at most of these sprints, the estimable @cweagans will not be available.

**Comment by cweagans** [comment]
I agree. I would want this to be something where sprint organizers can just plug the box in and everything else "just works" from there. We will occasionally have to do updates on the box (to make sure that it's got updated copies of everything), but that's something that can be automated as well.

**Comment by cweagans** [comment]
I would say that the MVP here is just an HTTP server with downloads for all the things. We can export the Docker images and have people import them manually - a registry might be a good future improvement.

**Comment by cweagans** [comment]
Recap from convo with @rfay and @rickmanelius today:

1) we provide hardware when we are in attendance
2) we provide steps to provision when we are *not* in attendance
3) whatever solution we come up with must be turnkey so that we don't have to play tech support
4) we don't step on Brian's toes
5) must be sustainable for both us and the community

**Comment by cweagans** [comment]
@rfay @rickmanelius https://docs.google.com/document/d/1_jG0JTD3Kyv5EUYTUomZgA2aKe4ou98fy0fPmEpbWD4/edit?usp=sharing may be of interest to you. This pretty much encapsulates what I was thinking, and results in a pretty seamless experience.

It doesn't use resilio sync (I thought we could do better in terms of how transparent the setup was), but I think if we can agree internally on this, we should pitch Brian and see what he says.

**Comment by rfay** [comment]
I'd like to see the whole test-sprint thing as three very separate things: 
1. Getting a nice ddev package that doesn't require external (docker) dependencies
2. Getting a full sprint package that doesn't require external dependencies (which is what I think this issue first encompassed)
3. Taking over the whole onsite distribution problem, which seems to be what the google doc above is pointing at.

**Comment by rickmanelius** [comment]
Surfacing a parallel doc from OSP
https://docs.google.com/document/d/1fkNJMCt0UBbCOFDhbsbqAHuM9SNwZXSTHWsQsBdxnjM/edit#heading=h.78j13uj8axrk

**Comment by rickmanelius** [comment]
Sent a follow-up email to @ briangilbert (didn't want to ping him without him subscribing to the issue himself) to see how we can triangulate our efforts.

**Comment by BrianGilbert** [comment]
I'm here guys.. just having some discussions with others in the mentoring team before I re-engage fully

**Comment by BrianGilbert** [comment]
I've also requested access to all the google docs linked here, be great if that could be approved please

**Comment by rickmanelius** [comment]
Updated issue summary with proposed acceptance criteria to continue and move this proposal process to a completion point.

**Comment by rfay** [comment]
I created https://github.com/drud/quicksprint for the folks at the London event. It has potential, though it's a newborn. Feedback requested. You can download the results of running the script at https://github.com/drud/quicksprint/releases, and when you untar that it has a readme for the end user.

**Comment by mradcliffe** [comment]
I successfully ran install_ddev.sh and start_ddev.sh this morning on my Slack box using docker-17.12.0-ce, docker-compose 1.19.0 (installed via a pyvenv I added into the root so I don't mess up my box), and using DDEV_GID (an issue with my particular system and not something I use when testing MacOS and Windows 10).

- Nice. I was able to copy some modified ide and irc container yamls into drupal8/.ddev, but I'm not sure where to include that in the quicksprint repository. Maybe a containers directory, and then copy those once the packaging script has run ddev config?
- If I needed to stop, I had to change directory into drupal8 manually. Probably only needs a bit of docs there. I think sprinters would normally be going into drupal8 directory to do all operations anyway, but might not realize that at first because an user would run the install/start scripts from the tarball root.
- I do not think pre-installing a database is necessary because sprinters often pick up tasks related to the installation process (testing, UX, etc...) and the [umami (Out of the Box initiative)](https://www.drupal.org/project/issues/search?projects=&project_issue_followers=&status%5B%5D=Open&issue_tags_op=%3D&issue_tags=Out+of+the+Box+Initiative) profile exists now.
- We probably need to include license file when distributing the external packages, images and 7za.
- Consider coping a .gitignore into the drupal git repo root so that the special directories are ignored and we don't accidentally generate bad patches.

I'll test on MacOS Sierra and Windows 10, Docker ToolBox (I can't switch it over to Hyper V for some reasons).

I'm not sure if I can get a PR out in time to do these for testing at MidCamp next weekend, but I'll try my best.

**Comment by rfay** [comment]
Thanks! Your issues and PRs are very welcome at https://github.com/drud/quicksprint - 

I haven't tried docker toolbox lately, but we really want to get that working, because lots of people don't have Windows 10 Pro.

**Comment by mradcliffe** [comment]
Yes, I'll plan on creating issues/PRs there. I wanted to add testing feedback here since it had the most activity.

I tested Windows 10 Pro, Docker ToolBox this morning and that was fairly functional. The ddev.exe wasn't copying correctly (missing `%HOMEPATH%` on my machine?) and the start_ddev.cmd couldn't find the db to import using Docker QuickStart Terminal, but I wasn't expecting any miracles. It did however create and start the containers and router fine. :-)

**Comment by mradcliffe** [comment]
I tested MacOS Sierra using Docker 17.12.0-ce-mac49 (21995). No issues.

**Comment by cweagans** [comment]
Can this be closed now? Or are there remaining tasks?

**Comment by BrianGilbert** [comment]
yes I think so
