### ISSUE TITLE
Manually stand-up a Backdrop CMS

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#515]
## What happened (or feature request):

* Feature request

## What you expected to happen:

We tested Backdrop at BADCamp and it looks like it won't be a heavy lift to provide official support. We should explore this further as part of the larger initiative (see #469).

## Related source links or issues:

* [META: inventory, research, and rank CMS and hosting provider support plans](https://github.com/drud/ddev/issues/469)

**Comment by rickmanelius** [comment]
Link to meta issue https://github.com/drud/ddev/issues/469 and updates to the nginx container https://github.com/drud/docker.nginx-php-fpm-local/issues/39.

**Comment by rfay** [comment]
Mostly there were just two problems with Backdrop:
1. You have to fool it and tell it was D7, and then it tries to do a couple of (not-too-relevant) things that fail, like touching sites/default/settings.php. We could solve this by having a "none" apptype that didn't try to do things of this type. That would help the typo3 example as well.
2. Drush doesn't work with Backdrop out of the box. You have to install some backdrop drush commands. But in order to do that you have to use the composer-type drush install. There is minor risk that drush with the backdrop commands could detect a drupal7 site as backdrop, but Jenn believes that has been resolved. Bottom line is we'd need to change our drush install technique and add the backdrop commands to it. The basic info is at https://backdropcms.org/news/dealing-drush, and I think Jenn would help us if we couldn't get it going.

**Comment by rfay** [comment]
This one is actually complete, but we can turn it into "fully support backdrop" after #535 lands, or we could close this one now. The modest work required to support drush shouldn't be too hard based on https://backdropcms.org/news/dealing-drush, and may well make all users happy. (In fact, the support of multiple drush versions can be undertaken separately, without trying to fully solve the backdrop issue.

**Comment by rickmanelius** [comment]
@rfay I'm fine with closing for now as long as you feel like the comment left on October 23rd is enough of a trail for someone to follow when adding this as a first-class citizen.

I anticipate the full list to be:

* Ensure "backdrop" is an official app/site type.
* Ensure we have a way to properly distinguish between Drupal 7 and Backdrop detection.
* Any differences in the handling of settings.php?
* Perhaps as part of a `ddev config` with Backdrop we warn users or at least link them to documentation on any Backdrop specific issues as well as how to install drush via composer on their host machine. I don't think we take this on per se, but providing an appropriate trail makes sense. That documentation could also link to known issues, such as cron throwing a 500. Or maybe that is something we just file in their issue queue with instructions on how to recreate.

Closing for now unless there is more to add beyond that.

**Comment by jenlampton** [comment]
> Running cron manually (from status page) in Backdrop failed with a 500, but this may be a backdrop problem. It's also an unusual thing in local dev to worry about cron.

Running cron manually on MAMP and Lando both seem to work fine, I'm not sure why cron might fail on DDEV. I haven't heard of this before. Perhaps its something about your specific site, and not the environment?

**Comment by rfay** [comment]
This was only when you and I ran it @jenlampton; you had suspicions at the time, just noted here check that particular issue.
