### ISSUE TITLE
Standardize usage to "project", away from "app" or "site", at least in interacting with user

### ISSUE THREAD

**Issue by rfay** [drud/ddev#526]
## What happened (or feature request):

In ddev we use "app" and "site" quite a lot. We should probably use one or the other, at least in user-facing stuff.  I'm a fan of "site" because I think it's what we're generally working with.  To me "app" usually refers to a smartphone app or an application that runs on the OS, and a "site" usually means HTML/css/js served from a web server.  I know that the usage has started to shift a bit (like some companies with smartphone apps will refer to their "web app" as an alternative). 

Anyway, we should choose the terminology that is most meaningful to our developers and go with it consistently.

Edit: We've agreed (below) to go with "project" when interacting with the user.

## Remaining Tasks

* [ ] Search/Replace and ensure all ddev CLI tests pass.
* [ ] Open up a ticket for DDEV UI

**Comment by rickmanelius** [comment]
Okie dokie. Here's some initial thoughts to unblock this.

## Intention

* Ultimately we want a word that is clear, enhances communication, and reduces confusion.
* It should also address the needs that we currently support (Drupal and WordPress website development) with an eye towards the future (Javascript front-end frameworks, API first projects, etc).

## Options

1. Site
2. App
3. Project (docksal uses this terminology)
4. Service (similar to microservice)
5. Repo

I only think options 1-3 deserve serious consideration although there's something to be said about the 1-1 nature of a repo with a ddev config...

## Evaluation

### "Site"

#### Pros

* It's a term the Drupal and WordPress communities recognize and use almost universally.
* I would hazard a guess that 99+% of all Drupal and WordPress projects end in a website (versus just an API or an intranet).
* There is generally (not always) a 1:1 relationship between a repo and a FQDN.

#### Cons

* It's possible to have multiple domains per code+database backend. Think domain access, multi-lingual sites, etc.
* CMS's like Drupal 8 are seeing more API first/only implementations where a "site" is not the most accurate descriptor.
* Looking towards the future, there are use cases where this is an inappropriate label.

### "App"

#### Pros

* This is a term that doesn't assume a certain category (e.g. it could be a CMS or a static site generator or an API/service).
* This balances being too specific and sometimes inaccurate (e.g. "site") while not being so generic to lose meaning (e.g. "project")
* One app/repo can power multiple front ends.

#### Cons

* This could potentially be confused with mobile or desktop apps versus web apps.
* Most in the CMS space (a majority of our initial end users) would be more familiar and comfortable with "site".

It's possible to fix some of these issues by extending to "Web App", but there are still situations where that would not be the correct terminology.

### "Project"

I've seen others use this term and while I appreciate it's accuracy (I mean literally any repo could be a project regardless of it's a CMS, static site, REST service, etc), I'm wondering if it's too generic.

## Proposal

My vote would actually be for "project" even though it's not something we've discussed at this time. In fact, we used this phrase a lot at a previous agency because a single client might have multiple projects in flight and each project might include multiple websites off a single repo. Additionally, I keep thinking about use ddev cases we've been having with customers where even "app" or "site" would not be an appropriate label.

I'm looking for sanity checking on this one because I know that it will take a bunch of changes in both the codebase as well as the documentation.

**Comment by rfay** [comment]
I could go with "project" for sure. It could possibly require some rewording of some messages.

To be clear we only need to change the code where it's interacting with the user; We mostly use "app" in the code for variables, and that probably is ok to stay.

**Comment by rickmanelius** [comment]
Reaching out for one last sanity check. @tannerjfco or @cweagans... any thoughts on standardizing around "project" instead of "site" or "app"? If you have no opinion/objections, then "project" it is and we'll get a language standardization PR out for docs and end-user usage.

**Comment by cweagans** [comment]
Project sounds great. :+1:

**Comment by rfay** [comment]
Edited OP and title. Let's do this after the upcoming release.

**Comment by rickmanelius** [comment]
Also updating assignee. Whomever wants to take this on is fine by me.

**Comment by rickmanelius** [comment]
@rfay I believe that this is now addressed given the PR merge. Please confirm and (if complete) close out at your earliest convenience!

**Comment by rfay** [comment]
No, the PR merge only addressed docs, not code, there's plenty more to do here.

**Comment by rickmanelius** [comment]
Updating assignee field in case @cweagans has bandwidth this week.
