### ISSUE TITLE
"ddev ssh" inappropriately returns (and exclaims) last executed command value

### ISSUE THREAD

**Issue by rfay** [drud/ddev#527]
## What happened (or feature request):

When you run `ddev ssh` and do some things, then exit the shell there, you end up back on the host with an error that implies something went wrong with docker-compose:

```
$ ddev ssh
root@1817ba25a159:/var/www/html# ididid
bash: ididid: command not found
root@1817ba25a159:/var/www/html# exit
Failed to ssh randyfay: Failed to run docker-compose [-f /Users/rfay/workspace/randyfay/.ddev/docker-compose.yaml exec web bash]: exit status 127
```

## What you expected to happen:

`ddev ssh` should only show an error if it failed to actually get you into the shell on the container.

## How to reproduce this:

`ddev ssh` and then type a non-command, then exit

**Comment by cweagans** [comment]
This seems to be an upstream issue with both the Docker CLI and docker-compose.

docker-compose:
```
❯ cat docker-compose.yml                     
version: '3'
services:
  mysql:
    image: "mysql:5.7"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
❯ docker-compose exec mysql bash
root@d5e4be35f12b:/# adadadad
bash: adadadad: command not found
root@d5e4be35f12b:/# exit
exit
❯ echo $?
127
```

docker:
```
❯ docker exec -it ddev-drupal-web bash
root@cd899a2232b9:/var/www/html# adadadad
bash: adadadad: command not found
root@cd899a2232b9:/var/www/html# exit
exit
❯ echo $?
127
```

Should we attempt to work around this behavior in ddev? Or go with what the upstream software is doing?

**Comment by tannerjfco** [comment]
I'm not really sure what we can do about this, short of ignoring the error output from the docker-compose call. I don't expect the behavior to change upstream either, as docker largely considers exec to be a development/troubleshooting tool.

Its possible we could get better error information if we re-implemented exec using the go-dockerclient library, but my attempt at this many months back was not successful, and I'm not sure that we'd actually get any better info to handle the error.

We do check for site to be in running state before allowing exec, perhaps we could get away with ignoring the error output here, perhaps make it a debug line rather than normal error. I'd just be concerned with missing a real error.

**Comment by cweagans** [comment]
We can check for different error codes - attempting to exec in a container that doesn't exist gives an exit code of 1. Exec'ing bash inside a container that does exist, but running a missing command inside of that container gives 127. However, I'm really not sure about attempting to circumvent upstream behavior. Consistency seems like a better result here.

**Comment by rfay** [comment]
I'd say we should completely ignore the return code in this case. The only downside of this is that a docker failure won't be properly reported.

**Comment by cweagans** [comment]
So are you saying we should close this? Or something else?

**Comment by rfay** [comment]
let's ignore the proc.Run() result in ComposeNoCapture() 

https://github.com/drud/ddev/blob/97d03df872bd77d414ea0fc16a53e3a10bbff3be/pkg/dockerutil/dockerutils.go#L219-L222

1. Change the signature of ComposeNoCapture (if it doesn't cause trouble) to not return error.
2. Ignore the return with _ = proc.Run()
