### ISSUE TITLE
Tests fail if there is no local Docker daemon

### ISSUE THREAD

**Issue by cweagans** [drud/ddev#547]
## What happened (or feature request):

I attempted to run `make test` without Docker running locally. Some of the tests pass without Docker, but the ones that need Docker failed.

## What you expected to happen:

If no Docker daemon is available, these tests should be skipped (similar to how the Pantheon tests are skipped if there is no DDEV_PANTHEON_API_TOKEN set).

## How to reproduce this:

Run `make test` without Docker running

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

1

**Comment by rfay** [comment]
I don't see any reason to have tests run without docker. ddev is really just a wrapper around docker-compose, so running tests without docker would be like pretending we had tests.

**Comment by rickmanelius** [comment]
I agree with @rfay that this is a scoping error. The goal of our test coverage is a 100% pass. If Docker isn't running, a fail will occur that should indicate that something is amiss. Since ddev is so intimately connected with Docker, I'm having a hard time recognizing the value of only testing the non-docker related features.

If you feel strongly enough, @cweagans, I'm happy to reconsider.
