### ISSUE TITLE
Add DDEV to Drupal.org docs

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#558]
## What happened (or feature request):

* Documentation request

## What you expected to happen:

Drupal has a reasonably robust set of documentation on how to set up Drupal with MAMP, LAMP, WAMP, etc. I've seen little to no reference to the more modern docker tools like DDEV. I would love to see a reference here. See https://www.drupal.org/docs/develop/local-server-setup

**Comment by nearlythere** [comment]
I see this issue is hibernating. 

Adding that I also expected to find it here, where Kalabox is listed. 
https://www.drupal.org/docs/develop/development-tools/development-tools-overview

**Comment by rfay** [comment]
Thanks @nearlythere - I added ddev on https://www.drupal.org/docs/develop/development-tools/development-tools-overview, but that's a pretty long long long page without much prominence. If you run across other places we can insert, we're all ears. 

It does seem we could write a whole new section in https://www.drupal.org/docs/develop/local-server-setup. There are plenty of appropriate and inappropriate things there (aegir? Production site on usb drive?).

**Comment by rickmanelius** [comment]
If we had the ambition (it's more an hour of time), it would probably be good to split out a new section from the local server landing page that @rfay referenced (https://www.drupal.org/docs/develop/local-server-setup) and split out a Docker/Container section that would include DDEV, Lando, Outrigger, Docksal, etc.

**Comment by nearlythere** [comment]
@rfay Yeah it's a long and winding page. Found it through search tho. Incidentally has good positioning for search engine results (google)

- drupal tools	(1)
- drupal administration development tools	(3)

@rickmanelius I could grab that task if you want? I am ambitious!

**Comment by rfay** [comment]
@nearlythere we'd *love* to have you grab that task, and learn from any feedback you have in the process. You *are* ambitious!

**Comment by nearlythere** [comment]
@rfay brilliant! will do! I will tackle Mon-Tues next week.

**Comment by nearlythere** [comment]
@rfay Any feedback on this before I post it? I think I need a better introduction. 

FYI - This is a child page to: [Local Server Set up on d.o](https://www.drupal.org/docs/develop/local-server-setup) After consideration, I think it’s better to add a child page instead of a new Guide. A guide would mean another step of navigation and a page PER solution. In that case, each page would likely duplicate content from the documentation of those projects and come out of sync quickly.

It will be similar to this page for VMs which includes some basic information and then a list of solutions.
[https://www.drupal.org/docs/develop/local-server-setup/virtual-machine-development-enviroments](https://www.drupal.org/docs/develop/local-server-setup/virtual-machine-development-enviroments)

Proposed URL: 
`https://www.drupal.org/docs/develop/local-server-setup/docker-development-environments`

- - - - - 

**Title: Docker Development Environments**

Docker is great for local development environments because of the small footprint and fast start-up times. More open source projects are packaging their stacks as Docker images to speed up the installation and collaboration. 

### Advantages of Docker or container based local development environments

When you use a Docker based development environment, you don’t need to follow a long series of install instructions, and you don’t need to manage the many dependencies involved in a project. When you have it set up, a typical installation or update with Docker is a single line. This is one way Docker based installation and maintenance for local development provides advantages over manual installs. Read [What is Docker](https://www.docker.com/what-docker) for more information.

Whereas a [virtual machine development environment](https://www.drupal.org/docs/develop/local-server-setup/virtual-machine-development-enviroments) virtualises a full operating system a container runs code directly on the host operating system. A virtual machine cordon off a portion of your hard disk to run. On the other hand, a container based environment will take up less hard disk space. This is just one way Docker provides an advantage over virtual machines, for local development in particular. Read [Docker versus Virtual Machines](https://www.aquasec.com/wiki/display/containers/Docker+vs.+Virtual+Machines).

### List of Docker based local dev environments with Drupal stacks or examples

**[DDEV](https://ddev.drud.com/) \- [DDEV on GitHub](https://github.com/drud/ddev)**

*   “[DDEV](https://github.com/drud/ddev) is an open source tool that makes it dead simple to get local PHP development environments up and running within minutes.” Works with Linux, Mac OS, and Windows. Developed by DRUD. [DDEV Documentation](https://ddev.readthedocs.io/en/latest/).

**Docker4Drupal - [Docker4Drupal on GitHub](https://github.com/wodby/docker4drupal)**

*   “Docker4Drupal is a set of docker containers optimized for Drupal. Use docker-compose.yml file from [docker4drupal repository](https://github.com/wodby/docker4drupal) to spin up local environment on Linux, Mac OS X and Windows.” [DDEV Documentation](https://github.com/wodby/docker4drupal/blob/master/docs/index.md).

**[Docksal](https://docksal.io/) \- [Docksal on GitHub](https://github.com/docksal/docksal)**

*   “Docksal is a tool for defining and managing development environments. It uses Docker to create fully containerized environments, along with VirtualBox to support macOS and Windows.” [Docksal Documentation](https://docs.docksal.io/en/master/).

**[Lando](https://docs.devwithlando.io/) \- [Lando on GitHub](https://github.com/lando/lando)**

*   “Lando is for developers who want to quickly specify and painlessly spin up the services and tools needed to develop their projects. It's a free, open source, cross-platform, local development environment and DevOps tool built on [Docker](http://docker.com/) container technology and developed by [Tandem](http://thinktandem.io/).” [Lando Documentation](https://docs.devwithlando.io/).

- - - - 

[Outrigger](http://outrigger.sh/) doesn’t seem to have a Drupal specific examples?

**[Outrigger](http://outrigger.sh/)**

*   Outrigger is a set of developer tools that makes development, integration, staging and production environments simple, portable and, most importantly, CONSISTENT across team members and environments. [Outrigger Documentation](http://docs.outrigger.sh/).

**Comment by rfay** [comment]
Wow, that looks awesome. I think it will be a great improvement. Just how awesome it is, I only have one tiny nit, apparently "macOS" is the correct way to talk about the OS these days. Somebody corrected me on that recently.

**Comment by nearlythere** [comment]
@rfay Thanks Randy! I'll fix that typo. Oops! Looks like you didn't have specific feedback about the content at this point. I will post that on Drupal.org!

**Comment by nearlythere** [comment]
Added the page to the Local Server guide. I'll ping Joe (The maintainer of the guide.)

https://www.drupal.org/docs/develop/local-server-setup/docker-development-environments

**Comment by nearlythere** [comment]
@rfay The page is LIVE. 👏  You can close this one out.

**Comment by rfay** [comment]
You're awesome, thanks!
