### ISSUE TITLE
Add full tests for drupal6, backdrop, typo3

### ISSUE THREAD

**Issue by rfay** [drud/ddev#617]
## What happened (or feature request):

ddevapp_test.go has long had full downloads and various tests for a d7, d8, and wordpress. We should expand that to do our new project types, drupal6, backdrop, and typo3. 

I began just a bit of work on this [here](https://github.com/rfay/ddev/blob/20180123_drupal6_typo3_tests/pkg/ddevapp/ddevapp_test.go#L46-L68)

But it seems that we should get the typo3 support in rather than getting stuck on the tests.

**Comment by rickmanelius** [comment]
Updated assignee because this might require a little of both of your time and we absolutely want to wrap this up by the time we (at least in the pre-existing roadmap) wanted to claim our support for the additional CMSes was no longer alpha/beta/experimental. Let's use this as a meta and split out PRs for each CMS. Leaving this on the active project board to keep top of mind.
