### ISSUE TITLE
What are the obstacles/concerns with using DDEV to host sites in production? 

### ISSUE THREAD

**Issue by nickchomey** [drud/ddev#6311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Given that I love ddev and aim to augment it further for use in development, ci/cd etc, it would be great to use it in production as well. 

The [docs](https://ddev.readthedocs.io/en/stable/users/topics/hosting/#additional-server-setup) as well as various comments in Github issues and discord suggest that DDEV is only really appropriate for hosting smaller sites in production.

So, I'm curious what the concerns are with using it in production for larger sites, so that I can perhaps work to address them through PRs to ddev, or share docs on how I eventually mitigate them through other means.

I assume that some of the concern is with regards to running many - hundreds or thousands - sites. I only intend to run one or a few, but they could be somewhat large. 

Likewise, I assume it isn't currently particularly compatible with horizontal scaling. But that could probably be addressed in one way or another. 

Whatever the case, it would be good to state the concerns in one place so that they could be addressed at some point.

Thanks! 

### Describe your solution

Once the concerns are defined here, they could be addressed within ddev or via docs for external approaches/solutions.

**Comment by rfay** [comment]
DDEV's overall goals are built around local development. That means:

* The `ddev-webserver` is far bigger than one would use for production, because it has all the things in it people want for local development. Even the `ddev-dbserver` is larger than you'd build for production, for the same reasons.
* Even with the "hardened images" feature, DDEV's overall goals aren't built for production security requirements.

When we work on DDEV we mostly think about "How does this work for local development", and have never expanded scope to try to support production, which has completely different performance and security requirements.

**Comment by rfay** [comment]
I expanded my [statement above](https://github.com/ddev/ddev/issues/6311#issuecomment-2166053486) to include discussion of performance and capacity.

> are there any general suggestions you can share about what might be lacking with DDEV's security in a production context

DDEV does several important good things for security, but because there's no security team or focus there's no fundamental review of them. But the good things:

* Containers are run as a normal unprivileged user, unlike many docker-based hosting environments. This prevents rogue code from being able to create setuid files on the host, for example.
* In the hardened images, sudo is removed.
* The current  Traefik`ddev-router` does not have privileges on the Docker socket, which the nginx-proxy router does use, and it could be a massive security problem. However, that was cleaned up when the traefik router was done. 

The potentially bad things:

* Mostly lack of review and design.
* Doesn't use rootless docker, which would be a lot better. It's possible that rootless docker would work with it these days.

**Comment by rfay** [comment]
It's a great conversation, thanks for raising it.

**Comment by rfay** [comment]
Here's an example: In work today on 
* https://github.com/ddev/ddev/pull/6317

I discovered that with traefik router, port 8025/8026 (mailpit) was exposed even when hardened images and let's encrypt were enabled. It turns out that the hardened image is smart enough not to *run* mailpit, so the port goes nowhere, but it shouldn't be used at all.
