### ISSUE TITLE
import-db fails when unable to manage settings files, should warn instead

### ISSUE THREAD

**Issue by rfay** [drud/ddev#704]
## What happened (or feature request):

import-db fails when the settings files slots are both occupied. It should warn instead. This failure is actually after the db has successfully been loaded.

`Failed to import database for typo3-kit: failed to write settings file for typo3-kit: Failed to get TYPO3 AdditionalConfiguration.php file path: settings files already exist and are being managed by the user`,

**Comment by rickmanelius** [comment]
Similar to https://github.com/drud/ddev/issues/743, I'm going to push to have this documented before we release [v0.16.0](https://github.com/drud/ddev/milestone/26) because this might result in a few support issues. This should also less of concern (hopefully) now that we are more proactive about taking on the settings file generation as a result of https://github.com/drud/ddev/issues/692.

**Comment by rfay** [comment]
This was *solved* in #692, but I'm fine if you want to keep it open as the docs placeholder.

**Comment by rickmanelius** [comment]
This was addressed in code and the docs were touched up in #752.
