### ISSUE TITLE
ddev start should use docker-compose up --force-recreate

### ISSUE THREAD

**Issue by rfay** [drud/ddev#716]
## What happened (or feature request):

Custom configuration of nginx and friends doesn't currently take place until the container is recreated, which can be kind of spotty. Our docs are currently saying you have to `ddev rm` and `ddev start` to make it happen. But it wouldn't take much to just use `docker compose up --force-recreate` and this would happen every time on `ddev start`. I think it would be less confusing to people.

**Comment by rickmanelius** [comment]
@rfay I saw a referenced PR merged. I'm assuming there is an additional PR needed to make this change?

**Comment by rfay** [comment]
No, nothing has been done on this issue, in fact it needs a decision. I must have referenced something wrongly? Or was just referring to it?

**Comment by rfay** [comment]
I don't actually think I'd like this, so closing.

**Comment by apotek** [comment]
> I don't actually think I'd like this, so closing.

Lando had a command called `rebuild`. Using language like `rebuild` felt less intimidating to me than `rm` as a user because its never clear to me (despite no longer being a novice) because an `rm` carries with it the sense that the data volumes will also be deleted. Ie, if I do `ddev rm && ddev start` will I lose my 2GB database import? 

I then run `ddev rm --help` to remind myself that unless I pass the `--remove-data` flag, the `rm` will actually just remove the container build, not the data volume 😅 . 

Sometimes the developer experience is improved not just by providing necessary tools or necessary workarounds, but in increasing confidence that I am doing what I intend to be doing. I felt a verb like `rebuild` felt more comfortable than `rm && start`. Just my $0.02.

**Comment by rfay** [comment]
`ddev rm` hasn't been a thing for many years, although it's still hidden in there as an alias. We changed because it could be confusing. But that was probably 7 years ago.

These days we use `ddev stop`, which stops and deletes all containers (and doesn't touch your database). We use `ddev start` (which recreates all containers from scratch). And of course we have `ddev restart`.

`--remove-data` also hasn't been used for some years. We use `ddev delete` these days. It deletes the database and the registration with ddev (so it doesn't show in `ddev list`

Try `ddev help` for more info, and the docs are at https://ddev.readthedocs.io

Have you still really been using `ddev rm`?

**Comment by apotek** [comment]
> Have you still really been using ddev rm?

Yes. I have been using it because if I modify something in, say `.ddev/web-build/Dockerfile.example-file` I don't see any output when I stop and start that would indicate that my changes are being taken into account (because I believe that only the base container checksum is being relied on for knowing when to recreate the container?)

So I have been using `rm` to try to ensure that DDEV will rebuild my container. Sometimes I end up going to the docker prune commands instead, just to make 100% sure that DDEV is forced to rebuild the container. I do this because sometimes I'll add an apt install to a Dockerfile build or some other step and it doesn't always seem to work until I force removal.

**Comment by rfay** [comment]
`rm` is obsolete and not useful. It's an alias for `stop`, please use `ddev stop`.

If you're debugging a Dockerfile, and trying to understand what's going on, please use `ddev debug rebuild`. (`ddev restart` does rebuild if the Dockerfile has changed, and you can look at the .ddev/.webimageBuild/Dockerfile to see that your change has been incorporated. But `ddev debug rebuild` will help you. 

* https://ddev.readthedocs.io/en/stable/users/usage/commands/#debug-rebuild
* https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#debugging-the-dockerfile-build

**Comment by apotek** [comment]
> If you're debugging a Dockerfile, and trying to understand what's going on, please use `ddev debug rebuild`.

Thank you. This is very helpful. I always look for a rebuild command (Lando had one) and I'm glad to see there is one as a subset of debug. I appreciate the guidance and feedback.
