### ISSUE TITLE
How to: Set up a D8/Composer site on Pantheon without CircleCI, custom upstreams, etc.

### ISSUE THREAD

**Issue by dsquaredb** [drud/ddev#747]
After some trial and error, I came up with this "recipe" to use ddev locally to manage a Drupal8 site hosted on Pantheon without having to setup/learn/manage additional tools like CircleCI, custom upstreams, etc. I have tested with creating new sites on Pantheon but have not tested with converting an existing site. 

1. Create a new D8 site on the Pantheon dashboard. Complete the setup of the dev site and commit the settings.php file via the dashboard.
2. Change the development mode on the Pantheon dashboard to Git mode.
3. Do a manual backup of the Pantheon dev site so you will have a database to import into ddev later.
4. Clone the Pantheon dev site into your local directory.
5. Make the following changes to your local project file structure to serve the site from a Web directory instead of the root directory (as noted in the [Pantheon docs](https://pantheon.io/docs/nested-docroot/) about nested docroots)
    - In your project directory, edit pantheon.yml to add this line: web_docroot:true
    - Navigate into the project directory (`cd project-name`)
    - Git push the changed pantheon.yml to the Pantheon dev site
    - Run `mkdir web` to create the web directory
    - Run `git mv -k $(find . -type f -maxdepth 1 | grep -v pantheon.yml) core drush modules profiles sites themes vendor index.php web` to move all the site files into the newly-created web directory
    - Check your project's file structure to confirm the web directory was created and the files were moved. If so, git push these changes to the Pantheon dev site.
6. Run `ddev config pantheon` to add the ddev setup. This will add a .ddev directory in your projects' directory.
7. Run `ddev pull` to pull the Pantheon dev site's database and files directory into your local project.

From this point on, you can use Composer to manage/update the site, install modules, etc. by using the "ddev exec composer" commands.

Not: After you set up the site to be managed via Composer, you must set the Pantheon upstream to empty so it will disable the Pantheon automatic core updates. This can be done using Terminus for Pantheon by running this command: `terminus site:upstream:set <site> empty` where <site> is your Pantheon site name.

**Comment by rfay** [comment]
Thanks so much for this!

**Comment by rickmanelius** [comment]
This is fantastic! Linking to [your blog article](https://dsquaredbconsulting.com/blog/ddev-to-rescue) to provide some of the background motivation. Also, this might be a great example of a HOWTO, and therefore I'm going to cross-link to this issue (https://github.com/drud/ddev/issues/659), where we can decide where to place this information in our docs (even if it's just a section that links back to this issue, for example). I'll close out this issue and we can address in #659.

**Comment by BudWerner** [comment]
Thank you Danita for your excellent post!!!  I have been struggling to set this up myself and with your help I FINALLY got this working on a windows 10 machine.

One question, why must we use `ddev exec composer` prefixes to our commands instead of the standard `ddev composer`?

I tried it both ways and indeed I can only get composer to work using `ddev exec composer`  in place of `ddev composer`

A couple of suggestions to these instructions:

1. The edit to the pantheon.yml file needs a space before the word _true_.  It should read like this: `web_docroot: true` 

2. I used the full `git mv` string provided by Pantheon instead of your post and this put the pantheon.upstream.yml file in the correct place.  Here's the command from pantheon : `git mv -k $(find . -maxdepth 1 -type f | egrep -v 'pantheon.yml|.gitignore|README.md|pantheon.upstream.yml') core drush modules profiles sites themes vendor index.php web`

3. I also made a note of how the directory should look after all of the changes - I'm very new at all of this and needed extra visuals.  The one on Pantheon did not include the .yml files or .gitignore

Site folder
     |--web
          |--core
          |--drush
          |--modules
          |--profiles
          |--sites
               |--default
               |--settings.php
          |--themes
          |--vendor
          |--index.php
    .gitignore
    pantheon.upstream.yml
    pantheon.yml 

4. Also should we add a step to update the .gitignore file to account for the new directory structure?  I'm not sure on this one.

# Ignore paths that contain user-generated content.
web/sites/*/files
web/sites/*/private
web/files/*

# Ignore SimpleTest multi-site environment.
web/sites/simpletest

Thanks again for taking the time to document this. - Alysa

**Comment by rfay** [comment]
When she wrote this, there was no `ddev composer`. It was created mostly for Windows users (because composer is awkward and unpredictable there, see [Windows OS and Composer](https://ddev.readthedocs.io/en/stable/users/developer-tools/#ddev-and-composer) in docs.

**Comment by BudWerner** [comment]
Thanks for this - I looked at that page some time ago, and it didn't quite answer my question - I'm just too new to all of this.  I'll share your response with another developer who is questioning why as well.

Thanks again.
