### ISSUE TITLE
ddev should always recreate docker-compose.yaml

### ISSUE THREAD

**Issue by rfay** [drud/ddev#762]
## What happened (or feature request):

Nearly every release we're having to tell people to delete docker-compose.yaml. We should just take it over and always recreate it. It's possible it should be renamed to something like ddev-docker-compose.yaml. Additional services can add properly named alternates that we won't touch.

**Comment by rickmanelius** [comment]
This is becoming a major pain point for upgrades, particularly on our fast release cycle. We may need to have a better way of prompting users that this is happening or warn when it's about to happen, particularly when a site is live. Let's outline some of these implications:

* Active projects w/running containers.
  * If a project is active and then run their next `ddev` command, do we immediately prompt them?
  * Once we have a project database #642, we can probably prompt to update/upgrade all.
  * Do we warn them to back up in case an upgrade causes them to crash their current site?
* Hooks:
  * I'm assuming this change requires us to also address .ddev/config.yml
  * We should probably move hooks to their old folder similar to this https://github.com/drud/hosting/issues/163#issuecomment-375100012. Otherwise we may rewrite without a user expecting it.
* Naming/Order/Precedence:
  * Docker compose can stack yml files (see https://github.com/drud/ddev/issues/121). We probably want to ensure the managed file is first and then allow services and a final "docker-composer.overrides.yml" at the end.

A simple, out of the gates approach would be:

1. prepend a /* ddev-generated */ at the top
2. simply re-run configure (pulling existing values and hooks) and the next ddev command.
3. output to the end-user that the config.yml file and docker-compose.yml was regenerated.

**Comment by rickmanelius** [comment]
@rfay I'm leaving this as "incubate" label until we can confirm the AC. Once that's the case, I'm fine with tagging with the v0.17.0 milestone and we'll see if something else has to go (if anything) from our goals with this release.

**Comment by rickmanelius** [comment]
Had a convo w/@rfay and we now have this unblocked. @rfay will update the issue summary and I'll preemptively tag actionable.

**Comment by rfay** [comment]
- [ ] Add a marker into docker-compose.yaml to indicate that we own it (like #ddev-generated)
- [ ] Always replace docker-compose.yaml on `ddev start` if we own it.
- [ ] Change config.yaml APIVersion to contain ddev version
- [ ] Warn user on ddev actions if their config.yaml is an old version and suggest that they do `ddev config`
- [ ] Change `ddev config` to update the APIVersion and web container versions (but leave everything else alone, like it currently does). Or probably `ddev config --update`

**Comment by rickmanelius** [comment]
AC looks great to me. Removing myself from the assignee field for now until it's ready for review!

**Comment by rfay** [comment]
When we do this, we should consider stopping using environment variables for substitution in docker-compose.yml. We may still need them for add-on services.

**Comment by rickmanelius** [comment]
Moving out of v0.17.0 because I don't think we'll get to this in time to release. Might be a good follow-up post Drupalcon.
