### ISSUE TITLE
Docker compose links flag is deprecated, but still used

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#813]
## What happened (or feature request):
According to the docker documentation "links" flag is deprecated. It is still used in ddev composer yaml
e.g.
```
web:
    links:
      - db:db
```

https://docs.docker.com/compose/compose-file/#links

**Comment by rfay** [comment]
Color me surprised; I tried to just remove those `links` stanzas because https://docs.docker.com/compose/compose-file/#links basically says they're not useful.

But things blow up in quite surprising ways; it *looks* like other projects' db servers are being hit randomly. So a Drupal install starts but fails partway through, it hits "variable table already exists", implying that it is suddenly hitting the *wrong* "db" container. 

The doc says:

> Links are not required to enable services to communicate - by default, any service can reach any other service at that service’s name.

So it seems there would be no reason for the stanza at all. But it seems there is. Things work perfectly when it's reintroduced.

**Comment by rfay** [comment]
This is a totally valid issue, but I don't think it's going to be worth pursuing until we're forced to pursue it, so flagging hibernate.

**Comment by rfay** [comment]
There may be a docker bug here. 

People have been having trouble with solr being accidentally shared between projects, and removing links does *not* solve that problem:

https://github.com/drud/ddev/blob/1bdcde384c610b3b17834585b1292580fdafe299/pkg/servicetest/testdata/services/docker-compose.solr.yaml#L63-L68

**Comment by rfay** [comment]
As of v1.19, the `links:` stanza is no longer used. Thanks for this issue!
