### ISSUE TITLE
Configure the TLD, change from ddev.local to something else

### ISSUE THREAD

**Issue by mdyoung3** [drud/ddev#834]
## Feature request:
Would it be possible to completely remove the .dev.local and replace it with another domain name? For example, dev.example.edu.

We have SSO that only works with one domain naming convention.

## What you expected to happen:
Alter the YAML file to specific a completely different hostname.

**Comment by rfay** [comment]
Changed the title, hope it reflects your request.

**Comment by rfay** [comment]
I would love it if you could explain more why it's important to use a specific domain name. Most local dev environments don't matter what the FQDN is. Could you please explain more about that? Why would SSO matter for a local dev environment? Wouldn't putting a bogus site (like mysite.yoursso.domain) be a bad thing? And since it wasn't in DNS, wouldn't that break things?

**Comment by cweagans** [comment]
It's really important for SAML authentication and similar authentication mechanisms. When you authenticate against a SAML identity provider (IDP), you are redirected to the IDP, you login, and then you get redirected back to a specific hostname set up in the IDP (with auth information in the URL in query params). Many SAML IDPs will not support redirecting back to an arbitrary URL, so your local environment has to live at a specific hostname. Since the IDP doesn't talk directly to the site you're logging into, not having the site in DNS doesn't affect the success.

**Comment by rickmanelius** [comment]
Adding tags. Noting a somewhat related issue that could open the door for other FQDNs #416.

**Comment by mdyoung3** [comment]
To answer the question of why you would want SSO for local development, it largely boils down to being able to test application(s) in development. In these apps, the user logs in, are registered as a user, and the username is used to fetch additional information via another server. These data are  added to user fields--and used for other applications.

As to your second point, I am not sure exactly what you mean by 'bad thing.' We have gotten SSO to work on local environments before (via Vagrant and Lando), and the applications worked in those environments.

**Comment by mglaman** [comment]
In https://github.com/drud/ddev/blob/06267550c4af2a96d595ec89507c9e59e67a4032/pkg/version/version.go#L50 I see

```
// DDevTLD defines the tld to use for DDev site URLs.
const DDevTLD = "ddev.local"
```

The other items are `var`. Does that mean they can be overridden by environment variables? Or are these only considered when building the tooling itself, not on configuration

**Comment by rfay** [comment]
The others can be overridden by make a build time. Doesn't mean that this shouldn't be configurable at runtime.

**Comment by rfay** [comment]
Closing this one in favor of https://github.com/drud/ddev/issues/868, which solves this problem as well as others. Ever project can have a unique full URL.

**Comment by rfay** [comment]
The TLD does become configurable in https://github.com/drud/ddev/pull/1611, in ddev v1.9
