### ISSUE TITLE
PHP script should be able to access web container by project domain, scheme, port

### ISSUE THREAD

**Issue by tmotyl** [drud/ddev#842]
## What happened (or feature request):
I would like to be able to access web container domain from within the container.

```
ddev ssh
ping myproject.ddev.local
ping: unknown host myproject.ddev.local

```
This is useful when e.g. indexing/crawling the page by the solr search engine.

## What you expected to happen:
the ping resolves domain correctly to localhost and pong back.

I'm working around it right now with custom docker-compose file:
```
#file .ddev/docker-compose.hosts.yaml
version: '3'
services:
  web:
    extra_hosts:
     - "${DDEV_SITENAME}.ddev.local:127.0.0.1"

```
## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

ddev 0.18

**Comment by rfay** [comment]
It seems like we could get the FQDN (like `myproject.ddev.local` in there fairly easily, just using your technique. One cannot expect that the port on the web container will be the same as the configured port on the official FQDN though, since the port listening is done on the router.

**Comment by tmotyl** [comment]
Hmm, the port is quite a limitation. Shouldnt we then setup the FQDN to point to the router ip?

**Comment by rfay** [comment]
Setting the FQDN in containers to point to the ddev-router could work; it would then only be useful for http/s traffic though.

**Comment by rfay** [comment]
@tmotyl could you please go into more detail about your application? We can easily add the official .ddev.local hostname(s) (pointing to the router) to the web container's extra_hosts at startup, but it will only work for http/s traffic. We could also add extra_hosts as 127.0.0.1, but it wouldn't be possible for a local application to know what port the webserver was on (although it would work for most people, since it's on 80 inside the container). Anyway, if you could explain a bit more; we just don't want to do something that doesn't actually solve your problem.

**Comment by galoppi** [comment]
@rfay: for TYPO3 we need your solution with the official .ddev.local hostname(s) pointing to the router.
Do you know a workaround until this is implemented? I don't know how to handle this in a docker-compose.override.yaml as I don't have access to the ddev-router service in a particular ddev project

**Comment by rfay** [comment]
In the web container, you can just use http://localhost/<uri>, does that solve your problem?

**Comment by rfay** [comment]
Also, better if you need the official hostname, try a docker-compose.extrahost.yaml with
```
version: '3'
services:
  web:
    extra_hosts:
     - "${DDEV_SITENAME}.ddev.local:127.0.0.1"
```

**Comment by galoppi** [comment]
@rfay That doesn't work because SSL is terminated by the ddev-router, not the nginx in web container.
So we need the IP of the ddev-router for ${DDEV_SITENAME}.ddev.local, f.e.
 ```version: '3'
services:
  web:
    extra_hosts:
     - "${DDEV_SITENAME}.ddev.local:${DDEV_ROUTER_IP}"
```
Another problem is, that curl and file_get_contents() on webserver isn't able to accept the self-signed insecure SSL certificate.

**Comment by rfay** [comment]
Edited to add that this really needs to be a fully useful URL, meaning scheme and port need to be supported.
